# Logit Models

Converted from `Code/r_01_logits.R` — R-kernel Jupyter port. Outputs tables to `Output/Tables/` and figures to `Output/Images/Graphs/`. Run the setup cell first, then sections in order.

In [1]:
pacman::p_load(
  sf, tidyverse, stargazer, dplyr,
  raster, spdep, sp, ggplot2, robust,
  lmtest, sandwich, car, jsonlite, conleyreg
)

PROJECT_ROOT <- tryCatch(
  normalizePath(file.path(dirname(rstudioapi::getActiveDocumentContext()$path), "..")),
  error = function(e) {
    cwd <- normalizePath(getwd())
    if (basename(cwd) == "Code") dirname(cwd) else cwd
  }
)
setwd(PROJECT_ROOT)
# Load pretty dictionary for labels
pretty_dict <- fromJSON("Code/pretty_dict.json")

pdf <- read_sf(dsn = "Data/Processed/northParishFlows.shp")

## Section 1: Main Parish-Level Logit Models

Monastic variables per arable km²

In [2]:
# Standardize and center continuous variables.
# Binary dummies (smHouse, bigHouse, mg_fsnub, mg_court, friary) are NOT standardized.
for (v in c(
  # Total monastic land (3 normalizations)
  "llandOwned", "llo_sk", "llo_arak",
  # Small/large split land (3 normalizations)
  "lsmLand", "lbigLand",
  "lsm_sk",  "lbg_sk",
  "lsm_arak","lbg_arak",
  # Off-site/on-site split land (3 normalizations)
  "lotherLand", "lownLand",
  "loth_sk",    "lown_sk",
  "loth_arak",  "lown_arak",
  # Tithes, alms, net income (3 normalizations each)
  "ltitheOutT", "lti_sk", "lti_arak",
  "lalmsInTot", "lal_sk", "lal_arak",
                "lni_sk", "lni_arak",
  # Controls (continuous)
  "lLStax_pc", "wet_1535", "wet_1536", "lpopC",
  "area", "mean_slope", "distScot"
)) {
  pdf[[v]] <- scale(pdf[[v]], center = TRUE, scale = TRUE)[, 1]
}

# --- Controls shared across all specifications ----------------------------
# mg_fsnub / mg_court: 20 km binary proximity dummies — not standardized.
controls <- c("mg_fsnub", "mg_court",
              "lLStax_pc", "wet_1535", "wet_1536", "lpopC",
              "uplands", "lowlands", "area", "mean_slope", "distScot")
hide_vars <- c("Constant", "uplands", "lowlands", "area", "mean_slope")
full_controls_formula <- paste(controls, collapse = " + ")

# --- Nine monastic-variable specifications --------------------------------
monastic_specs <- list(
  total_raw = list(
    monastic_vars = c("llandOwned", "ltitheOutT", "lalmsInTot",
                      "smHouse", "bigHouse", "friary"),
    var_list_list = list(
      c("llandOwned", "smHouse", "bigHouse"),
      c("ltitheOutT", "lalmsInTot", "friary"),
      c("lLStax_pc", "lpopC", "wet_1535", "wet_1536"),
      c("uplands", "lowlands", "area", "mean_slope")
    ),
    suffix = "_total_raw"
  ),
  total_sk = list(
    monastic_vars = c("llo_sk", "lti_sk", "lal_sk",
                      "smHouse", "bigHouse", "friary"),
    var_list_list = list(
      c("llo_sk", "smHouse", "bigHouse"),
      c("lti_sk", "lal_sk", "friary"),
      c("lLStax_pc", "lpopC", "wet_1535", "wet_1536"),
      c("uplands", "lowlands", "area", "mean_slope")
    ),
    suffix = "_total_sk"
  ),
  total_arak = list(
    monastic_vars = c("llo_arak", "lti_arak", "lal_arak", "lni_arak",
                      "smHouse", "bigHouse", "friary"),
    var_list_list = list(
      c("llo_arak", "smHouse", "bigHouse"),
      c("lti_arak", "lal_arak", "lni_arak", "friary"),
      c("lLStax_pc", "lpopC", "wet_1535", "wet_1536"),
      c("uplands", "lowlands", "area", "mean_slope")
    ),
    suffix = "_total_arak"
  ),
  split_raw = list(
    monastic_vars = c("lsmLand", "lbigLand", "ltitheOutT", "lalmsInTot",
                      "smHouse", "bigHouse", "friary"),
    var_list_list = list(
      c("lsmLand", "lbigLand", "smHouse", "bigHouse"),
      c("ltitheOutT", "lalmsInTot", "friary"),
      c("lLStax_pc", "lpopC", "wet_1535", "wet_1536"),
      c("uplands", "lowlands", "area", "mean_slope")
    ),
    suffix = "_split_raw"
  ),
  split_sk = list(
    monastic_vars = c("lsm_sk", "lbg_sk", "lti_sk", "lal_sk",
                      "smHouse", "bigHouse", "friary"),
    var_list_list = list(
      c("lsm_sk", "lbg_sk", "smHouse", "bigHouse"),
      c("lti_sk", "lal_sk", "friary"),
      c("lLStax_pc", "lpopC", "wet_1535", "wet_1536"),
      c("uplands", "lowlands", "area", "mean_slope")
    ),
    suffix = "_split_sk"
  ),
  split_arak = list(
    monastic_vars = c("lsm_arak", "lbg_arak", "lti_arak", "lal_arak", "lni_arak",
                      "smHouse", "bigHouse", "friary"),
    var_list_list = list(
      c("lsm_arak", "lbg_arak", "smHouse", "bigHouse"),
      c("lti_arak", "lal_arak", "lni_arak", "friary"),
      c("lLStax_pc", "lpopC", "wet_1535", "wet_1536"),
      c("uplands", "lowlands", "area", "mean_slope")
    ),
    suffix = "_split_arak"
  ),
  ownOther_raw = list(
    monastic_vars = c("lotherLand", "lownLand", "ltitheOutT", "lalmsInTot",
                      "smHouse", "bigHouse", "friary"),
    var_list_list = list(
      c("lotherLand", "lownLand", "smHouse", "bigHouse"),
      c("ltitheOutT", "lalmsInTot", "friary"),
      c("lLStax_pc", "lpopC", "wet_1535", "wet_1536"),
      c("uplands", "lowlands", "area", "mean_slope")
    ),
    suffix = "_ownOther_raw"
  ),
  ownOther_sk = list(
    monastic_vars = c("loth_sk", "lown_sk", "lti_sk", "lal_sk",
                      "smHouse", "bigHouse", "friary"),
    var_list_list = list(
      c("loth_sk", "lown_sk", "smHouse", "bigHouse"),
      c("lti_sk", "lal_sk", "friary"),
      c("lLStax_pc", "lpopC", "wet_1535", "wet_1536"),
      c("uplands", "lowlands", "area", "mean_slope")
    ),
    suffix = "_ownOther_sk"
  ),
  ownOther_arak = list(
    monastic_vars = c("loth_arak", "lown_arak", "lti_arak", "lal_arak", "lni_arak",
                      "smHouse", "bigHouse", "friary"),
    var_list_list = list(
      c("loth_arak", "lown_arak", "smHouse", "bigHouse"),
      c("lti_arak", "lal_arak", "lni_arak", "friary"),
      c("lLStax_pc", "lpopC", "wet_1535", "wet_1536"),
      c("uplands", "lowlands", "area", "mean_slope")
    ),
    suffix = "_ownOther_arak"
  )
)

# --- Helper: coefficient plot for a full GLM model -----------------------
make_logit_plot <- function(model, plot_vars, pretty_dict,
                            x_label = "Coefficient (Log Odds / Log Count)") {
  cs        <- summary(model)$coefficients
  coef_rows <- lapply(plot_vars, function(v) {
    if (!v %in% rownames(cs)) return(NULL)
    est <- cs[v, "Estimate"];  se <- cs[v, "Std. Error"]
    data.frame(variable  = v,
               coefficient = est, se = se,
               ci_lower  = est - 1.645 * se,
               ci_upper  = est + 1.645 * se,
               p_value   = cs[v, ncol(cs)])
  })
  coef_df <- bind_rows(coef_rows)
  if (nrow(coef_df) == 0) return(NULL)
  labels_vec             <- unlist(pretty_dict)
  coef_df$variable_label <- unname(labels_vec[coef_df$variable])
  coef_df$significant    <- coef_df$p_value < 0.10
  coef_df$order          <- match(coef_df$variable, plot_vars)
  lvl_order              <- order(-coef_df$order)
  coef_df$variable_label <- factor(coef_df$variable_label,
                                    levels = coef_df$variable_label[lvl_order])
  ggplot(coef_df, aes(x = coefficient, y = variable_label)) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "gray50") +
    geom_errorbar(aes(xmin = ci_lower, xmax = ci_upper),
                  width = 0.2, color = "gray30", orientation = "y") +
    geom_point(aes(color = significant), size = 3) +
    scale_color_manual(values = c("FALSE" = "gray60", "TRUE" = "#0072B2"),
                       labels = c("FALSE" = "Not Significant", "TRUE" = "p < 0.10")) +
    labs(x = x_label, y = "", color = "Significance") +
    theme_minimal() +
    theme(axis.text.x    = element_text(size = 14),
          axis.text.y    = element_text(size = 14),
          axis.title.x   = element_text(size = 14),
          legend.text    = element_text(size = 13),
          legend.title   = element_text(size = 13),
          legend.position = "bottom")
}

# --- Helper: Conley (spatial HAC) SEs at 100 km for a GLM model ----------
# pdf is the sf object read at the top; conleyreg uses its geometry for distances.
conley_glm_se <- function(glm_mod, family_lab, cutoff_km = 100) {
  fm <- formula(glm_mod)
  cr <- tryCatch(
    conleyreg(
      formula     = fm,
      data        = pdf,
      dist_cutoff = cutoff_km,
      model       = family_lab,
      kernel      = "bartlett",
      verbose     = FALSE
    ),
    error = function(e) {
      cat("conleyreg failed:", conditionMessage(e), "\n"); NULL
    }
  )
  if (is.null(cr)) return(NULL)
  out <- setNames(rep(NA_real_, length(coef(glm_mod))), names(coef(glm_mod)))
  out[rownames(cr)] <- cr[, "Std. Error"]
  out
}

# --- Helper: run the full monastic analysis for one spec -----------------
run_monastic_spec <- function(spec_name, spec) {
  mon_vars      <- spec$monastic_vars
  var_list_list <- spec$var_list_list
  sfx           <- spec$suffix

  mon_cov_order  <- c(mon_vars, "mg_fsnub", "mg_court",
                      "lLStax_pc", "wet_1535", "wet_1536", "lpopC", "distScot")
  mon_cov_labels <- unlist(pretty_dict[mon_cov_order])

  # (a) Single-variable logit tables — one column per monastic var ----------
  muster_list <- list(); primary_list <- list(); seat_list <- list()
  for (var in mon_vars) {
    muster_list[[var]]  <- glm(paste("muster ~",  var, "+", full_controls_formula),
                               data = pdf, family = binomial(link = "logit"))
    primary_list[[var]] <- glm(paste("primary ~", var, "+", full_controls_formula),
                               data = pdf, family = binomial(link = "logit"))
    seat_list[[var]]    <- glm(paste("seats ~",   var, "+", full_controls_formula),
                               data = pdf, family = "poisson")
  }
  muster_ses  <- lapply(muster_list,  function(m) conley_glm_se(m, "logit"))
  primary_ses <- lapply(primary_list, function(m) conley_glm_se(m, "logit"))
  seat_ses    <- lapply(seat_list,    function(m) conley_glm_se(m, "poisson"))

  stargazer(muster_list, type = "latex",
    title   = paste0("Muster — Monastic Variables [", spec_name, "]"),
    label   = paste0("tab:muster_monastic", sfx),
    se      = muster_ses,
    omit    = hide_vars, covariate.labels = mon_cov_labels,
    add.lines = list(c("Controls", rep("Y", length(mon_vars))),
                     c("Conley SEs (100 km)", rep("Y", length(mon_vars)))),
    align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"),
    table.placement = "H",
    out = paste0("Output/Tables/muster_monastic", sfx, ".tex"))
  stargazer(primary_list, type = "latex",
    title   = paste0("Primary — Monastic Variables [", spec_name, "]"),
    label   = paste0("tab:primary_monastic", sfx),
    se      = primary_ses,
    omit    = hide_vars, covariate.labels = mon_cov_labels,
    add.lines = list(c("Controls", rep("Y", length(mon_vars))),
                     c("Conley SEs (100 km)", rep("Y", length(mon_vars)))),
    align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"),
    table.placement = "H",
    out = paste0("Output/Tables/primary_monastic", sfx, ".tex"))
  stargazer(seat_list, type = "latex",
    title   = paste0("Seats — Monastic Variables [", spec_name, "]"),
    label   = paste0("tab:seat_monastic", sfx),
    se      = seat_ses,
    omit    = hide_vars, covariate.labels = mon_cov_labels,
    add.lines = list(c("Controls", rep("Y", length(mon_vars))),
                     c("Conley SEs (100 km)", rep("Y", length(mon_vars)))),
    align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"),
    table.placement = "H",
    out = paste0("Output/Tables/seat_monastic", sfx, ".tex"))

  # (b) Progressive model building -----------------------------------------
  fit_prog <- function(dep, family) {
    out <- list(); vl <- c(); i <- 1
    for (vs in var_list_list) {
      vl <- c(vl, vs)
      out[[i]] <- glm(paste(dep, "~", paste(vl, collapse = " + ")),
                      data = pdf, family = family)
      i <- i + 1
    }
    out
  }
  muster_prog  <- fit_prog("muster",  binomial(link = "logit"))
  primary_prog <- fit_prog("primary", binomial(link = "logit"))
  seat_prog    <- fit_prog("seats",   "poisson")

  muster_prog_ses  <- lapply(muster_prog,  function(m) conley_glm_se(m, "logit"))
  primary_prog_ses <- lapply(primary_prog, function(m) conley_glm_se(m, "logit"))
  seat_prog_ses    <- lapply(seat_prog,    function(m) conley_glm_se(m, "poisson"))

  prog_order      <- unlist(var_list_list[1:3])
  cov_labels_prog <- unlist(pretty_dict[prog_order])
  stargazer(muster_prog, type = "latex",
    title = paste0("Muster — Progressive Model [", spec_name, "]"),
    label = paste0("tab:muster_all", sfx),
    se    = muster_prog_ses,
    omit  = hide_vars, covariate.labels = cov_labels_prog,
    add.lines = list(c("Controls", "N", "N", "N", "Y"),
                     c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
    align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"),
    table.placement = "H",
    out = paste0("Output/Tables/muster_all", sfx, ".tex"))
  stargazer(primary_prog, type = "latex",
    title = paste0("Primary — Progressive Model [", spec_name, "]"),
    label = paste0("tab:primary_all", sfx),
    se    = primary_prog_ses,
    omit  = hide_vars, covariate.labels = cov_labels_prog,
    add.lines = list(c("Controls", "N", "N", "N", "Y"),
                     c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
    align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"),
    table.placement = "H",
    out = paste0("Output/Tables/primary_all", sfx, ".tex"))
  stargazer(seat_prog, type = "latex",
    title = paste0("Seats — Progressive Model [", spec_name, "]"),
    label = paste0("tab:seat_all", sfx),
    se    = seat_prog_ses,
    omit  = hide_vars, covariate.labels = cov_labels_prog,
    add.lines = list(c("Controls", "N", "N", "N", "Y"),
                     c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
    align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"),
    table.placement = "H",
    out = paste0("Output/Tables/seat_all", sfx, ".tex"))

  # (c) Full joint model — muster / primary / seats in columns -------------
  all_mon_formula <- paste(mon_vars, collapse = " + ")
  full_muster  <- glm(paste("muster ~",  all_mon_formula, "+", full_controls_formula),
                      data = pdf, family = binomial(link = "logit"))
  full_primary <- glm(paste("primary ~", all_mon_formula, "+", full_controls_formula),
                      data = pdf, family = binomial(link = "logit"))
  full_seat    <- glm(paste("seats ~",   all_mon_formula, "+", full_controls_formula),
                      data = pdf, family = "poisson")

  full_muster_se  <- conley_glm_se(full_muster,  "logit")
  full_primary_se <- conley_glm_se(full_primary, "logit")
  full_seat_se    <- conley_glm_se(full_seat,    "poisson")

  stargazer(full_muster, full_primary, full_seat, type = "latex",
    title   = paste0("Full Monastic Model [", spec_name, "]"),
    label   = paste0("tab:full_monastic", sfx),
    se      = list(full_muster_se, full_primary_se, full_seat_se),
    omit    = hide_vars, covariate.labels = mon_cov_labels,
    column.labels = c("Muster", "Primary", "Seats"),
    add.lines = list(c("Conley SEs (100 km)", "Y", "Y", "Y")),
    align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"),
    table.placement = "H",
    out = paste0("Output/Tables/full_monastic", sfx, ".tex"))

  # (d) Coefficient plots for the full joint model
  plot_vars <- c(mon_vars, "mg_fsnub", "mg_court",
                 "lLStax_pc", "wet_1535", "wet_1536", "lpopC")
  for (nm in c("muster", "primary", "seats")) {
    mod <- switch(nm, muster = full_muster, primary = full_primary, seats = full_seat)
    p   <- make_logit_plot(mod, plot_vars, pretty_dict)
    if (!is.null(p)) {
      ggsave(paste0("Output/Images/Graphs/logit_", nm, sfx, ".png"),
             plot = p, width = 10, height = 6, dpi = 300)
    }
  }

  list(muster = full_muster, primary = full_primary, seat = full_seat)
}

# --- Run all nine specs ---------------------------------------------------
full_models_by_spec <- list()
for (spec_name in names(monastic_specs)) {
  full_models_by_spec[[spec_name]] <- run_monastic_spec(
    spec_name, monastic_specs[[spec_name]]
  )
}

# Back-compat aliases: split_arak is the primary per-arable-km² specification
monastic_vars <- monastic_specs$split_arak$monastic_vars
full_muster   <- full_models_by_spec$split_arak$muster
full_primary  <- full_models_by_spec$split_arak$primary
full_seat     <- full_models_by_spec$split_arak$seat

# --- DAG Regressions (minimal adjustment set) ----------------------------
dag_vars_labels <- c("llo_arak", "lpopC", "lLStax_pc")
dag_cov_labels  <- unlist(pretty_dict[dag_vars_labels])

dag_muster  <- glm(muster  ~ llo_arak + lpopC + lLStax_pc,
                   data = pdf, family = binomial(link = "logit"))
dag_primary <- glm(primary ~ llo_arak + lpopC + lLStax_pc,
                   data = pdf, family = binomial(link = "logit"))
dag_seat    <- glm(seats   ~ llo_arak + lpopC + lLStax_pc,
                   data = pdf, family = "poisson")

dag_muster_se  <- conley_glm_se(dag_muster,  "logit")
dag_primary_se <- conley_glm_se(dag_primary, "logit")
dag_seat_se    <- conley_glm_se(dag_seat,    "poisson")

stargazer(dag_muster, dag_primary, dag_seat,
  type = "latex", title = "DAG Results", label = "tab:dag",
  se   = list(dag_muster_se, dag_primary_se, dag_seat_se),
  align = TRUE, column.sep.width = ".5pt",
  covariate.labels = dag_cov_labels,
  column.labels    = c("Muster", "Primary", "Seats"),
  add.lines        = list(c("Conley SEs (100 km)", "Y", "Y", "Y")),
  omit.stat        = c("aic"), table.placement = "H",
  out = "Output/Tables/dag.tex"
)

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:21
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Monastic Variables [total_raw]}
  \label{tab:muster_monastic_total_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{6}{c}{\textit{Dependent variable:}} \\
\cline{2-7}
\\[-1.8ex] & \multicolumn{6}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.206 &  &  &  &  &  \\
  & (0.151) &  &  &  &  &  \\
  & & & & & & \\
 ln(Tithe) &  & -0.113 &  &  &  &  \\
  &  & (0.151) &  &  &  &  \\
  & & & & & & \\
 ln(Alms) &  &  & 0.216^{**} &  &  &  \\
  &  &  & (0.091) &  &  &  \\
  & & & & & & \\
 Small House Proximity (20km) &  &  &  & -0.425 &  &  \\
  &  &  &  & (0.543) &  &  \\
  & & & & & & \\
 Large House Proximity (20km) &  &  &  &  & 0.608^{*} &  \\
  &  &  &  &  & (0.317) &  \\
  & & & & & & \\
 Friary Presence &  &  &  &  &  & 0.643 \\
  &  &  &  &  &  & (0.429) \\
  & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.546 & -0.589 & -0.669 & -0.551 & -0.626 & -0.607 \\
  & (0.491) & (0.506) & (0.501) & (0.515) & (0.506) & (0.511) \\
  & & & & & & \\
 Court Officer Proximity (20 km) & 0.289 & 0.383 & 0.365 & 0.368 & 0.290 & 0.368 \\
  & (0.380) & (0.424) & (0.440) & (0.444) & (0.420) & (0.441) \\
  & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.184 & 0.214^{*} & 0.201^{*} & 0.220^{*} & 0.187 & 0.201 \\
  & (0.132) & (0.130) & (0.122) & (0.134) & (0.124) & (0.129) \\
  & & & & & & \\
 Wet 1535 Weather Shock & -0.030 & 0.032 & 0.001 & 0.046 & -0.065 & 0.037 \\
  & (0.225) & (0.219) & (0.224) & (0.231) & (0.239) & (0.210) \\
  & & & & & & \\
 Wet 1536 Weather Shock & 0.119 & 0.069 & 0.089 & 0.054 & 0.149 & 0.063 \\
  & (0.149) & (0.142) & (0.158) & (0.154) & (0.176) & (0.143) \\
  & & & & & & \\
 ln(Population) & 0.367^{**} & 0.390^{**} & 0.369^{**} & 0.377^{**} & 0.396^{**} & 0.368^{**} \\
  & (0.164) & (0.164) & (0.170) & (0.165) & (0.165) & (0.160) \\
  & & & & & & \\
 Distance to Scotland & -0.530^{**} & -0.505^{**} & -0.513^{**} & -0.526^{**} & -0.568^{**} & -0.496^{**} \\
  & (0.247) & (0.248) & (0.249) & (0.242) & (0.242) & (0.252) \\
  & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-164.417} & \multicolumn{1}{c}{-164.799} & \multicolumn{1}{c}{-163.427} & \multicolumn{1}{c}{-164.785} & \multicolumn{1}{c}{-164.003} & \multicolumn{1}{c}{-164.686} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{6}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:22
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Monastic Variables [total_raw]}
  \label{tab:primary_monastic_total_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{6}{c}{\textit{Dependent variable:}} \\
\cline{2-7}
\\[-1.8ex] & \multicolumn{6}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.507^{*} &  &  &  &  &  \\
  & (0.299) &  &  &  &  &  \\
  & & & & & & \\
 ln(Tithe) &  & 0.054 &  &  &  &  \\
  &  & (0.203) &  &  &  &  \\
  & & & & & & \\
 ln(Alms) &  &  & 0.317^{***} &  &  &  \\
  &  &  & (0.086) &  &  &  \\
  & & & & & & \\
 Small House Proximity (20km) &  &  &  & -1.113^{**} &  &  \\
  &  &  &  & (0.515) &  &  \\
  & & & & & & \\
 Large House Proximity (20km) &  &  &  &  & 0.617 &  \\
  &  &  &  &  & (0.544) &  \\
  & & & & & & \\
 Friary Presence &  &  &  &  &  & 0.626 \\
  &  &  &  &  &  & (0.528) \\
  & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.470 & -0.575 & -0.775 & -0.447 & -0.624 & -0.599 \\
  & (0.681) & (0.685) & (0.701) & (0.634) & (0.662) & (0.707) \\
  & & & & & & \\
 Court Officer Proximity (20 km) & -0.104 & 0.128 & 0.140 & 0.184 & 0.049 & 0.148 \\
  & (0.296) & (0.328) & (0.360) & (0.353) & (0.351) & (0.354) \\
  & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.137 & 0.177 & 0.167 & 0.252 & 0.161 & 0.180 \\
  & (0.230) & (0.230) & (0.222) & (0.203) & (0.202) & (0.220) \\
  & & & & & & \\
 Wet 1535 Weather Shock & -0.175 & -0.017 & -0.055 & 0.042 & -0.097 & -0.012 \\
  & (0.170) & (0.164) & (0.168) & (0.181) & (0.173) & (0.155) \\
  & & & & & & \\
 Wet 1536 Weather Shock & 0.545^{**} & 0.386^{*} & 0.409^{*} & 0.324 & 0.461^{*} & 0.383^{*} \\
  & (0.231) & (0.214) & (0.239) & (0.217) & (0.258) & (0.215) \\
  & & & & & & \\
 ln(Population) & 0.426^{**} & 0.456^{**} & 0.438^{**} & 0.430^{**} & 0.471^{**} & 0.439^{**} \\
  & (0.193) & (0.189) & (0.205) & (0.180) & (0.185) & (0.184) \\
  & & & & & & \\
 Distance to Scotland & -0.638^{*} & -0.571 & -0.612 & -0.642^{*} & -0.641 & -0.555 \\
  & (0.381) & (0.373) & (0.375) & (0.365) & (0.410) & (0.376) \\
  & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-86.517} & \multicolumn{1}{c}{-88.123} & \multicolumn{1}{c}{-85.892} & \multicolumn{1}{c}{-87.012} & \multicolumn{1}{c}{-87.607} & \multicolumn{1}{c}{-87.977} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{6}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:22
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Monastic Variables [total_raw]}
  \label{tab:seat_monastic_total_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{6}{c}{\textit{Dependent variable:}} \\
\cline{2-7}
\\[-1.8ex] & \multicolumn{6}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.239^{**} &  &  &  &  &  \\
  & (0.112) &  &  &  &  &  \\
  & & & & & & \\
 ln(Tithe) &  & 0.132 &  &  &  &  \\
  &  & (0.113) &  &  &  &  \\
  & & & & & & \\
 ln(Alms) &  &  & 0.055 &  &  &  \\
  &  &  & (0.066) &  &  &  \\
  & & & & & & \\
 Small House Proximity (20km) &  &  &  & 0.705^{*} &  &  \\
  &  &  &  & (0.421) &  &  \\
  & & & & & & \\
 Large House Proximity (20km) &  &  &  &  & 0.672^{**} &  \\
  &  &  &  &  & (0.301) &  \\
  & & & & & & \\
 Friary Presence &  &  &  &  &  & -0.568 \\
  &  &  &  &  &  & (0.890) \\
  & & & & & & \\
 Snubbed Family Proximity (20 km) & 0.130 & 0.090 & 0.057 & 0.051 & 0.006 & 0.082 \\
  & (0.363) & (0.383) & (0.397) & (0.390) & (0.389) & (0.384) \\
  & & & & & & \\
 Court Officer Proximity (20 km) & 0.628^{***} & 0.710^{***} & 0.741^{***} & 0.730^{***} & 0.693^{***} & 0.745^{***} \\
  & (0.214) & (0.244) & (0.258) & (0.253) & (0.244) & (0.259) \\
  & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.377^{***} & 0.375^{***} & 0.383^{***} & 0.378^{***} & 0.391^{***} & 0.389^{***} \\
  & (0.069) & (0.081) & (0.075) & (0.072) & (0.065) & (0.071) \\
  & & & & & & \\
 Wet 1535 Weather Shock & 0.045 & 0.122 & 0.127 & 0.127 & 0.005 & 0.134 \\
  & (0.141) & (0.134) & (0.136) & (0.140) & (0.132) & (0.140) \\
  & & & & & & \\
 Wet 1536 Weather Shock & 0.409^{***} & 0.350^{**} & 0.350^{**} & 0.354^{**} & 0.464^{***} & 0.345^{**} \\
  & (0.137) & (0.136) & (0.138) & (0.142) & (0.123) & (0.141) \\
  & & & & & & \\
 ln(Population) & 0.014 & 0.029 & 0.025 & 0.037 & 0.031 & 0.046 \\
  & (0.075) & (0.081) & (0.080) & (0.080) & (0.075) & (0.078) \\
  & & & & & & \\
 Distance to Scotland & -0.879^{***} & -0.856^{***} & -0.852^{***} & -0.833^{***} & -0.935^{***} & -0.856^{***} \\
  & (0.288) & (0.290) & (0.293) & (0.296) & (0.305) & (0.291) \\
  & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-286.660} & \multicolumn{1}{c}{-287.656} & \multicolumn{1}{c}{-288.409} & \multicolumn{1}{c}{-288.060} & \multicolumn{1}{c}{-285.824} & \multicolumn{1}{c}{-288.406} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{6}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:25
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Progressive Model [total_raw]}
  \label{tab:muster_all_total_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.430^{**} & 0.397^{***} & 0.225^{*} & 0.183 \\
  & (0.171) & (0.137) & (0.127) & (0.117) \\
  & & & & \\
 Small House Proximity (20km) & -1.014^{***} & -1.092^{***} & -0.646 & -0.474 \\
  & (0.336) & (0.363) & (0.691) & (0.638) \\
  & & & & \\
 Large House Proximity (20km) & -0.345 & -0.381 & 0.060 & 0.249 \\
  & (0.391) & (0.388) & (0.382) & (0.361) \\
  & & & & \\
 ln(Tithe) &  & -0.222^{**} & -0.299^{**} & -0.297^{**} \\
  &  & (0.097) & (0.118) & (0.138) \\
  & & & & \\
 ln(Alms) &  & 0.277^{***} & 0.276^{***} & 0.245^{***} \\
  &  & (0.074) & (0.070) & (0.074) \\
  & & & & \\
 Friary Presence &  & 0.939^{***} & 0.523 & 0.691 \\
  &  & (0.327) & (0.419) & (0.422) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.003 & 0.047 \\
  &  &  & (0.164) & (0.161) \\
  & & & & \\
 ln(Population) &  &  & 0.403^{***} & 0.326^{**} \\
  &  &  & (0.109) & (0.157) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.083 & -0.054 \\
  &  &  & (0.236) & (0.267) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.391^{***} & 0.271 \\
  &  &  & (0.152) & (0.185) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-243.879} & \multicolumn{1}{c}{-238.117} & \multicolumn{1}{c}{-167.131} & \multicolumn{1}{c}{-164.627} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:25
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Progressive Model [total_raw]}
  \label{tab:primary_all_total_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.713^{***} & 0.648^{***} & 0.455 & 0.411 \\
  & (0.239) & (0.244) & (0.326) & (0.294) \\
  & & & & \\
 Small House Proximity (20km) & -1.266^{***} & -1.318^{**} & -1.234^{*} & -1.225^{**} \\
  & (0.479) & (0.514) & (0.664) & (0.609) \\
  & & & & \\
 Large House Proximity (20km) & -0.576 & -0.638 & 0.009 & 0.039 \\
  & (0.589) & (0.576) & (0.542) & (0.498) \\
  & & & & \\
 ln(Tithe) &  & -0.150 & -0.224 & -0.243 \\
  &  & (0.154) & (0.202) & (0.235) \\
  & & & & \\
 ln(Alms) &  & 0.255^{**} & 0.331^{***} & 0.306^{***} \\
  &  & (0.105) & (0.062) & (0.073) \\
  & & & & \\
 Friary Presence &  & 0.380 & 0.570 & 0.741 \\
  &  & (0.606) & (0.703) & (0.481) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & -0.038 & -0.016 \\
  &  &  & (0.246) & (0.232) \\
  & & & & \\
 ln(Population) &  &  & 0.402^{***} & 0.327^{*} \\
  &  &  & (0.136) & (0.189) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.108 & -0.092 \\
  &  &  & (0.187) & (0.211) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.636^{**} & 0.604^{**} \\
  &  &  & (0.252) & (0.300) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-134.945} & \multicolumn{1}{c}{-132.823} & \multicolumn{1}{c}{-86.350} & \multicolumn{1}{c}{-85.580} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:26
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Progressive Model [total_raw]}
  \label{tab:seat_all_total_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.324^{***} & 0.301^{***} & 0.220^{**} & 0.166^{*} \\
  & (0.111) & (0.092) & (0.098) & (0.098) \\
  & & & & \\
 Small House Proximity (20km) & -0.050 & -0.038 & 1.240^{***} & 1.254^{***} \\
  & (0.496) & (0.504) & (0.444) & (0.449) \\
  & & & & \\
 Large House Proximity (20km) & -0.271 & -0.273 & 0.214 & 0.260 \\
  & (0.297) & (0.302) & (0.297) & (0.316) \\
  & & & & \\
 ln(Tithe) &  & 0.055 & 0.083 & 0.084 \\
  &  & (0.113) & (0.124) & (0.123) \\
  & & & & \\
 ln(Alms) &  & 0.0003 & 0.009 & -0.024 \\
  &  & (0.059) & (0.056) & (0.057) \\
  & & & & \\
 Friary Presence &  & -0.717 & -0.339 & -0.120 \\
  &  & (0.757) & (0.749) & (0.769) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.067 & 0.050 \\
  &  &  & (0.136) & (0.121) \\
  & & & & \\
 ln(Population) &  &  & 0.072 & 0.022 \\
  &  &  & (0.082) & (0.097) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.013 & -0.032 \\
  &  &  & (0.172) & (0.188) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.744^{***} & 0.723^{***} \\
  &  &  & (0.197) & (0.191) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-428.322} & \multicolumn{1}{c}{-427.687} & \multicolumn{1}{c}{-316.943} & \multicolumn{1}{c}{-310.508} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:27
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model [total_raw]}
  \label{tab:full_monastic_total_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.200^{*} & 0.455 & 0.159^{*} \\
  & (0.119) & (0.316) & (0.094) \\
  & & & \\
 ln(Tithe) & -0.315^{**} & -0.269 & 0.072 \\
  & (0.127) & (0.235) & (0.113) \\
  & & & \\
 ln(Alms) & 0.260^{***} & 0.331^{***} & -0.027 \\
  & (0.076) & (0.077) & (0.066) \\
  & & & \\
 Small House Proximity (20km) & -0.711 & -1.618^{***} & 0.588 \\
  & (0.607) & (0.436) & (0.428) \\
  & & & \\
 Large House Proximity (20km) & 0.477 & 0.400 & 0.574^{*} \\
  & (0.327) & (0.529) & (0.295) \\
  & & & \\
 Friary Presence & 0.624 & 0.662 & -0.693 \\
  & (0.423) & (0.527) & (0.926) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.666 & -0.600 & 0.079 \\
  & (0.480) & (0.664) & (0.392) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.302 & 0.003 & 0.590^{***} \\
  & (0.404) & (0.357) & (0.201) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.223^{*} & 0.225 & 0.378^{***} \\
  & (0.121) & (0.224) & (0.068) \\
  & & & \\
 Wet 1535 Weather Shock & -0.091 & -0.181 & -0.040 \\
  & (0.255) & (0.205) & (0.133) \\
  & & & \\
 Wet 1536 Weather Shock & 0.166 & 0.507^{*} & 0.496^{***} \\
  & (0.178) & (0.287) & (0.122) \\
  & & & \\
 ln(Population) & 0.344^{**} & 0.370^{**} & 0.040 \\
  & (0.149) & (0.174) & (0.068) \\
  & & & \\
 Distance to Scotland & -0.609^{**} & -0.795^{**} & -0.946^{***} \\
  & (0.245) & (0.404) & (0.307) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.251} & \multicolumn{1}{c}{-82.392} & \multicolumn{1}{c}{-283.716} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:31
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Monastic Variables [total_sk]}
  \label{tab:muster_monastic_total_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{6}{c}{\textit{Dependent variable:}} \\
\cline{2-7}
\\[-1.8ex] & \multicolumn{6}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.135 &  &  &  &  &  \\
  & (0.184) &  &  &  &  &  \\
  & & & & & & \\
 ln(Tithe / km²) &  & -0.170 &  &  &  &  \\
  &  & (0.161) &  &  &  &  \\
  & & & & & & \\
 ln(Alms / km²) &  &  & 0.211^{*} &  &  &  \\
  &  &  & (0.112) &  &  &  \\
  & & & & & & \\
 Small House Proximity (20km) &  &  &  & -0.425 &  &  \\
  &  &  &  & (0.543) &  &  \\
  & & & & & & \\
 Large House Proximity (20km) &  &  &  &  & 0.608^{*} &  \\
  &  &  &  &  & (0.317) &  \\
  & & & & & & \\
 Friary Presence &  &  &  &  &  & 0.643 \\
  &  &  &  &  &  & (0.429) \\
  & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.573 & -0.593 & -0.627 & -0.551 & -0.626 & -0.607 \\
  & (0.503) & (0.504) & (0.504) & (0.515) & (0.506) & (0.511) \\
  & & & & & & \\
 Court Officer Proximity (20 km) & 0.336 & 0.389 & 0.353 & 0.368 & 0.290 & 0.368 \\
  & (0.400) & (0.427) & (0.426) & (0.444) & (0.420) & (0.441) \\
  & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.190 & 0.217^{*} & 0.207^{*} & 0.220^{*} & 0.187 & 0.201 \\
  & (0.130) & (0.130) & (0.124) & (0.134) & (0.124) & (0.129) \\
  & & & & & & \\
 Wet 1535 Weather Shock & -0.001 & 0.033 & 0.010 & 0.046 & -0.065 & 0.037 \\
  & (0.226) & (0.218) & (0.227) & (0.231) & (0.239) & (0.210) \\
  & & & & & & \\
 Wet 1536 Weather Shock & 0.092 & 0.068 & 0.075 & 0.054 & 0.149 & 0.063 \\
  & (0.149) & (0.141) & (0.154) & (0.154) & (0.176) & (0.143) \\
  & & & & & & \\
 ln(Population) & 0.377^{**} & 0.391^{**} & 0.380^{**} & 0.377^{**} & 0.396^{**} & 0.368^{**} \\
  & (0.165) & (0.164) & (0.170) & (0.165) & (0.165) & (0.160) \\
  & & & & & & \\
 Distance to Scotland & -0.524^{**} & -0.504^{**} & -0.518^{**} & -0.526^{**} & -0.568^{**} & -0.496^{**} \\
  & (0.245) & (0.249) & (0.248) & (0.242) & (0.242) & (0.252) \\
  & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-164.806} & \multicolumn{1}{c}{-164.573} & \multicolumn{1}{c}{-163.712} & \multicolumn{1}{c}{-164.785} & \multicolumn{1}{c}{-164.003} & \multicolumn{1}{c}{-164.686} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{6}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:32
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Monastic Variables [total_sk]}
  \label{tab:primary_monastic_total_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{6}{c}{\textit{Dependent variable:}} \\
\cline{2-7}
\\[-1.8ex] & \multicolumn{6}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.423 &  &  &  &  &  \\
  & (0.346) &  &  &  &  &  \\
  & & & & & & \\
 ln(Tithe / km²) &  & -0.022 &  &  &  &  \\
  &  & (0.238) &  &  &  &  \\
  & & & & & & \\
 ln(Alms / km²) &  &  & 0.293^{***} &  &  &  \\
  &  &  & (0.102) &  &  &  \\
  & & & & & & \\
 Small House Proximity (20km) &  &  &  & -1.113^{**} &  &  \\
  &  &  &  & (0.515) &  &  \\
  & & & & & & \\
 Large House Proximity (20km) &  &  &  &  & 0.617 &  \\
  &  &  &  &  & (0.544) &  \\
  & & & & & & \\
 Friary Presence &  &  &  &  &  & 0.626 \\
  &  &  &  &  &  & (0.528) \\
  & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.542 & -0.575 & -0.671 & -0.447 & -0.624 & -0.599 \\
  & (0.682) & (0.681) & (0.684) & (0.634) & (0.662) & (0.707) \\
  & & & & & & \\
 Court Officer Proximity (20 km) & 0.019 & 0.142 & 0.115 & 0.184 & 0.049 & 0.148 \\
  & (0.300) & (0.329) & (0.342) & (0.353) & (0.351) & (0.354) \\
  & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.140 & 0.188 & 0.179 & 0.252 & 0.161 & 0.180 \\
  & (0.234) & (0.228) & (0.211) & (0.203) & (0.202) & (0.220) \\
  & & & & & & \\
 Wet 1535 Weather Shock & -0.121 & -0.017 & -0.038 & 0.042 & -0.097 & -0.012 \\
  & (0.183) & (0.164) & (0.166) & (0.181) & (0.173) & (0.155) \\
  & & & & & & \\
 Wet 1536 Weather Shock & 0.478^{**} & 0.386^{*} & 0.386^{*} & 0.324 & 0.461^{*} & 0.383^{*} \\
  & (0.220) & (0.212) & (0.232) & (0.217) & (0.258) & (0.215) \\
  & & & & & & \\
 ln(Population) & 0.442^{**} & 0.458^{**} & 0.455^{**} & 0.430^{**} & 0.471^{**} & 0.439^{**} \\
  & (0.188) & (0.189) & (0.203) & (0.180) & (0.185) & (0.184) \\
  & & & & & & \\
 Distance to Scotland & -0.636^{*} & -0.566 & -0.609^{*} & -0.642^{*} & -0.641 & -0.555 \\
  & (0.376) & (0.373) & (0.370) & (0.365) & (0.410) & (0.376) \\
  & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-87.118} & \multicolumn{1}{c}{-88.152} & \multicolumn{1}{c}{-86.537} & \multicolumn{1}{c}{-87.012} & \multicolumn{1}{c}{-87.607} & \multicolumn{1}{c}{-87.977} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{6}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:33
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Monastic Variables [total_sk]}
  \label{tab:seat_monastic_total_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{6}{c}{\textit{Dependent variable:}} \\
\cline{2-7}
\\[-1.8ex] & \multicolumn{6}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.113 &  &  &  &  &  \\
  & (0.104) &  &  &  &  &  \\
  & & & & & & \\
 ln(Tithe / km²) &  & 0.096 &  &  &  &  \\
  &  & (0.123) &  &  &  &  \\
  & & & & & & \\
 ln(Alms / km²) &  &  & 0.025 &  &  &  \\
  &  &  & (0.064) &  &  &  \\
  & & & & & & \\
 Small House Proximity (20km) &  &  &  & 0.705^{*} &  &  \\
  &  &  &  & (0.421) &  &  \\
  & & & & & & \\
 Large House Proximity (20km) &  &  &  &  & 0.672^{**} &  \\
  &  &  &  &  & (0.301) &  \\
  & & & & & & \\
 Friary Presence &  &  &  &  &  & -0.568 \\
  &  &  &  &  &  & (0.890) \\
  & & & & & & \\
 Snubbed Family Proximity (20 km) & 0.091 & 0.084 & 0.067 & 0.051 & 0.006 & 0.082 \\
  & (0.373) & (0.382) & (0.392) & (0.390) & (0.389) & (0.384) \\
  & & & & & & \\
 Court Officer Proximity (20 km) & 0.707^{***} & 0.724^{***} & 0.742^{***} & 0.730^{***} & 0.693^{***} & 0.745^{***} \\
  & (0.235) & (0.245) & (0.258) & (0.253) & (0.244) & (0.259) \\
  & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.380^{***} & 0.379^{***} & 0.385^{***} & 0.378^{***} & 0.391^{***} & 0.389^{***} \\
  & (0.072) & (0.079) & (0.073) & (0.072) & (0.065) & (0.071) \\
  & & & & & & \\
 Wet 1535 Weather Shock & 0.101 & 0.128 & 0.131 & 0.127 & 0.005 & 0.134 \\
  & (0.145) & (0.137) & (0.138) & (0.140) & (0.132) & (0.140) \\
  & & & & & & \\
 Wet 1536 Weather Shock & 0.366^{***} & 0.347^{**} & 0.346^{**} & 0.354^{**} & 0.464^{***} & 0.345^{**} \\
  & (0.139) & (0.138) & (0.140) & (0.142) & (0.123) & (0.141) \\
  & & & & & & \\
 ln(Population) & 0.027 & 0.032 & 0.032 & 0.037 & 0.031 & 0.046 \\
  & (0.078) & (0.080) & (0.078) & (0.080) & (0.075) & (0.078) \\
  & & & & & & \\
 Distance to Scotland & -0.864^{***} & -0.855^{***} & -0.850^{***} & -0.833^{***} & -0.935^{***} & -0.856^{***} \\
  & (0.292) & (0.289) & (0.293) & (0.296) & (0.305) & (0.291) \\
  & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-288.221} & \multicolumn{1}{c}{-288.177} & \multicolumn{1}{c}{-288.588} & \multicolumn{1}{c}{-288.060} & \multicolumn{1}{c}{-285.824} & \multicolumn{1}{c}{-288.406} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{6}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:35
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Progressive Model [total_sk]}
  \label{tab:muster_all_total_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.170 & 0.121 & 0.022 & 0.069 \\
  & (0.157) & (0.146) & (0.107) & (0.118) \\
  & & & & \\
 Small House Proximity (20km) & -1.025^{***} & -1.067^{***} & -0.575 & -0.420 \\
  & (0.340) & (0.352) & (0.702) & (0.641) \\
  & & & & \\
 Large House Proximity (20km) & -0.269 & -0.275 & 0.178 & 0.339 \\
  & (0.384) & (0.378) & (0.402) & (0.375) \\
  & & & & \\
 ln(Tithe / km²) &  & -0.113 & -0.257^{**} & -0.279^{*} \\
  &  & (0.107) & (0.126) & (0.144) \\
  & & & & \\
 ln(Alms / km²) &  & 0.204^{**} & 0.250^{***} & 0.221^{**} \\
  &  & (0.081) & (0.094) & (0.100) \\
  & & & & \\
 Friary Presence &  & 0.941^{***} & 0.526 & 0.714^{*} \\
  &  & (0.353) & (0.431) & (0.424) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.024 & 0.060 \\
  &  &  & (0.157) & (0.161) \\
  & & & & \\
 ln(Population) &  &  & 0.451^{***} & 0.347^{**} \\
  &  &  & (0.113) & (0.160) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.031 & -0.022 \\
  &  &  & (0.228) & (0.265) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.356^{**} & 0.236 \\
  &  &  & (0.145) & (0.185) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-247.774} & \multicolumn{1}{c}{-243.993} & \multicolumn{1}{c}{-168.433} & \multicolumn{1}{c}{-165.202} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:36
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Progressive Model [total_sk]}
  \label{tab:primary_all_total_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.375^{*} & 0.303 & 0.228 & 0.292 \\
  & (0.219) & (0.255) & (0.323) & (0.337) \\
  & & & & \\
 Small House Proximity (20km) & -1.339^{***} & -1.353^{***} & -1.131^{*} & -1.150^{*} \\
  & (0.445) & (0.458) & (0.681) & (0.589) \\
  & & & & \\
 Large House Proximity (20km) & -0.506 & -0.525 & 0.189 & 0.177 \\
  & (0.586) & (0.573) & (0.593) & (0.545) \\
  & & & & \\
 ln(Tithe / km²) &  & -0.027 & -0.175 & -0.227 \\
  &  & (0.145) & (0.213) & (0.251) \\
  & & & & \\
 ln(Alms / km²) &  & 0.185^{*} & 0.283^{***} & 0.253^{**} \\
  &  & (0.108) & (0.107) & (0.105) \\
  & & & & \\
 Friary Presence &  & 0.376 & 0.469 & 0.739 \\
  &  & (0.660) & (0.817) & (0.533) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & -0.016 & 0.001 \\
  &  &  & (0.238) & (0.231) \\
  & & & & \\
 ln(Population) &  &  & 0.491^{***} & 0.362^{**} \\
  &  &  & (0.142) & (0.184) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.039 & -0.039 \\
  &  &  & (0.202) & (0.218) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.596^{**} & 0.549^{*} \\
  &  &  & (0.247) & (0.295) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-138.931} & \multicolumn{1}{c}{-137.824} & \multicolumn{1}{c}{-88.409} & \multicolumn{1}{c}{-86.707} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:36
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Progressive Model [total_sk]}
  \label{tab:seat_all_total_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.053 & 0.016 & 0.024 & -0.002 \\
  & (0.106) & (0.099) & (0.087) & (0.085) \\
  & & & & \\
 Small House Proximity (20km) & -0.039 & -0.026 & 1.277^{***} & 1.275^{***} \\
  & (0.479) & (0.486) & (0.449) & (0.449) \\
  & & & & \\
 Large House Proximity (20km) & -0.182 & -0.179 & 0.313 & 0.348 \\
  & (0.290) & (0.294) & (0.304) & (0.324) \\
  & & & & \\
 ln(Tithe / km²) &  & 0.096 & 0.091 & 0.084 \\
  &  & (0.104) & (0.128) & (0.126) \\
  & & & & \\
 ln(Alms / km²) &  & 0.003 & 0.009 & -0.019 \\
  &  & (0.061) & (0.059) & (0.061) \\
  & & & & \\
 Friary Presence &  & -0.690 & -0.359 & -0.112 \\
  &  & (0.779) & (0.786) & (0.794) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.084 & 0.067 \\
  &  &  & (0.129) & (0.116) \\
  & & & & \\
 ln(Population) &  &  & 0.110 & 0.041 \\
  &  &  & (0.079) & (0.101) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & 0.026 & 0.007 \\
  &  &  & (0.178) & (0.196) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.711^{***} & 0.686^{***} \\
  &  &  & (0.191) & (0.192) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-433.676} & \multicolumn{1}{c}{-432.777} & \multicolumn{1}{c}{-319.283} & \multicolumn{1}{c}{-311.905} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:37
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model [total_sk]}
  \label{tab:full_monastic_total_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.099 & 0.341 & 0.029 \\
  & (0.126) & (0.365) & (0.078) \\
  & & & \\
 ln(Tithe / km²) & -0.300^{**} & -0.254 & 0.076 \\
  & (0.129) & (0.246) & (0.119) \\
  & & & \\
 ln(Alms / km²) & 0.233^{**} & 0.276^{***} & -0.037 \\
  & (0.105) & (0.107) & (0.069) \\
  & & & \\
 Small House Proximity (20km) & -0.653 & -1.531^{***} & 0.592 \\
  & (0.613) & (0.436) & (0.421) \\
  & & & \\
 Large House Proximity (20km) & 0.562^{*} & 0.520 & 0.639^{**} \\
  & (0.337) & (0.572) & (0.305) \\
  & & & \\
 Friary Presence & 0.632 & 0.629 & -0.704 \\
  & (0.418) & (0.577) & (0.957) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.660 & -0.568 & 0.036 \\
  & (0.505) & (0.646) & (0.395) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.326 & 0.063 & 0.656^{***} \\
  & (0.409) & (0.334) & (0.215) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.233^{*} & 0.241 & 0.383^{***} \\
  & (0.123) & (0.210) & (0.067) \\
  & & & \\
 Wet 1535 Weather Shock & -0.057 & -0.113 & 0.00001 \\
  & (0.254) & (0.205) & (0.130) \\
  & & & \\
 Wet 1536 Weather Shock & 0.130 & 0.440 & 0.468^{***} \\
  & (0.177) & (0.276) & (0.121) \\
  & & & \\
 ln(Population) & 0.368^{**} & 0.409^{**} & 0.051 \\
  & (0.151) & (0.168) & (0.071) \\
  & & & \\
 Distance to Scotland & -0.609^{**} & -0.789^{**} & -0.937^{***} \\
  & (0.243) & (0.396) & (0.307) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.857} & \multicolumn{1}{c}{-83.603} & \multicolumn{1}{c}{-284.790} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:42
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Monastic Variables [total_arak]}
  \label{tab:muster_monastic_total_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.219 &  &  &  &  &  &  \\
  & (0.153) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe / Arable km²) &  & -0.131 &  &  &  &  &  \\
  &  & (0.145) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Alms / Arable km²) &  &  & 0.224^{**} &  &  &  &  \\
  &  &  & (0.110) &  &  &  &  \\
  & & & & & & & \\
 ln(Net Income / Arable km²) &  &  &  & 0.344^{***} &  &  &  \\
  &  &  &  & (0.109) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -0.425 &  &  \\
  &  &  &  &  & (0.543) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.608^{*} &  \\
  &  &  &  &  &  & (0.317) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.643 \\
  &  &  &  &  &  &  & (0.429) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.569 & -0.594 & -0.636 & -0.726 & -0.551 & -0.626 & -0.607 \\
  & (0.486) & (0.505) & (0.498) & (0.509) & (0.515) & (0.506) & (0.511) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.329 & 0.383 & 0.356 & 0.439 & 0.368 & 0.290 & 0.368 \\
  & (0.406) & (0.429) & (0.438) & (0.486) & (0.444) & (0.420) & (0.441) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.172 & 0.216^{*} & 0.199 & 0.204^{*} & 0.220^{*} & 0.187 & 0.201 \\
  & (0.135) & (0.130) & (0.122) & (0.124) & (0.134) & (0.124) & (0.129) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & -0.027 & 0.032 & 0.008 & -0.046 & 0.046 & -0.065 & 0.037 \\
  & (0.220) & (0.218) & (0.226) & (0.225) & (0.231) & (0.239) & (0.210) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.121 & 0.066 & 0.084 & 0.112 & 0.054 & 0.149 & 0.063 \\
  & (0.143) & (0.142) & (0.155) & (0.152) & (0.154) & (0.176) & (0.143) \\
  & & & & & & & \\
 ln(Population) & 0.371^{**} & 0.392^{**} & 0.376^{**} & 0.376^{**} & 0.377^{**} & 0.396^{**} & 0.368^{**} \\
  & (0.162) & (0.164) & (0.169) & (0.168) & (0.165) & (0.165) & (0.160) \\
  & & & & & & & \\
 Distance to Scotland & -0.530^{**} & -0.507^{**} & -0.511^{**} & -0.498^{**} & -0.526^{**} & -0.568^{**} & -0.496^{**} \\
  & (0.247) & (0.249) & (0.247) & (0.249) & (0.242) & (0.242) & (0.252) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-164.325} & \multicolumn{1}{c}{-164.745} & \multicolumn{1}{c}{-163.539} & \multicolumn{1}{c}{-161.461} & \multicolumn{1}{c}{-164.785} & \multicolumn{1}{c}{-164.003} & \multicolumn{1}{c}{-164.686} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:43
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Monastic Variables [total_arak]}
  \label{tab:primary_monastic_total_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.474 &  &  &  &  &  &  \\
  & (0.296) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe / Arable km²) &  & 0.013 &  &  &  &  &  \\
  &  & (0.215) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Alms / Arable km²) &  &  & 0.302^{***} &  &  &  &  \\
  &  &  & (0.109) &  &  &  &  \\
  & & & & & & & \\
 ln(Net Income / Arable km²) &  &  &  & 0.378^{***} &  &  &  \\
  &  &  &  & (0.137) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -1.113^{**} &  &  \\
  &  &  &  &  & (0.515) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.617 &  \\
  &  &  &  &  &  & (0.544) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.626 \\
  &  &  &  &  &  &  & (0.528) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.541 & -0.575 & -0.691 & -0.791 & -0.447 & -0.624 & -0.599 \\
  & (0.654) & (0.682) & (0.678) & (0.661) & (0.634) & (0.662) & (0.707) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.024 & 0.137 & 0.125 & 0.237 & 0.184 & 0.049 & 0.148 \\
  & (0.295) & (0.332) & (0.352) & (0.382) & (0.353) & (0.351) & (0.354) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.113 & 0.183 & 0.159 & 0.178 & 0.252 & 0.161 & 0.180 \\
  & (0.237) & (0.230) & (0.219) & (0.210) & (0.203) & (0.202) & (0.220) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & -0.153 & -0.017 & -0.039 & -0.094 & 0.042 & -0.097 & -0.012 \\
  & (0.182) & (0.164) & (0.168) & (0.176) & (0.181) & (0.173) & (0.155) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.535^{**} & 0.387^{*} & 0.399^{*} & 0.427^{*} & 0.324 & 0.461^{*} & 0.383^{*} \\
  & (0.222) & (0.209) & (0.228) & (0.233) & (0.217) & (0.258) & (0.215) \\
  & & & & & & & \\
 ln(Population) & 0.441^{**} & 0.457^{**} & 0.451^{**} & 0.446^{**} & 0.430^{**} & 0.471^{**} & 0.439^{**} \\
  & (0.182) & (0.188) & (0.200) & (0.195) & (0.180) & (0.185) & (0.184) \\
  & & & & & & & \\
 Distance to Scotland & -0.630^{*} & -0.568 & -0.596 & -0.575 & -0.642^{*} & -0.641 & -0.555 \\
  & (0.377) & (0.374) & (0.371) & (0.375) & (0.365) & (0.410) & (0.376) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-86.676} & \multicolumn{1}{c}{-88.154} & \multicolumn{1}{c}{-86.419} & \multicolumn{1}{c}{-85.972} & \multicolumn{1}{c}{-87.012} & \multicolumn{1}{c}{-87.607} & \multicolumn{1}{c}{-87.977} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:44
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Monastic Variables [total_arak]}
  \label{tab:seat_monastic_total_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.187^{*} &  &  &  &  &  &  \\
  & (0.109) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe / Arable km²) &  & 0.103 &  &  &  &  &  \\
  &  & (0.110) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Alms / Arable km²) &  &  & -0.001 &  &  &  &  \\
  &  &  & (0.071) &  &  &  &  \\
  & & & & & & & \\
 ln(Net Income / Arable km²) &  &  &  & 0.073 &  &  &  \\
  &  &  &  & (0.086) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & 0.705^{*} &  &  \\
  &  &  &  &  & (0.421) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.672^{**} &  \\
  &  &  &  &  &  & (0.301) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & -0.568 \\
  &  &  &  &  &  &  & (0.890) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & 0.085 & 0.086 & 0.071 & 0.038 & 0.051 & 0.006 & 0.082 \\
  & (0.374) & (0.381) & (0.391) & (0.402) & (0.390) & (0.389) & (0.384) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.706^{***} & 0.729^{***} & 0.745^{***} & 0.758^{***} & 0.730^{***} & 0.693^{***} & 0.745^{***} \\
  & (0.240) & (0.249) & (0.259) & (0.270) & (0.253) & (0.244) & (0.259) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.372^{***} & 0.378^{***} & 0.387^{***} & 0.386^{***} & 0.378^{***} & 0.391^{***} & 0.389^{***} \\
  & (0.068) & (0.078) & (0.072) & (0.072) & (0.072) & (0.065) & (0.071) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & 0.076 & 0.128 & 0.134 & 0.121 & 0.127 & 0.005 & 0.134 \\
  & (0.143) & (0.136) & (0.139) & (0.137) & (0.140) & (0.132) & (0.140) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.389^{***} & 0.348^{**} & 0.345^{**} & 0.352^{**} & 0.354^{**} & 0.464^{***} & 0.345^{**} \\
  & (0.141) & (0.138) & (0.140) & (0.139) & (0.142) & (0.123) & (0.141) \\
  & & & & & & & \\
 ln(Population) & 0.023 & 0.031 & 0.034 & 0.027 & 0.037 & 0.031 & 0.046 \\
  & (0.076) & (0.079) & (0.077) & (0.081) & (0.080) & (0.075) & (0.078) \\
  & & & & & & & \\
 Distance to Scotland & -0.876^{***} & -0.856^{***} & -0.849^{***} & -0.848^{***} & -0.833^{***} & -0.935^{***} & -0.856^{***} \\
  & (0.293) & (0.289) & (0.293) & (0.292) & (0.296) & (0.305) & (0.291) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-287.453} & \multicolumn{1}{c}{-288.091} & \multicolumn{1}{c}{-288.622} & \multicolumn{1}{c}{-288.353} & \multicolumn{1}{c}{-288.060} & \multicolumn{1}{c}{-285.824} & \multicolumn{1}{c}{-288.406} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:46
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Progressive Model [total_arak]}
  \label{tab:muster_all_total_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.284^{**} & 0.199^{**} & 0.122 & 0.117 \\
  & (0.117) & (0.081) & (0.116) & (0.117) \\
  & & & & \\
 Small House Proximity (20km) & -1.020^{***} & -1.104^{***} & -0.669 & -0.502 \\
  & (0.335) & (0.358) & (0.685) & (0.614) \\
  & & & & \\
 Large House Proximity (20km) & -0.298 & -0.306 & 0.098 & 0.274 \\
  & (0.405) & (0.392) & (0.400) & (0.355) \\
  & & & & \\
 ln(Tithe / Arable km²) &  & -0.156 & -0.279^{**} & -0.282^{**} \\
  &  & (0.134) & (0.114) & (0.128) \\
  & & & & \\
 ln(Alms / Arable km²) &  & 0.131^{*} & 0.113 & 0.081 \\
  &  & (0.069) & (0.092) & (0.102) \\
  & & & & \\
 ln(Net Income / Arable km²) &  & 0.188^{**} & 0.304^{***} & 0.309^{***} \\
  &  & (0.084) & (0.092) & (0.086) \\
  & & & & \\
 Friary Presence &  & 0.865^{**} & 0.474 & 0.668 \\
  &  & (0.347) & (0.448) & (0.424) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.032 & 0.070 \\
  &  &  & (0.163) & (0.167) \\
  & & & & \\
 ln(Population) &  &  & 0.437^{***} & 0.343^{**} \\
  &  &  & (0.109) & (0.156) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.113 & -0.092 \\
  &  &  & (0.224) & (0.256) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.397^{***} & 0.275 \\
  &  &  & (0.142) & (0.175) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-246.251} & \multicolumn{1}{c}{-240.681} & \multicolumn{1}{c}{-165.890} & \multicolumn{1}{c}{-162.838} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:47
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Progressive Model [total_arak]}
  \label{tab:primary_all_total_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.438^{***} & 0.375^{***} & 0.326 & 0.344 \\
  & (0.123) & (0.124) & (0.292) & (0.298) \\
  & & & & \\
 Small House Proximity (20km) & -1.283^{***} & -1.326^{***} & -1.169^{*} & -1.210^{**} \\
  & (0.465) & (0.479) & (0.692) & (0.600) \\
  & & & & \\
 Large House Proximity (20km) & -0.501 & -0.517 & 0.120 & 0.099 \\
  & (0.617) & (0.596) & (0.603) & (0.524) \\
  & & & & \\
 ln(Tithe / Arable km²) &  & -0.101 & -0.199 & -0.225 \\
  &  & (0.203) & (0.194) & (0.221) \\
  & & & & \\
 ln(Alms / Arable km²) &  & 0.119 & 0.187 & 0.141 \\
  &  & (0.090) & (0.127) & (0.122) \\
  & & & & \\
 ln(Net Income / Arable km²) &  & 0.108 & 0.226 & 0.245 \\
  &  & (0.143) & (0.173) & (0.150) \\
  & & & & \\
 Friary Presence &  & 0.354 & 0.409 & 0.675 \\
  &  & (0.644) & (0.839) & (0.531) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & -0.017 & -0.002 \\
  &  &  & (0.253) & (0.248) \\
  & & & & \\
 ln(Population) &  &  & 0.473^{***} & 0.357^{*} \\
  &  &  & (0.140) & (0.184) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.116 & -0.105 \\
  &  &  & (0.205) & (0.227) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.643^{***} & 0.605^{**} \\
  &  &  & (0.249) & (0.298) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-138.016} & \multicolumn{1}{c}{-136.756} & \multicolumn{1}{c}{-87.107} & \multicolumn{1}{c}{-85.627} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:47
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Progressive Model [total_arak]}
  \label{tab:seat_all_total_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.202^{***} & 0.168^{**} & 0.117 & 0.073 \\
  & (0.073) & (0.085) & (0.100) & (0.104) \\
  & & & & \\
 Small House Proximity (20km) & -0.055 & -0.059 & 1.265^{***} & 1.268^{***} \\
  & (0.502) & (0.498) & (0.440) & (0.441) \\
  & & & & \\
 Large House Proximity (20km) & -0.231 & -0.223 & 0.285 & 0.324 \\
  & (0.299) & (0.304) & (0.295) & (0.311) \\
  & & & & \\
 ln(Tithe / Arable km²) &  & 0.084 & 0.080 & 0.070 \\
  &  & (0.096) & (0.126) & (0.126) \\
  & & & & \\
 ln(Alms / Arable km²) &  & -0.095 & -0.075 & -0.118 \\
  &  & (0.060) & (0.089) & (0.089) \\
  & & & & \\
 ln(Net Income / Arable km²) &  & 0.071 & 0.084 & 0.094 \\
  &  & (0.069) & (0.078) & (0.081) \\
  & & & & \\
 Friary Presence &  & -0.723 & -0.398 & -0.151 \\
  &  & (0.766) & (0.793) & (0.799) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.081 & 0.070 \\
  &  &  & (0.131) & (0.116) \\
  & & & & \\
 ln(Population) &  &  & 0.104 & 0.039 \\
  &  &  & (0.078) & (0.099) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.0001 & -0.017 \\
  &  &  & (0.181) & (0.200) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.738^{***} & 0.709^{***} \\
  &  &  & (0.199) & (0.196) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-431.490} & \multicolumn{1}{c}{-430.267} & \multicolumn{1}{c}{-318.295} & \multicolumn{1}{c}{-311.138} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:48
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model [total_arak]}
  \label{tab:full_monastic_total_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.139 & 0.376 & 0.115 \\
  & (0.129) & (0.303) & (0.107) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.309^{***} & -0.253 & 0.065 \\
  & (0.114) & (0.210) & (0.115) \\
  & & & \\
 ln(Alms / Arable km²) & 0.094 & 0.164 & -0.116 \\
  & (0.092) & (0.109) & (0.103) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.309^{***} & 0.247 & 0.076 \\
  & (0.093) & (0.174) & (0.114) \\
  & & & \\
 Small House Proximity (20km) & -0.735 & -1.585^{***} & 0.606 \\
  & (0.581) & (0.423) & (0.410) \\
  & & & \\
 Large House Proximity (20km) & 0.478 & 0.428 & 0.602^{**} \\
  & (0.323) & (0.559) & (0.287) \\
  & & & \\
 Friary Presence & 0.586 & 0.575 & -0.781 \\
  & (0.431) & (0.610) & (0.993) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.762 & -0.693 & 0.028 \\
  & (0.495) & (0.612) & (0.396) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.407 & 0.149 & 0.667^{***} \\
  & (0.460) & (0.342) & (0.238) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.235^{*} & 0.221 & 0.383^{***} \\
  & (0.128) & (0.227) & (0.062) \\
  & & & \\
 Wet 1535 Weather Shock & -0.125 & -0.171 & -0.027 \\
  & (0.246) & (0.207) & (0.133) \\
  & & & \\
 Wet 1536 Weather Shock & 0.174 & 0.494^{*} & 0.487^{***} \\
  & (0.166) & (0.268) & (0.124) \\
  & & & \\
 ln(Population) & 0.362^{**} & 0.400^{**} & 0.051 \\
  & (0.150) & (0.165) & (0.069) \\
  & & & \\
 Distance to Scotland & -0.592^{**} & -0.767^{*} & -0.944^{***} \\
  & (0.243) & (0.395) & (0.308) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-158.536} & \multicolumn{1}{c}{-82.585} & \multicolumn{1}{c}{-283.957} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:53
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Monastic Variables [split_raw]}
  \label{tab:muster_monastic_split_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & 0.117 &  &  &  &  &  &  \\
  & (0.129) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(Large House Land + 1) &  & 0.302^{**} &  &  &  &  &  \\
  &  & (0.147) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe) &  &  & -0.113 &  &  &  &  \\
  &  &  & (0.151) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms) &  &  &  & 0.216^{**} &  &  &  \\
  &  &  &  & (0.091) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -0.425 &  &  \\
  &  &  &  &  & (0.543) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.608^{*} &  \\
  &  &  &  &  &  & (0.317) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.643 \\
  &  &  &  &  &  &  & (0.429) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.554 & -0.550 & -0.589 & -0.669 & -0.551 & -0.626 & -0.607 \\
  & (0.493) & (0.480) & (0.506) & (0.501) & (0.515) & (0.506) & (0.511) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.323 & 0.272 & 0.383 & 0.365 & 0.368 & 0.290 & 0.368 \\
  & (0.425) & (0.368) & (0.424) & (0.440) & (0.444) & (0.420) & (0.441) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.185 & 0.187 & 0.214^{*} & 0.201^{*} & 0.220^{*} & 0.187 & 0.201 \\
  & (0.135) & (0.137) & (0.130) & (0.122) & (0.134) & (0.124) & (0.129) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & -0.011 & -0.042 & 0.032 & 0.001 & 0.046 & -0.065 & 0.037 \\
  & (0.231) & (0.222) & (0.219) & (0.224) & (0.231) & (0.239) & (0.210) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.097 & 0.135 & 0.069 & 0.089 & 0.054 & 0.149 & 0.063 \\
  & (0.150) & (0.153) & (0.142) & (0.158) & (0.154) & (0.176) & (0.143) \\
  & & & & & & & \\
 ln(Population) & 0.373^{**} & 0.360^{**} & 0.390^{**} & 0.369^{**} & 0.377^{**} & 0.396^{**} & 0.368^{**} \\
  & (0.160) & (0.163) & (0.164) & (0.170) & (0.165) & (0.165) & (0.160) \\
  & & & & & & & \\
 Distance to Scotland & -0.489^{**} & -0.544^{**} & -0.505^{**} & -0.513^{**} & -0.526^{**} & -0.568^{**} & -0.496^{**} \\
  & (0.249) & (0.246) & (0.248) & (0.249) & (0.242) & (0.242) & (0.252) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-164.729} & \multicolumn{1}{c}{-163.598} & \multicolumn{1}{c}{-164.799} & \multicolumn{1}{c}{-163.427} & \multicolumn{1}{c}{-164.785} & \multicolumn{1}{c}{-164.003} & \multicolumn{1}{c}{-164.686} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:54
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Monastic Variables [split_raw]}
  \label{tab:primary_monastic_split_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & -0.103 &  &  &  &  &  &  \\
  & (0.138) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(Large House Land + 1) &  & 0.595^{**} &  &  &  &  &  \\
  &  & (0.284) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe) &  &  & 0.054 &  &  &  &  \\
  &  &  & (0.203) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms) &  &  &  & 0.317^{***} &  &  &  \\
  &  &  &  & (0.086) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -1.113^{**} &  &  \\
  &  &  &  &  & (0.515) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.617 &  \\
  &  &  &  &  &  & (0.544) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.626 \\
  &  &  &  &  &  &  & (0.528) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.608 & -0.491 & -0.575 & -0.775 & -0.447 & -0.624 & -0.599 \\
  & (0.688) & (0.658) & (0.685) & (0.701) & (0.634) & (0.662) & (0.707) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.181 & -0.121 & 0.128 & 0.140 & 0.184 & 0.049 & 0.148 \\
  & (0.331) & (0.284) & (0.328) & (0.360) & (0.353) & (0.351) & (0.354) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.202 & 0.155 & 0.177 & 0.167 & 0.252 & 0.161 & 0.180 \\
  & (0.217) & (0.229) & (0.230) & (0.222) & (0.203) & (0.202) & (0.220) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & 0.017 & -0.177 & -0.017 & -0.055 & 0.042 & -0.097 & -0.012 \\
  & (0.175) & (0.165) & (0.164) & (0.168) & (0.181) & (0.173) & (0.155) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.362^{*} & 0.564^{**} & 0.386^{*} & 0.409^{*} & 0.324 & 0.461^{*} & 0.383^{*} \\
  & (0.213) & (0.235) & (0.214) & (0.239) & (0.217) & (0.258) & (0.215) \\
  & & & & & & & \\
 ln(Population) & 0.467^{**} & 0.420^{**} & 0.456^{**} & 0.438^{**} & 0.430^{**} & 0.471^{**} & 0.439^{**} \\
  & (0.194) & (0.193) & (0.189) & (0.205) & (0.180) & (0.185) & (0.184) \\
  & & & & & & & \\
 Distance to Scotland & -0.584 & -0.660^{*} & -0.571 & -0.612 & -0.642^{*} & -0.641 & -0.555 \\
  & (0.379) & (0.383) & (0.373) & (0.375) & (0.365) & (0.410) & (0.376) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-88.054} & \multicolumn{1}{c}{-85.735} & \multicolumn{1}{c}{-88.123} & \multicolumn{1}{c}{-85.892} & \multicolumn{1}{c}{-87.012} & \multicolumn{1}{c}{-87.607} & \multicolumn{1}{c}{-87.977} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:55
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Monastic Variables [split_raw]}
  \label{tab:seat_monastic_split_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & 0.211^{***} &  &  &  &  &  &  \\
  & (0.061) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(Large House Land + 1) &  & 0.264^{***} &  &  &  &  &  \\
  &  & (0.101) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe) &  &  & 0.132 &  &  &  &  \\
  &  &  & (0.113) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms) &  &  &  & 0.055 &  &  &  \\
  &  &  &  & (0.066) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & 0.705^{*} &  &  \\
  &  &  &  &  & (0.421) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.672^{**} &  \\
  &  &  &  &  &  & (0.301) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & -0.568 \\
  &  &  &  &  &  &  & (0.890) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & 0.158 & 0.114 & 0.090 & 0.057 & 0.051 & 0.006 & 0.082 \\
  & (0.374) & (0.364) & (0.383) & (0.397) & (0.390) & (0.389) & (0.384) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.625^{**} & 0.642^{***} & 0.710^{***} & 0.741^{***} & 0.730^{***} & 0.693^{***} & 0.745^{***} \\
  & (0.251) & (0.219) & (0.244) & (0.258) & (0.253) & (0.244) & (0.259) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.355^{***} & 0.390^{***} & 0.375^{***} & 0.383^{***} & 0.378^{***} & 0.391^{***} & 0.389^{***} \\
  & (0.082) & (0.066) & (0.081) & (0.075) & (0.072) & (0.065) & (0.071) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & 0.040 & 0.049 & 0.122 & 0.127 & 0.127 & 0.005 & 0.134 \\
  & (0.139) & (0.135) & (0.134) & (0.136) & (0.140) & (0.132) & (0.140) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.392^{***} & 0.419^{***} & 0.350^{**} & 0.350^{**} & 0.354^{**} & 0.464^{***} & 0.345^{**} \\
  & (0.136) & (0.135) & (0.136) & (0.138) & (0.142) & (0.123) & (0.141) \\
  & & & & & & & \\
 ln(Population) & 0.013 & 0.009 & 0.029 & 0.025 & 0.037 & 0.031 & 0.046 \\
  & (0.081) & (0.074) & (0.081) & (0.080) & (0.080) & (0.075) & (0.078) \\
  & & & & & & & \\
 Distance to Scotland & -0.812^{***} & -0.894^{***} & -0.856^{***} & -0.852^{***} & -0.833^{***} & -0.935^{***} & -0.856^{***} \\
  & (0.294) & (0.290) & (0.290) & (0.293) & (0.296) & (0.305) & (0.291) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-285.900} & \multicolumn{1}{c}{-285.932} & \multicolumn{1}{c}{-287.656} & \multicolumn{1}{c}{-288.409} & \multicolumn{1}{c}{-288.060} & \multicolumn{1}{c}{-285.824} & \multicolumn{1}{c}{-288.406} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:58
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Progressive Model [split_raw]}
  \label{tab:muster_all_split_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & 0.245^{**} & 0.205^{**} & 0.165 & 0.150 \\
  & (0.100) & (0.102) & (0.144) & (0.137) \\
  & & & & \\
 ln(Large House Land + 1) & 0.454^{***} & 0.476^{***} & 0.329^{***} & 0.291^{**} \\
  & (0.166) & (0.137) & (0.124) & (0.117) \\
  & & & & \\
 Small House Proximity (20km) & -1.089^{***} & -1.132^{***} & -0.685 & -0.515 \\
  & (0.346) & (0.366) & (0.688) & (0.632) \\
  & & & & \\
 Large House Proximity (20km) & -0.380 & -0.421 & 0.011 & 0.171 \\
  & (0.384) & (0.381) & (0.365) & (0.346) \\
  & & & & \\
 ln(Tithe) &  & -0.275^{***} & -0.345^{***} & -0.345^{**} \\
  &  & (0.099) & (0.115) & (0.135) \\
  & & & & \\
 ln(Alms) &  & 0.262^{***} & 0.265^{***} & 0.235^{***} \\
  &  & (0.076) & (0.071) & (0.076) \\
  & & & & \\
 Friary Presence &  & 0.876^{***} & 0.409 & 0.580 \\
  &  & (0.312) & (0.436) & (0.438) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & -0.002 & 0.040 \\
  &  &  & (0.167) & (0.166) \\
  & & & & \\
 ln(Population) &  &  & 0.374^{***} & 0.304^{**} \\
  &  &  & (0.101) & (0.150) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.143 & -0.105 \\
  &  &  & (0.245) & (0.269) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.437^{***} & 0.319^{*} \\
  &  &  & (0.156) & (0.187) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-240.102} & \multicolumn{1}{c}{-234.595} & \multicolumn{1}{c}{-165.582} & \multicolumn{1}{c}{-163.355} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:58
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Progressive Model [split_raw]}
  \label{tab:primary_all_split_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & 0.178^{*} & 0.138 & -0.046 & -0.059 \\
  & (0.096) & (0.126) & (0.150) & (0.142) \\
  & & & & \\
 ln(Large House Land + 1) & 0.741^{***} & 0.718^{***} & 0.557^{*} & 0.513^{*} \\
  & (0.230) & (0.234) & (0.317) & (0.289) \\
  & & & & \\
 Small House Proximity (20km) & -1.285^{***} & -1.303^{**} & -1.175^{*} & -1.156^{*} \\
  & (0.479) & (0.509) & (0.678) & (0.612) \\
  & & & & \\
 Large House Proximity (20km) & -0.602 & -0.675 & -0.043 & -0.007 \\
  & (0.585) & (0.577) & (0.541) & (0.496) \\
  & & & & \\
 ln(Tithe) &  & -0.194 & -0.258 & -0.275 \\
  &  & (0.164) & (0.216) & (0.248) \\
  & & & & \\
 ln(Alms) &  & 0.252^{**} & 0.332^{***} & 0.306^{***} \\
  &  & (0.109) & (0.061) & (0.075) \\
  & & & & \\
 Friary Presence &  & 0.345 & 0.556 & 0.725 \\
  &  & (0.648) & (0.686) & (0.474) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & -0.028 & -0.010 \\
  &  &  & (0.252) & (0.233) \\
  & & & & \\
 ln(Population) &  &  & 0.393^{***} & 0.324^{*} \\
  &  &  & (0.135) & (0.187) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.100 & -0.085 \\
  &  &  & (0.184) & (0.209) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.654^{***} & 0.617^{**} \\
  &  &  & (0.253) & (0.300) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-133.224} & \multicolumn{1}{c}{-131.119} & \multicolumn{1}{c}{-85.618} & \multicolumn{1}{c}{-84.929} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:08:59
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Progressive Model [split_raw]}
  \label{tab:seat_all_split_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & 0.306^{***} & 0.315^{***} & 0.293^{***} & 0.275^{***} \\
  & (0.079) & (0.073) & (0.072) & (0.075) \\
  & & & & \\
 ln(Large House Land + 1) & 0.255^{***} & 0.255^{***} & 0.225^{***} & 0.180^{**} \\
  & (0.080) & (0.076) & (0.087) & (0.090) \\
  & & & & \\
 Small House Proximity (20km) & -0.169 & -0.162 & 1.121^{**} & 1.128^{**} \\
  & (0.480) & (0.484) & (0.447) & (0.449) \\
  & & & & \\
 Large House Proximity (20km) & -0.292 & -0.300 & 0.195 & 0.241 \\
  & (0.302) & (0.305) & (0.293) & (0.311) \\
  & & & & \\
 ln(Tithe) &  & 0.020 & 0.037 & 0.034 \\
  &  & (0.104) & (0.118) & (0.115) \\
  & & & & \\
 ln(Alms) &  & -0.029 & 0.001 & -0.034 \\
  &  & (0.052) & (0.046) & (0.050) \\
  & & & & \\
 Friary Presence &  & -0.886 & -0.481 & -0.246 \\
  &  & (0.789) & (0.789) & (0.767) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.062 & 0.051 \\
  &  &  & (0.127) & (0.117) \\
  & & & & \\
 ln(Population) &  &  & 0.042 & -0.002 \\
  &  &  & (0.077) & (0.092) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.103 & -0.128 \\
  &  &  & (0.160) & (0.178) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.790^{***} & 0.781^{***} \\
  &  &  & (0.202) & (0.198) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-420.713} & \multicolumn{1}{c}{-419.910} & \multicolumn{1}{c}{-311.050} & \multicolumn{1}{c}{-305.410} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:00
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model [split_raw]}
  \label{tab:full_monastic_split_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & 0.091 & -0.162 & 0.184^{***} \\
  & (0.127) & (0.144) & (0.051) \\
  & & & \\
 ln(Large House Land + 1) & 0.326^{***} & 0.581^{*} & 0.204^{**} \\
  & (0.117) & (0.299) & (0.087) \\
  & & & \\
 ln(Tithe) & -0.369^{***} & -0.308 & 0.017 \\
  & (0.122) & (0.248) & (0.105) \\
  & & & \\
 ln(Alms) & 0.251^{***} & 0.344^{***} & -0.034 \\
  & (0.079) & (0.076) & (0.060) \\
  & & & \\
 Small House Proximity (20km) & -0.730 & -1.528^{***} & 0.505 \\
  & (0.584) & (0.410) & (0.428) \\
  & & & \\
 Large House Proximity (20km) & 0.401 & 0.360 & 0.539^{*} \\
  & (0.321) & (0.540) & (0.293) \\
  & & & \\
 Friary Presence & 0.548 & 0.657 & -0.739 \\
  & (0.422) & (0.538) & (0.930) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.643 & -0.698 & 0.147 \\
  & (0.452) & (0.652) & (0.379) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.274 & 0.052 & 0.512^{**} \\
  & (0.385) & (0.341) & (0.203) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.225^{*} & 0.265 & 0.371^{***} \\
  & (0.134) & (0.222) & (0.074) \\
  & & & \\
 Wet 1535 Weather Shock & -0.129 & -0.139 & -0.120 \\
  & (0.258) & (0.198) & (0.133) \\
  & & & \\
 Wet 1536 Weather Shock & 0.202 & 0.492^{*} & 0.545^{***} \\
  & (0.182) & (0.291) & (0.121) \\
  & & & \\
 ln(Population) & 0.326^{**} & 0.377^{**} & 0.018 \\
  & (0.143) & (0.172) & (0.066) \\
  & & & \\
 Distance to Scotland & -0.613^{**} & -0.848^{**} & -0.923^{***} \\
  & (0.248) & (0.406) & (0.310) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-159.129} & \multicolumn{1}{c}{-81.406} & \multicolumn{1}{c}{-281.218} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:04
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Monastic Variables [split_sk]}
  \label{tab:muster_monastic_split_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & 0.033 &  &  &  &  &  &  \\
  & (0.129) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(Large House Land / km²) &  & 0.227 &  &  &  &  &  \\
  &  & (0.182) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe / km²) &  &  & -0.170 &  &  &  &  \\
  &  &  & (0.161) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms / km²) &  &  &  & 0.211^{*} &  &  &  \\
  &  &  &  & (0.112) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -0.425 &  &  \\
  &  &  &  &  & (0.543) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.608^{*} &  \\
  &  &  &  &  &  & (0.317) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.643 \\
  &  &  &  &  &  &  & (0.429) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.579 & -0.580 & -0.593 & -0.627 & -0.551 & -0.626 & -0.607 \\
  & (0.499) & (0.494) & (0.504) & (0.504) & (0.515) & (0.506) & (0.511) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.356 & 0.331 & 0.389 & 0.353 & 0.368 & 0.290 & 0.368 \\
  & (0.434) & (0.393) & (0.427) & (0.426) & (0.444) & (0.420) & (0.441) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.199 & 0.189 & 0.217^{*} & 0.207^{*} & 0.220^{*} & 0.187 & 0.201 \\
  & (0.135) & (0.132) & (0.130) & (0.124) & (0.134) & (0.124) & (0.129) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & 0.021 & -0.012 & 0.033 & 0.010 & 0.046 & -0.065 & 0.037 \\
  & (0.223) & (0.226) & (0.218) & (0.227) & (0.231) & (0.239) & (0.210) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.074 & 0.105 & 0.068 & 0.075 & 0.054 & 0.149 & 0.063 \\
  & (0.146) & (0.152) & (0.141) & (0.154) & (0.154) & (0.176) & (0.143) \\
  & & & & & & & \\
 ln(Population) & 0.382^{**} & 0.372^{**} & 0.391^{**} & 0.380^{**} & 0.377^{**} & 0.396^{**} & 0.368^{**} \\
  & (0.163) & (0.164) & (0.164) & (0.170) & (0.165) & (0.165) & (0.160) \\
  & & & & & & & \\
 Distance to Scotland & -0.503^{**} & -0.541^{**} & -0.504^{**} & -0.518^{**} & -0.526^{**} & -0.568^{**} & -0.496^{**} \\
  & (0.246) & (0.245) & (0.249) & (0.248) & (0.242) & (0.242) & (0.252) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-165.029} & \multicolumn{1}{c}{-164.325} & \multicolumn{1}{c}{-164.573} & \multicolumn{1}{c}{-163.712} & \multicolumn{1}{c}{-164.785} & \multicolumn{1}{c}{-164.003} & \multicolumn{1}{c}{-164.686} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:05
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Monastic Variables [split_sk]}
  \label{tab:primary_monastic_split_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & -0.554^{**} &  &  &  &  &  &  \\
  & (0.252) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(Large House Land / km²) &  & 0.517 &  &  &  &  &  \\
  &  & (0.324) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe / km²) &  &  & -0.022 &  &  &  &  \\
  &  &  & (0.238) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms / km²) &  &  &  & 0.293^{***} &  &  &  \\
  &  &  &  & (0.102) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -1.113^{**} &  &  \\
  &  &  &  &  & (0.515) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.617 &  \\
  &  &  &  &  &  & (0.544) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.626 \\
  &  &  &  &  &  &  & (0.528) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.678 & -0.568 & -0.575 & -0.671 & -0.447 & -0.624 & -0.599 \\
  & (0.677) & (0.666) & (0.681) & (0.684) & (0.634) & (0.662) & (0.707) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.246 & 0.017 & 0.142 & 0.115 & 0.184 & 0.049 & 0.148 \\
  & (0.335) & (0.294) & (0.329) & (0.342) & (0.353) & (0.351) & (0.354) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.248 & 0.150 & 0.188 & 0.179 & 0.252 & 0.161 & 0.180 \\
  & (0.206) & (0.231) & (0.228) & (0.211) & (0.203) & (0.202) & (0.220) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & 0.066 & -0.127 & -0.017 & -0.038 & 0.042 & -0.097 & -0.012 \\
  & (0.170) & (0.177) & (0.164) & (0.166) & (0.181) & (0.173) & (0.155) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.337 & 0.495^{**} & 0.386^{*} & 0.386^{*} & 0.324 & 0.461^{*} & 0.383^{*} \\
  & (0.218) & (0.220) & (0.212) & (0.232) & (0.217) & (0.258) & (0.215) \\
  & & & & & & & \\
 ln(Population) & 0.483^{**} & 0.438^{**} & 0.458^{**} & 0.455^{**} & 0.430^{**} & 0.471^{**} & 0.439^{**} \\
  & (0.202) & (0.188) & (0.189) & (0.203) & (0.180) & (0.185) & (0.184) \\
  & & & & & & & \\
 Distance to Scotland & -0.624^{*} & -0.666^{*} & -0.566 & -0.609^{*} & -0.642^{*} & -0.641 & -0.555 \\
  & (0.373) & (0.378) & (0.373) & (0.370) & (0.365) & (0.410) & (0.376) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-86.985} & \multicolumn{1}{c}{-86.502} & \multicolumn{1}{c}{-88.152} & \multicolumn{1}{c}{-86.537} & \multicolumn{1}{c}{-87.012} & \multicolumn{1}{c}{-87.607} & \multicolumn{1}{c}{-87.977} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:06
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Monastic Variables [split_sk]}
  \label{tab:seat_monastic_split_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & 0.154^{***} &  &  &  &  &  &  \\
  & (0.057) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(Large House Land / km²) &  & 0.148 &  &  &  &  &  \\
  &  & (0.096) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe / km²) &  &  & 0.096 &  &  &  &  \\
  &  &  & (0.123) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms / km²) &  &  &  & 0.025 &  &  &  \\
  &  &  &  & (0.064) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & 0.705^{*} &  &  \\
  &  &  &  &  & (0.421) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.672^{**} &  \\
  &  &  &  &  &  & (0.301) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & -0.568 \\
  &  &  &  &  &  &  & (0.890) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & 0.118 & 0.083 & 0.084 & 0.067 & 0.051 & 0.006 & 0.082 \\
  & (0.382) & (0.376) & (0.382) & (0.392) & (0.390) & (0.389) & (0.384) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.684^{***} & 0.710^{***} & 0.724^{***} & 0.742^{***} & 0.730^{***} & 0.693^{***} & 0.745^{***} \\
  & (0.253) & (0.240) & (0.245) & (0.258) & (0.253) & (0.244) & (0.259) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.364^{***} & 0.386^{***} & 0.379^{***} & 0.385^{***} & 0.378^{***} & 0.391^{***} & 0.389^{***} \\
  & (0.080) & (0.069) & (0.079) & (0.073) & (0.072) & (0.065) & (0.071) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & 0.088 & 0.098 & 0.128 & 0.131 & 0.127 & 0.005 & 0.134 \\
  & (0.142) & (0.140) & (0.137) & (0.138) & (0.140) & (0.132) & (0.140) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.363^{***} & 0.374^{***} & 0.347^{**} & 0.346^{**} & 0.354^{**} & 0.464^{***} & 0.345^{**} \\
  & (0.140) & (0.137) & (0.138) & (0.140) & (0.142) & (0.123) & (0.141) \\
  & & & & & & & \\
 ln(Population) & 0.026 & 0.023 & 0.032 & 0.032 & 0.037 & 0.031 & 0.046 \\
  & (0.080) & (0.078) & (0.080) & (0.078) & (0.080) & (0.075) & (0.078) \\
  & & & & & & & \\
 Distance to Scotland & -0.829^{***} & -0.876^{***} & -0.855^{***} & -0.850^{***} & -0.833^{***} & -0.935^{***} & -0.856^{***} \\
  & (0.294) & (0.293) & (0.289) & (0.293) & (0.296) & (0.305) & (0.291) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-287.360} & \multicolumn{1}{c}{-287.862} & \multicolumn{1}{c}{-288.177} & \multicolumn{1}{c}{-288.588} & \multicolumn{1}{c}{-288.060} & \multicolumn{1}{c}{-285.824} & \multicolumn{1}{c}{-288.406} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:08
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Progressive Model [split_sk]}
  \label{tab:muster_all_split_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & 0.149^{*} & 0.110 & 0.032 & 0.063 \\
  & (0.077) & (0.102) & (0.140) & (0.134) \\
  & & & & \\
 ln(Large House Land / km²) & 0.219 & 0.215 & 0.150 & 0.186 \\
  & (0.153) & (0.137) & (0.111) & (0.120) \\
  & & & & \\
 Small House Proximity (20km) & -1.086^{***} & -1.117^{***} & -0.595 & -0.438 \\
  & (0.338) & (0.342) & (0.687) & (0.622) \\
  & & & & \\
 Large House Proximity (20km) & -0.308 & -0.315 & 0.129 & 0.287 \\
  & (0.382) & (0.374) & (0.396) & (0.366) \\
  & & & & \\
 ln(Tithe / km²) &  & -0.154 & -0.295^{**} & -0.316^{**} \\
  &  & (0.109) & (0.122) & (0.139) \\
  & & & & \\
 ln(Alms / km²) &  & 0.184^{**} & 0.235^{**} & 0.206^{**} \\
  &  & (0.079) & (0.092) & (0.099) \\
  & & & & \\
 Friary Presence &  & 0.894^{**} & 0.454 & 0.633 \\
  &  & (0.357) & (0.453) & (0.452) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.011 & 0.049 \\
  &  &  & (0.166) & (0.168) \\
  & & & & \\
 ln(Population) &  &  & 0.444^{***} & 0.337^{**} \\
  &  &  & (0.109) & (0.154) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.058 & -0.047 \\
  &  &  & (0.235) & (0.267) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.383^{***} & 0.260 \\
  &  &  & (0.148) & (0.185) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-246.313} & \multicolumn{1}{c}{-242.834} & \multicolumn{1}{c}{-168.128} & \multicolumn{1}{c}{-164.771} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:09
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Progressive Model [split_sk]}
  \label{tab:primary_all_split_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & 0.082 & 0.052 & -0.456^{**} & -0.445^{**} \\
  & (0.115) & (0.173) & (0.201) & (0.222) \\
  & & & & \\
 ln(Large House Land / km²) & 0.427^{**} & 0.386^{*} & 0.339 & 0.388 \\
  & (0.206) & (0.233) & (0.301) & (0.312) \\
  & & & & \\
 Small House Proximity (20km) & -1.356^{***} & -1.365^{***} & -1.048 & -1.050^{*} \\
  & (0.432) & (0.436) & (0.666) & (0.550) \\
  & & & & \\
 Large House Proximity (20km) & -0.538 & -0.562 & 0.154 & 0.175 \\
  & (0.588) & (0.580) & (0.610) & (0.545) \\
  & & & & \\
 ln(Tithe / km²) &  & -0.061 & -0.208 & -0.250 \\
  &  & (0.153) & (0.226) & (0.267) \\
  & & & & \\
 ln(Alms / km²) &  & 0.176 & 0.289^{**} & 0.258^{**} \\
  &  & (0.114) & (0.115) & (0.111) \\
  & & & & \\
 Friary Presence &  & 0.377 & 0.707 & 0.931^{*} \\
  &  & (0.703) & (0.768) & (0.521) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.013 & 0.015 \\
  &  &  & (0.243) & (0.228) \\
  & & & & \\
 ln(Population) &  &  & 0.498^{***} & 0.376^{**} \\
  &  &  & (0.135) & (0.186) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & 0.027 & 0.020 \\
  &  &  & (0.204) & (0.219) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.591^{**} & 0.533^{*} \\
  &  &  & (0.244) & (0.296) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-138.100} & \multicolumn{1}{c}{-137.050} & \multicolumn{1}{c}{-86.935} & \multicolumn{1}{c}{-85.417} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:10
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Progressive Model [split_sk]}
  \label{tab:seat_all_split_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & 0.197^{***} & 0.201^{***} & 0.210^{***} & 0.217^{***} \\
  & (0.061) & (0.056) & (0.067) & (0.074) \\
  & & & & \\
 ln(Large House Land / km²) & 0.034 & 0.011 & 0.063 & 0.037 \\
  & (0.089) & (0.087) & (0.079) & (0.079) \\
  & & & & \\
 Small House Proximity (20km) & -0.120 & -0.111 & 1.209^{***} & 1.205^{***} \\
  & (0.469) & (0.474) & (0.451) & (0.446) \\
  & & & & \\
 Large House Proximity (20km) & -0.203 & -0.205 & 0.289 & 0.322 \\
  & (0.293) & (0.295) & (0.308) & (0.322) \\
  & & & & \\
 ln(Tithe / km²) &  & 0.074 & 0.060 & 0.054 \\
  &  & (0.101) & (0.125) & (0.122) \\
  & & & & \\
 ln(Alms / km²) &  & -0.025 & -0.027 & -0.058 \\
  &  & (0.053) & (0.052) & (0.050) \\
  & & & & \\
 Friary Presence &  & -0.793 & -0.534 & -0.264 \\
  &  & (0.778) & (0.855) & (0.832) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.070 & 0.058 \\
  &  &  & (0.126) & (0.116) \\
  & & & & \\
 ln(Population) &  &  & 0.106 & 0.032 \\
  &  &  & (0.075) & (0.098) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.031 & -0.050 \\
  &  &  & (0.171) & (0.188) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.748^{***} & 0.716^{***} \\
  &  &  & (0.194) & (0.194) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-430.501} & \multicolumn{1}{c}{-429.620} & \multicolumn{1}{c}{-316.681} & \multicolumn{1}{c}{-309.293} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:11
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model [split_sk]}
  \label{tab:full_monastic_split_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & 0.010 & -0.574^{**} & 0.152^{***} \\
  & (0.130) & (0.255) & (0.058) \\
  & & & \\
 ln(Large House Land / km²) & 0.233^{*} & 0.459 & 0.095 \\
  & (0.124) & (0.330) & (0.070) \\
  & & & \\
 ln(Tithe / km²) & -0.342^{***} & -0.272 & 0.041 \\
  & (0.125) & (0.270) & (0.115) \\
  & & & \\
 ln(Alms / km²) & 0.223^{**} & 0.289^{**} & -0.067 \\
  & (0.107) & (0.120) & (0.067) \\
  & & & \\
 Small House Proximity (20km) & -0.661 & -1.409^{***} & 0.547 \\
  & (0.584) & (0.392) & (0.421) \\
  & & & \\
 Large House Proximity (20km) & 0.505 & 0.515 & 0.605^{**} \\
  & (0.336) & (0.589) & (0.306) \\
  & & & \\
 Friary Presence & 0.575 & 0.786 & -0.808 \\
  & (0.433) & (0.602) & (0.990) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.662 & -0.733 & 0.089 \\
  & (0.485) & (0.648) & (0.392) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.328 & 0.181 & 0.606^{***} \\
  & (0.403) & (0.356) & (0.215) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.234^{*} & 0.301 & 0.372^{***} \\
  & (0.134) & (0.196) & (0.072) \\
  & & & \\
 Wet 1535 Weather Shock & -0.070 & -0.020 & -0.051 \\
  & (0.255) & (0.204) & (0.132) \\
  & & & \\
 Wet 1536 Weather Shock & 0.144 & 0.398 & 0.493^{***} \\
  & (0.175) & (0.284) & (0.121) \\
  & & & \\
 ln(Population) & 0.361^{**} & 0.432^{**} & 0.044 \\
  & (0.146) & (0.172) & (0.069) \\
  & & & \\
 Distance to Scotland & -0.626^{***} & -0.864^{**} & -0.925^{***} \\
  & (0.242) & (0.391) & (0.310) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.322} & \multicolumn{1}{c}{-81.700} & \multicolumn{1}{c}{-283.517} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:16
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Monastic Variables [split_arak]}
  \label{tab:muster_monastic_split_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{8}{c}{\textit{Dependent variable:}} \\
\cline{2-9}
\\[-1.8ex] & \multicolumn{8}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)} & \multicolumn{1}{c}{(8)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & 0.086 &  &  &  &  &  &  &  \\
  & (0.141) &  &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Large Monastery Land / Arable km²) &  & 0.302^{**} &  &  &  &  &  &  \\
  &  & (0.144) &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Tithe / Arable km²) &  &  & -0.131 &  &  &  &  &  \\
  &  &  & (0.145) &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Alms / Arable km²) &  &  &  & 0.224^{**} &  &  &  &  \\
  &  &  &  & (0.110) &  &  &  &  \\
  & & & & & & & & \\
 ln(Net Income / Arable km²) &  &  &  &  & 0.344^{***} &  &  &  \\
  &  &  &  &  & (0.109) &  &  &  \\
  & & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  &  & -0.425 &  &  \\
  &  &  &  &  &  & (0.543) &  &  \\
  & & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  &  & 0.608^{*} &  \\
  &  &  &  &  &  &  & (0.317) &  \\
  & & & & & & & & \\
 Friary Presence &  &  &  &  &  &  &  & 0.643 \\
  &  &  &  &  &  &  &  & (0.429) \\
  & & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.572 & -0.587 & -0.594 & -0.636 & -0.726 & -0.551 & -0.626 & -0.607 \\
  & (0.499) & (0.473) & (0.505) & (0.498) & (0.509) & (0.515) & (0.506) & (0.511) \\
  & & & & & & & & \\
 Court Officer Proximity (20 km) & 0.351 & 0.328 & 0.383 & 0.356 & 0.439 & 0.368 & 0.290 & 0.368 \\
  & (0.442) & (0.397) & (0.429) & (0.438) & (0.486) & (0.444) & (0.420) & (0.441) \\
  & & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.188 & 0.170 & 0.216^{*} & 0.199 & 0.204^{*} & 0.220^{*} & 0.187 & 0.201 \\
  & (0.140) & (0.138) & (0.130) & (0.122) & (0.124) & (0.134) & (0.124) & (0.129) \\
  & & & & & & & & \\
 Wet 1535 Weather Shock & 0.005 & -0.035 & 0.032 & 0.008 & -0.046 & 0.046 & -0.065 & 0.037 \\
  & (0.222) & (0.220) & (0.218) & (0.226) & (0.225) & (0.231) & (0.239) & (0.210) \\
  & & & & & & & & \\
 Wet 1536 Weather Shock & 0.089 & 0.135 & 0.066 & 0.084 & 0.112 & 0.054 & 0.149 & 0.063 \\
  & (0.145) & (0.147) & (0.142) & (0.155) & (0.152) & (0.154) & (0.176) & (0.143) \\
  & & & & & & & & \\
 ln(Population) & 0.378^{**} & 0.365^{**} & 0.392^{**} & 0.376^{**} & 0.376^{**} & 0.377^{**} & 0.396^{**} & 0.368^{**} \\
  & (0.163) & (0.160) & (0.164) & (0.169) & (0.168) & (0.165) & (0.165) & (0.160) \\
  & & & & & & & & \\
 Distance to Scotland & -0.498^{**} & -0.545^{**} & -0.507^{**} & -0.511^{**} & -0.498^{**} & -0.526^{**} & -0.568^{**} & -0.496^{**} \\
  & (0.244) & (0.246) & (0.249) & (0.247) & (0.249) & (0.242) & (0.242) & (0.252) \\
  & & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-164.886} & \multicolumn{1}{c}{-163.565} & \multicolumn{1}{c}{-164.745} & \multicolumn{1}{c}{-163.539} & \multicolumn{1}{c}{-161.461} & \multicolumn{1}{c}{-164.785} & \multicolumn{1}{c}{-164.003} & \multicolumn{1}{c}{-164.686} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{8}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:17
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Monastic Variables [split_arak]}
  \label{tab:primary_monastic_split_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{8}{c}{\textit{Dependent variable:}} \\
\cline{2-9}
\\[-1.8ex] & \multicolumn{8}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)} & \multicolumn{1}{c}{(8)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & -0.355^{**} &  &  &  &  &  &  &  \\
  & (0.175) &  &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Large Monastery Land / Arable km²) &  & 0.553^{**} &  &  &  &  &  &  \\
  &  & (0.266) &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Tithe / Arable km²) &  &  & 0.013 &  &  &  &  &  \\
  &  &  & (0.215) &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Alms / Arable km²) &  &  &  & 0.302^{***} &  &  &  &  \\
  &  &  &  & (0.109) &  &  &  &  \\
  & & & & & & & & \\
 ln(Net Income / Arable km²) &  &  &  &  & 0.378^{***} &  &  &  \\
  &  &  &  &  & (0.137) &  &  &  \\
  & & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  &  & -1.113^{**} &  &  \\
  &  &  &  &  &  & (0.515) &  &  \\
  & & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  &  & 0.617 &  \\
  &  &  &  &  &  &  & (0.544) &  \\
  & & & & & & & & \\
 Friary Presence &  &  &  &  &  &  &  & 0.626 \\
  &  &  &  &  &  &  &  & (0.528) \\
  & & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.633 & -0.575 & -0.575 & -0.691 & -0.791 & -0.447 & -0.624 & -0.599 \\
  & (0.668) & (0.633) & (0.682) & (0.678) & (0.661) & (0.634) & (0.662) & (0.707) \\
  & & & & & & & & \\
 Court Officer Proximity (20 km) & 0.197 & 0.023 & 0.137 & 0.125 & 0.237 & 0.184 & 0.049 & 0.148 \\
  & (0.332) & (0.288) & (0.332) & (0.352) & (0.382) & (0.353) & (0.351) & (0.354) \\
  & & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.238 & 0.123 & 0.183 & 0.159 & 0.178 & 0.252 & 0.161 & 0.180 \\
  & (0.210) & (0.236) & (0.230) & (0.219) & (0.210) & (0.203) & (0.202) & (0.220) \\
  & & & & & & & & \\
 Wet 1535 Weather Shock & 0.059 & -0.153 & -0.017 & -0.039 & -0.094 & 0.042 & -0.097 & -0.012 \\
  & (0.180) & (0.174) & (0.164) & (0.168) & (0.176) & (0.181) & (0.173) & (0.155) \\
  & & & & & & & & \\
 Wet 1536 Weather Shock & 0.322 & 0.550^{**} & 0.387^{*} & 0.399^{*} & 0.427^{*} & 0.324 & 0.461^{*} & 0.383^{*} \\
  & (0.219) & (0.220) & (0.209) & (0.228) & (0.233) & (0.217) & (0.258) & (0.215) \\
  & & & & & & & & \\
 ln(Population) & 0.476^{**} & 0.437^{**} & 0.457^{**} & 0.451^{**} & 0.446^{**} & 0.430^{**} & 0.471^{**} & 0.439^{**} \\
  & (0.198) & (0.180) & (0.188) & (0.200) & (0.195) & (0.180) & (0.185) & (0.184) \\
  & & & & & & & & \\
 Distance to Scotland & -0.604 & -0.654^{*} & -0.568 & -0.596 & -0.575 & -0.642^{*} & -0.641 & -0.555 \\
  & (0.375) & (0.381) & (0.374) & (0.371) & (0.375) & (0.365) & (0.410) & (0.376) \\
  & & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-87.424} & \multicolumn{1}{c}{-85.956} & \multicolumn{1}{c}{-88.154} & \multicolumn{1}{c}{-86.419} & \multicolumn{1}{c}{-85.972} & \multicolumn{1}{c}{-87.012} & \multicolumn{1}{c}{-87.607} & \multicolumn{1}{c}{-87.977} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{8}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:18
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Monastic Variables [split_arak]}
  \label{tab:seat_monastic_split_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{8}{c}{\textit{Dependent variable:}} \\
\cline{2-9}
\\[-1.8ex] & \multicolumn{8}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)} & \multicolumn{1}{c}{(8)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & 0.134^{**} &  &  &  &  &  &  &  \\
  & (0.060) &  &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Large Monastery Land / Arable km²) &  & 0.245^{**} &  &  &  &  &  &  \\
  &  & (0.101) &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Tithe / Arable km²) &  &  & 0.103 &  &  &  &  &  \\
  &  &  & (0.110) &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Alms / Arable km²) &  &  &  & -0.001 &  &  &  &  \\
  &  &  &  & (0.071) &  &  &  &  \\
  & & & & & & & & \\
 ln(Net Income / Arable km²) &  &  &  &  & 0.073 &  &  &  \\
  &  &  &  &  & (0.086) &  &  &  \\
  & & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  &  & 0.705^{*} &  &  \\
  &  &  &  &  &  & (0.421) &  &  \\
  & & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  &  & 0.672^{**} &  \\
  &  &  &  &  &  &  & (0.301) &  \\
  & & & & & & & & \\
 Friary Presence &  &  &  &  &  &  &  & -0.568 \\
  &  &  &  &  &  &  &  & (0.890) \\
  & & & & & & & & \\
 Snubbed Family Proximity (20 km) & 0.108 & 0.065 & 0.086 & 0.071 & 0.038 & 0.051 & 0.006 & 0.082 \\
  & (0.381) & (0.376) & (0.381) & (0.391) & (0.402) & (0.390) & (0.389) & (0.384) \\
  & & & & & & & & \\
 Court Officer Proximity (20 km) & 0.709^{***} & 0.710^{***} & 0.729^{***} & 0.745^{***} & 0.758^{***} & 0.730^{***} & 0.693^{***} & 0.745^{***} \\
  & (0.256) & (0.239) & (0.249) & (0.259) & (0.270) & (0.253) & (0.244) & (0.259) \\
  & & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.365^{***} & 0.380^{***} & 0.378^{***} & 0.387^{***} & 0.386^{***} & 0.378^{***} & 0.391^{***} & 0.389^{***} \\
  & (0.076) & (0.067) & (0.078) & (0.072) & (0.072) & (0.072) & (0.065) & (0.071) \\
  & & & & & & & & \\
 Wet 1535 Weather Shock & 0.090 & 0.067 & 0.128 & 0.134 & 0.121 & 0.127 & 0.005 & 0.134 \\
  & (0.141) & (0.137) & (0.136) & (0.139) & (0.137) & (0.140) & (0.132) & (0.140) \\
  & & & & & & & & \\
 Wet 1536 Weather Shock & 0.371^{***} & 0.404^{***} & 0.348^{**} & 0.345^{**} & 0.352^{**} & 0.354^{**} & 0.464^{***} & 0.345^{**} \\
  & (0.140) & (0.137) & (0.138) & (0.140) & (0.139) & (0.142) & (0.123) & (0.141) \\
  & & & & & & & & \\
 ln(Population) & 0.027 & 0.018 & 0.031 & 0.034 & 0.027 & 0.037 & 0.031 & 0.046 \\
  & (0.080) & (0.074) & (0.079) & (0.077) & (0.081) & (0.080) & (0.075) & (0.078) \\
  & & & & & & & & \\
 Distance to Scotland & -0.831^{***} & -0.896^{***} & -0.856^{***} & -0.849^{***} & -0.848^{***} & -0.833^{***} & -0.935^{***} & -0.856^{***} \\
  & (0.293) & (0.294) & (0.289) & (0.293) & (0.292) & (0.296) & (0.305) & (0.291) \\
  & & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-287.634} & \multicolumn{1}{c}{-286.453} & \multicolumn{1}{c}{-288.091} & \multicolumn{1}{c}{-288.622} & \multicolumn{1}{c}{-288.353} & \multicolumn{1}{c}{-288.060} & \multicolumn{1}{c}{-285.824} & \multicolumn{1}{c}{-288.406} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{8}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:21
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Progressive Model [split_arak]}
  \label{tab:muster_all_split_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & 0.137 & 0.062 & 0.081 & 0.068 \\
  & (0.094) & (0.111) & (0.147) & (0.133) \\
  & & & & \\
 ln(Large Monastery Land / Arable km²) & 0.318^{***} & 0.290^{***} & 0.249^{**} & 0.236^{**} \\
  & (0.117) & (0.077) & (0.110) & (0.110) \\
  & & & & \\
 Small House Proximity (20km) & -1.045^{***} & -1.106^{***} & -0.666 & -0.505 \\
  & (0.331) & (0.349) & (0.663) & (0.591) \\
  & & & & \\
 Large House Proximity (20km) & -0.315 & -0.336 & 0.054 & 0.223 \\
  & (0.399) & (0.391) & (0.376) & (0.334) \\
  & & & & \\
 ln(Tithe / Arable km²) &  & -0.189 & -0.323^{***} & -0.326^{***} \\
  &  & (0.134) & (0.111) & (0.126) \\
  & & & & \\
 ln(Alms / Arable km²) &  & 0.117^{*} & 0.116 & 0.082 \\
  &  & (0.070) & (0.093) & (0.101) \\
  & & & & \\
 ln(Net Income / Arable km²) &  & 0.181^{**} & 0.279^{***} & 0.290^{***} \\
  &  & (0.077) & (0.094) & (0.088) \\
  & & & & \\
 Friary Presence &  & 0.877^{***} & 0.398 & 0.601 \\
  &  & (0.339) & (0.459) & (0.440) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.014 & 0.054 \\
  &  &  & (0.174) & (0.177) \\
  & & & & \\
 ln(Population) &  &  & 0.425^{***} & 0.333^{**} \\
  &  &  & (0.105) & (0.151) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.148 & -0.122 \\
  &  &  & (0.229) & (0.255) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.434^{***} & 0.313^{*} \\
  &  &  & (0.148) & (0.176) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-244.525} & \multicolumn{1}{c}{-239.342} & \multicolumn{1}{c}{-165.064} & \multicolumn{1}{c}{-162.120} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:21
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Progressive Model [split_arak]}
  \label{tab:primary_all_split_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & -0.025 & -0.089 & -0.283^{*} & -0.300^{**} \\
  & (0.105) & (0.148) & (0.171) & (0.149) \\
  & & & & \\
 ln(Large Monastery Land / Arable km²) & 0.492^{***} & 0.456^{***} & 0.444^{*} & 0.456^{*} \\
  & (0.122) & (0.113) & (0.261) & (0.262) \\
  & & & & \\
 Small House Proximity (20km) & -1.246^{***} & -1.284^{***} & -1.081 & -1.098^{*} \\
  & (0.462) & (0.476) & (0.691) & (0.572) \\
  & & & & \\
 Large House Proximity (20km) & -0.522 & -0.560 & 0.035 & 0.037 \\
  & (0.619) & (0.609) & (0.630) & (0.540) \\
  & & & & \\
 ln(Tithe / Arable km²) &  & -0.134 & -0.255 & -0.266 \\
  &  & (0.196) & (0.207) & (0.231) \\
  & & & & \\
 ln(Alms / Arable km²) &  & 0.120 & 0.202 & 0.149 \\
  &  & (0.096) & (0.133) & (0.131) \\
  & & & & \\
 ln(Net Income / Arable km²) &  & 0.124 & 0.223 & 0.242^{*} \\
  &  & (0.135) & (0.170) & (0.144) \\
  & & & & \\
 Friary Presence &  & 0.443 & 0.499 & 0.743 \\
  &  & (0.650) & (0.813) & (0.526) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & -0.001 & 0.008 \\
  &  &  & (0.263) & (0.247) \\
  & & & & \\
 ln(Population) &  &  & 0.481^{***} & 0.367^{**} \\
  &  &  & (0.138) & (0.186) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.067 & -0.050 \\
  &  &  & (0.199) & (0.226) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.631^{**} & 0.568^{*} \\
  &  &  & (0.246) & (0.302) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-137.201} & \multicolumn{1}{c}{-135.771} & \multicolumn{1}{c}{-85.901} & \multicolumn{1}{c}{-84.487} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:22
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Progressive Model [split_arak]}
  \label{tab:seat_all_split_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & 0.185^{***} & 0.191^{***} & 0.194^{***} & 0.182^{***} \\
  & (0.056) & (0.050) & (0.064) & (0.068) \\
  & & & & \\
 ln(Large Monastery Land / Arable km²) & 0.184^{***} & 0.169^{**} & 0.175^{**} & 0.139 \\
  & (0.066) & (0.077) & (0.088) & (0.098) \\
  & & & & \\
 Small House Proximity (20km) & -0.101 & -0.107 & 1.234^{***} & 1.227^{***} \\
  & (0.496) & (0.491) & (0.437) & (0.439) \\
  & & & & \\
 Large House Proximity (20km) & -0.236 & -0.236 & 0.264 & 0.298 \\
  & (0.301) & (0.305) & (0.297) & (0.310) \\
  & & & & \\
 ln(Tithe / Arable km²) &  & 0.068 & 0.043 & 0.028 \\
  &  & (0.092) & (0.118) & (0.119) \\
  & & & & \\
 ln(Alms / Arable km²) &  & -0.104^{*} & -0.073 & -0.118 \\
  &  & (0.055) & (0.084) & (0.082) \\
  & & & & \\
 ln(Net Income / Arable km²) &  & 0.047 & 0.050 & 0.065 \\
  &  & (0.065) & (0.077) & (0.083) \\
  & & & & \\
 Friary Presence &  & -0.816 & -0.553 & -0.278 \\
  &  & (0.790) & (0.851) & (0.819) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.064 & 0.057 \\
  &  &  & (0.130) & (0.117) \\
  & & & & \\
 ln(Population) &  &  & 0.092 & 0.033 \\
  &  &  & (0.075) & (0.094) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.048 & -0.076 \\
  &  &  & (0.174) & (0.193) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.776^{***} & 0.762^{***} \\
  &  &  & (0.201) & (0.198) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-428.324} & \multicolumn{1}{c}{-427.060} & \multicolumn{1}{c}{-315.634} & \multicolumn{1}{c}{-308.917} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:23
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model [split_arak]}
  \label{tab:full_monastic_split_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & 0.028 & -0.393^{**} & 0.124^{**} \\
  & (0.132) & (0.163) & (0.051) \\
  & & & \\
 ln(Large Monastery Land / Arable km²) & 0.274^{**} & 0.509^{**} & 0.195^{**} \\
  & (0.116) & (0.256) & (0.094) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.359^{***} & -0.307 & 0.022 \\
  & (0.110) & (0.218) & (0.107) \\
  & & & \\
 ln(Alms / Arable km²) & 0.098 & 0.187 & -0.119 \\
  & (0.094) & (0.122) & (0.103) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.292^{***} & 0.243 & 0.057 \\
  & (0.095) & (0.162) & (0.116) \\
  & & & \\
 Small House Proximity (20km) & -0.730 & -1.474^{***} & 0.589 \\
  & (0.544) & (0.373) & (0.412) \\
  & & & \\
 Large House Proximity (20km) & 0.417 & 0.366 & 0.565^{**} \\
  & (0.313) & (0.585) & (0.287) \\
  & & & \\
 Friary Presence & 0.537 & 0.627 & -0.862 \\
  & (0.433) & (0.635) & (1.004) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.768 & -0.849 & 0.057 \\
  & (0.469) & (0.602) & (0.390) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.411 & 0.233 & 0.640^{***} \\
  & (0.457) & (0.353) & (0.232) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.230 & 0.264 & 0.375^{***} \\
  & (0.141) & (0.220) & (0.064) \\
  & & & \\
 Wet 1535 Weather Shock & -0.144 & -0.084 & -0.074 \\
  & (0.245) & (0.204) & (0.134) \\
  & & & \\
 Wet 1536 Weather Shock & 0.197 & 0.432 & 0.523^{***} \\
  & (0.164) & (0.278) & (0.123) \\
  & & & \\
 ln(Population) & 0.352^{**} & 0.416^{**} & 0.043 \\
  & (0.145) & (0.166) & (0.067) \\
  & & & \\
 Distance to Scotland & -0.606^{**} & -0.828^{**} & -0.943^{***} \\
  & (0.240) & (0.387) & (0.308) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-157.742} & \multicolumn{1}{c}{-80.952} & \multicolumn{1}{c}{-282.482} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:28
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Monastic Variables [ownOther_raw]}
  \label{tab:muster_monastic_ownOther_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.235 &  &  &  &  &  &  \\
  & (0.151) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(On-site Monastic Land + 1) &  & -0.161 &  &  &  &  &  \\
  &  & (0.159) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe) &  &  & -0.113 &  &  &  &  \\
  &  &  & (0.151) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms) &  &  &  & 0.216^{**} &  &  &  \\
  &  &  &  & (0.091) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -0.425 &  &  \\
  &  &  &  &  & (0.543) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.608^{*} &  \\
  &  &  &  &  &  & (0.317) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.643 \\
  &  &  &  &  &  &  & (0.429) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.540 & -0.577 & -0.589 & -0.669 & -0.551 & -0.626 & -0.607 \\
  & (0.489) & (0.502) & (0.506) & (0.501) & (0.515) & (0.506) & (0.511) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.276 & 0.355 & 0.383 & 0.365 & 0.368 & 0.290 & 0.368 \\
  & (0.377) & (0.439) & (0.424) & (0.440) & (0.444) & (0.420) & (0.441) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.179 & 0.209 & 0.214^{*} & 0.201^{*} & 0.220^{*} & 0.187 & 0.201 \\
  & (0.133) & (0.136) & (0.130) & (0.122) & (0.134) & (0.124) & (0.129) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & -0.037 & 0.034 & 0.032 & 0.001 & 0.046 & -0.065 & 0.037 \\
  & (0.223) & (0.214) & (0.219) & (0.224) & (0.231) & (0.239) & (0.210) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.125 & 0.062 & 0.069 & 0.089 & 0.054 & 0.149 & 0.063 \\
  & (0.150) & (0.138) & (0.142) & (0.158) & (0.154) & (0.176) & (0.143) \\
  & & & & & & & \\
 ln(Population) & 0.364^{**} & 0.396^{**} & 0.390^{**} & 0.369^{**} & 0.377^{**} & 0.396^{**} & 0.368^{**} \\
  & (0.164) & (0.168) & (0.164) & (0.170) & (0.165) & (0.165) & (0.160) \\
  & & & & & & & \\
 Distance to Scotland & -0.531^{**} & -0.509^{**} & -0.505^{**} & -0.513^{**} & -0.526^{**} & -0.568^{**} & -0.496^{**} \\
  & (0.246) & (0.246) & (0.248) & (0.249) & (0.242) & (0.242) & (0.252) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-164.226} & \multicolumn{1}{c}{-164.656} & \multicolumn{1}{c}{-164.799} & \multicolumn{1}{c}{-163.427} & \multicolumn{1}{c}{-164.785} & \multicolumn{1}{c}{-164.003} & \multicolumn{1}{c}{-164.686} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:29
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Monastic Variables [ownOther_raw]}
  \label{tab:primary_monastic_ownOther_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.537^{*} &  &  &  &  &  &  \\
  & (0.304) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(On-site Monastic Land + 1) &  & -0.215 &  &  &  &  &  \\
  &  & (0.161) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe) &  &  & 0.054 &  &  &  &  \\
  &  &  & (0.203) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms) &  &  &  & 0.317^{***} &  &  &  \\
  &  &  &  & (0.086) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -1.113^{**} &  &  \\
  &  &  &  &  & (0.515) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.617 &  \\
  &  &  &  &  &  & (0.544) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.626 \\
  &  &  &  &  &  &  & (0.528) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.462 & -0.569 & -0.575 & -0.775 & -0.447 & -0.624 & -0.599 \\
  & (0.677) & (0.673) & (0.685) & (0.701) & (0.634) & (0.662) & (0.707) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & -0.125 & 0.119 & 0.128 & 0.140 & 0.184 & 0.049 & 0.148 \\
  & (0.298) & (0.360) & (0.328) & (0.360) & (0.353) & (0.351) & (0.354) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.133 & 0.206 & 0.177 & 0.167 & 0.252 & 0.161 & 0.180 \\
  & (0.230) & (0.210) & (0.230) & (0.222) & (0.203) & (0.202) & (0.220) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & -0.183 & -0.027 & -0.017 & -0.055 & 0.042 & -0.097 & -0.012 \\
  & (0.170) & (0.159) & (0.164) & (0.168) & (0.181) & (0.173) & (0.155) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.554^{**} & 0.391^{*} & 0.386^{*} & 0.409^{*} & 0.324 & 0.461^{*} & 0.383^{*} \\
  & (0.231) & (0.208) & (0.214) & (0.239) & (0.217) & (0.258) & (0.215) \\
  & & & & & & & \\
 ln(Population) & 0.423^{**} & 0.467^{**} & 0.456^{**} & 0.438^{**} & 0.430^{**} & 0.471^{**} & 0.439^{**} \\
  & (0.192) & (0.193) & (0.189) & (0.205) & (0.180) & (0.185) & (0.184) \\
  & & & & & & & \\
 Distance to Scotland & -0.636^{*} & -0.559 & -0.571 & -0.612 & -0.642^{*} & -0.641 & -0.555 \\
  & (0.381) & (0.375) & (0.373) & (0.375) & (0.365) & (0.410) & (0.376) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-86.321} & \multicolumn{1}{c}{-87.833} & \multicolumn{1}{c}{-88.123} & \multicolumn{1}{c}{-85.892} & \multicolumn{1}{c}{-87.012} & \multicolumn{1}{c}{-87.607} & \multicolumn{1}{c}{-87.977} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:29
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Monastic Variables [ownOther_raw]}
  \label{tab:seat_monastic_ownOther_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.202^{*} &  &  &  &  &  &  \\
  & (0.103) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(On-site Monastic Land + 1) &  & 0.107^{**} &  &  &  &  &  \\
  &  & (0.050) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe) &  &  & 0.132 &  &  &  &  \\
  &  &  & (0.113) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms) &  &  &  & 0.055 &  &  &  \\
  &  &  &  & (0.066) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & 0.705^{*} &  &  \\
  &  &  &  &  & (0.421) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.672^{**} &  \\
  &  &  &  &  &  & (0.301) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & -0.568 \\
  &  &  &  &  &  &  & (0.890) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & 0.124 & 0.067 & 0.090 & 0.057 & 0.051 & 0.006 & 0.082 \\
  & (0.363) & (0.388) & (0.383) & (0.397) & (0.390) & (0.389) & (0.384) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.645^{***} & 0.747^{***} & 0.710^{***} & 0.741^{***} & 0.730^{***} & 0.693^{***} & 0.745^{***} \\
  & (0.221) & (0.259) & (0.244) & (0.258) & (0.253) & (0.244) & (0.259) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.377^{***} & 0.385^{***} & 0.375^{***} & 0.383^{***} & 0.378^{***} & 0.391^{***} & 0.389^{***} \\
  & (0.068) & (0.076) & (0.081) & (0.075) & (0.072) & (0.065) & (0.071) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & 0.061 & 0.125 & 0.122 & 0.127 & 0.127 & 0.005 & 0.134 \\
  & (0.144) & (0.136) & (0.134) & (0.136) & (0.140) & (0.132) & (0.140) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.398^{***} & 0.354^{***} & 0.350^{**} & 0.350^{**} & 0.354^{**} & 0.464^{***} & 0.345^{**} \\
  & (0.139) & (0.137) & (0.136) & (0.138) & (0.142) & (0.123) & (0.141) \\
  & & & & & & & \\
 ln(Population) & 0.016 & 0.023 & 0.029 & 0.025 & 0.037 & 0.031 & 0.046 \\
  & (0.075) & (0.080) & (0.081) & (0.080) & (0.080) & (0.075) & (0.078) \\
  & & & & & & & \\
 Distance to Scotland & -0.871^{***} & -0.855^{***} & -0.856^{***} & -0.852^{***} & -0.833^{***} & -0.935^{***} & -0.856^{***} \\
  & (0.290) & (0.293) & (0.290) & (0.293) & (0.296) & (0.305) & (0.291) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-287.192} & \multicolumn{1}{c}{-288.001} & \multicolumn{1}{c}{-287.656} & \multicolumn{1}{c}{-288.409} & \multicolumn{1}{c}{-288.060} & \multicolumn{1}{c}{-285.824} & \multicolumn{1}{c}{-288.406} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:32
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Progressive Model [ownOther_raw]}
  \label{tab:muster_all_ownOther_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.477^{***} & 0.486^{***} & 0.306^{**} & 0.267^{**} \\
  & (0.178) & (0.143) & (0.131) & (0.124) \\
  & & & & \\
 ln(On-site Monastic Land + 1) & -0.080 & -0.426^{**} & -0.443 & -0.482 \\
  & (0.133) & (0.200) & (0.307) & (0.337) \\
  & & & & \\
 Small House Proximity (20km) & -0.999^{***} & -1.121^{***} & -0.611 & -0.461 \\
  & (0.336) & (0.358) & (0.690) & (0.643) \\
  & & & & \\
 Large House Proximity (20km) & -0.349 & -0.439 & 0.073 & 0.258 \\
  & (0.392) & (0.398) & (0.408) & (0.395) \\
  & & & & \\
 ln(Tithe) &  & -0.290^{***} & -0.343^{***} & -0.346^{**} \\
  &  & (0.101) & (0.128) & (0.148) \\
  & & & & \\
 ln(Alms) &  & 0.499^{***} & 0.474^{***} & 0.445^{***} \\
  &  & (0.097) & (0.152) & (0.152) \\
  & & & & \\
 Friary Presence &  & 1.034^{***} & 0.495 & 0.641 \\
  &  & (0.333) & (0.426) & (0.420) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.005 & 0.041 \\
  &  &  & (0.172) & (0.168) \\
  & & & & \\
 ln(Population) &  &  & 0.409^{***} & 0.341^{**} \\
  &  &  & (0.113) & (0.162) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.097 & -0.060 \\
  &  &  & (0.230) & (0.261) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.426^{***} & 0.304^{*} \\
  &  &  & (0.153) & (0.183) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-242.971} & \multicolumn{1}{c}{-232.977} & \multicolumn{1}{c}{-164.089} & \multicolumn{1}{c}{-161.724} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:33
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Progressive Model [ownOther_raw]}
  \label{tab:primary_all_ownOther_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.778^{***} & 0.735^{***} & 0.540 & 0.504 \\
  & (0.256) & (0.258) & (0.345) & (0.307) \\
  & & & & \\
 ln(On-site Monastic Land + 1) & -0.171 & -0.539^{***} & -0.640^{***} & -0.737^{***} \\
  & (0.218) & (0.191) & (0.195) & (0.175) \\
  & & & & \\
 Small House Proximity (20km) & -1.234^{***} & -1.374^{***} & -1.182^{*} & -1.221^{*} \\
  & (0.475) & (0.497) & (0.696) & (0.636) \\
  & & & & \\
 Large House Proximity (20km) & -0.574 & -0.708 & 0.081 & 0.104 \\
  & (0.590) & (0.591) & (0.510) & (0.481) \\
  & & & & \\
 ln(Tithe) &  & -0.219 & -0.293 & -0.319 \\
  &  & (0.190) & (0.257) & (0.287) \\
  & & & & \\
 ln(Alms) &  & 0.512^{***} & 0.599^{***} & 0.587^{***} \\
  &  & (0.095) & (0.076) & (0.087) \\
  & & & & \\
 Friary Presence &  & 0.501 & 0.544 & 0.681 \\
  &  & (0.580) & (0.714) & (0.504) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.004 & 0.014 \\
  &  &  & (0.239) & (0.228) \\
  & & & & \\
 ln(Population) &  &  & 0.426^{***} & 0.361^{*} \\
  &  &  & (0.149) & (0.200) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.161 & -0.135 \\
  &  &  & (0.192) & (0.204) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.722^{***} & 0.701^{**} \\
  &  &  & (0.269) & (0.303) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-134.025} & \multicolumn{1}{c}{-128.631} & \multicolumn{1}{c}{-82.954} & \multicolumn{1}{c}{-82.254} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:33
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Progressive Model [ownOther_raw]}
  \label{tab:seat_all_ownOther_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.318^{***} & 0.293^{***} & 0.192^{**} & 0.135 \\
  & (0.092) & (0.084) & (0.091) & (0.092) \\
  & & & & \\
 ln(On-site Monastic Land + 1) & -0.010 & -0.035 & 0.023 & 0.036 \\
  & (0.065) & (0.071) & (0.063) & (0.058) \\
  & & & & \\
 Small House Proximity (20km) & -0.041 & -0.031 & 1.238^{***} & 1.254^{***} \\
  & (0.496) & (0.503) & (0.443) & (0.448) \\
  & & & & \\
 Large House Proximity (20km) & -0.265 & -0.270 & 0.225 & 0.270 \\
  & (0.298) & (0.304) & (0.294) & (0.314) \\
  & & & & \\
 ln(Tithe) &  & 0.054 & 0.087 & 0.090 \\
  &  & (0.120) & (0.134) & (0.132) \\
  & & & & \\
 ln(Alms) &  & 0.034 & 0.012 & -0.032 \\
  &  & (0.070) & (0.070) & (0.073) \\
  & & & & \\
 Friary Presence &  & -0.710 & -0.335 & -0.110 \\
  &  & (0.766) & (0.752) & (0.768) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.068 & 0.051 \\
  &  &  & (0.135) & (0.119) \\
  & & & & \\
 ln(Population) &  &  & 0.070 & 0.021 \\
  &  &  & (0.082) & (0.097) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.005 & -0.024 \\
  &  &  & (0.176) & (0.193) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.738^{***} & 0.715^{***} \\
  &  &  & (0.198) & (0.194) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-428.522} & \multicolumn{1}{c}{-427.805} & \multicolumn{1}{c}{-317.196} & \multicolumn{1}{c}{-310.699} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:34
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model [ownOther_raw]}
  \label{tab:full_monastic_ownOther_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.287^{**} & 0.556^{*} & 0.115 \\
  & (0.123) & (0.326) & (0.096) \\
  & & & \\
 ln(On-site Monastic Land + 1) & -0.544 & -0.849^{***} & 0.077 \\
  & (0.348) & (0.171) & (0.075) \\
  & & & \\
 ln(Tithe) & -0.375^{***} & -0.372 & 0.080 \\
  & (0.145) & (0.314) & (0.121) \\
  & & & \\
 ln(Alms) & 0.488^{***} & 0.655^{***} & -0.058 \\
  & (0.155) & (0.083) & (0.095) \\
  & & & \\
 Small House Proximity (20km) & -0.710 & -1.641^{***} & 0.582 \\
  & (0.617) & (0.466) & (0.427) \\
  & & & \\
 Large House Proximity (20km) & 0.532 & 0.568 & 0.580^{**} \\
  & (0.379) & (0.535) & (0.293) \\
  & & & \\
 Friary Presence & 0.557 & 0.572 & -0.673 \\
  & (0.399) & (0.541) & (0.921) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.700 & -0.705 & 0.074 \\
  & (0.452) & (0.637) & (0.399) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.258 & -0.111 & 0.614^{***} \\
  & (0.386) & (0.376) & (0.209) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.233^{*} & 0.305 & 0.379^{***} \\
  & (0.130) & (0.206) & (0.069) \\
  & & & \\
 Wet 1535 Weather Shock & -0.104 & -0.243 & -0.026 \\
  & (0.252) & (0.201) & (0.133) \\
  & & & \\
 Wet 1536 Weather Shock & 0.193 & 0.612^{**} & 0.488^{***} \\
  & (0.189) & (0.308) & (0.122) \\
  & & & \\
 ln(Population) & 0.366^{**} & 0.421^{**} & 0.037 \\
  & (0.156) & (0.187) & (0.069) \\
  & & & \\
 Distance to Scotland & -0.658^{***} & -0.889^{**} & -0.941^{***} \\
  & (0.232) & (0.405) & (0.308) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-156.818} & \multicolumn{1}{c}{-78.436} & \multicolumn{1}{c}{-283.811} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:39
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Monastic Variables [ownOther_sk]}
  \label{tab:muster_monastic_ownOther_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.172 &  &  &  &  &  &  \\
  & (0.186) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(On-site Land / km²) &  & -0.216 &  &  &  &  &  \\
  &  & (0.217) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe / km²) &  &  & -0.170 &  &  &  &  \\
  &  &  & (0.161) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms / km²) &  &  &  & 0.211^{*} &  &  &  \\
  &  &  &  & (0.112) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -0.425 &  &  \\
  &  &  &  &  & (0.543) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.608^{*} &  \\
  &  &  &  &  &  & (0.317) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.643 \\
  &  &  &  &  &  &  & (0.429) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.569 & -0.578 & -0.593 & -0.627 & -0.551 & -0.626 & -0.607 \\
  & (0.501) & (0.503) & (0.504) & (0.504) & (0.515) & (0.506) & (0.511) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.327 & 0.357 & 0.389 & 0.353 & 0.368 & 0.290 & 0.368 \\
  & (0.395) & (0.441) & (0.427) & (0.426) & (0.444) & (0.420) & (0.441) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.184 & 0.204 & 0.217^{*} & 0.207^{*} & 0.220^{*} & 0.187 & 0.201 \\
  & (0.131) & (0.134) & (0.130) & (0.124) & (0.134) & (0.124) & (0.129) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & -0.008 & 0.041 & 0.033 & 0.010 & 0.046 & -0.065 & 0.037 \\
  & (0.226) & (0.213) & (0.218) & (0.227) & (0.231) & (0.239) & (0.210) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.098 & 0.057 & 0.068 & 0.075 & 0.054 & 0.149 & 0.063 \\
  & (0.150) & (0.137) & (0.141) & (0.154) & (0.154) & (0.176) & (0.143) \\
  & & & & & & & \\
 ln(Population) & 0.374^{**} & 0.395^{**} & 0.391^{**} & 0.380^{**} & 0.377^{**} & 0.396^{**} & 0.368^{**} \\
  & (0.164) & (0.168) & (0.164) & (0.170) & (0.165) & (0.165) & (0.160) \\
  & & & & & & & \\
 Distance to Scotland & -0.527^{**} & -0.509^{**} & -0.504^{**} & -0.518^{**} & -0.526^{**} & -0.568^{**} & -0.496^{**} \\
  & (0.245) & (0.245) & (0.249) & (0.248) & (0.242) & (0.242) & (0.252) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-164.652} & \multicolumn{1}{c}{-164.598} & \multicolumn{1}{c}{-164.573} & \multicolumn{1}{c}{-163.712} & \multicolumn{1}{c}{-164.785} & \multicolumn{1}{c}{-164.003} & \multicolumn{1}{c}{-164.686} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:40
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Monastic Variables [ownOther_sk]}
  \label{tab:primary_monastic_ownOther_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.462 &  &  &  &  &  &  \\
  & (0.350) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(On-site Land / km²) &  & -0.446^{*} &  &  &  &  &  \\
  &  & (0.232) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe / km²) &  &  & -0.022 &  &  &  &  \\
  &  &  & (0.238) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms / km²) &  &  &  & 0.293^{***} &  &  &  \\
  &  &  &  & (0.102) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & -1.113^{**} &  &  \\
  &  &  &  &  & (0.515) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.617 &  \\
  &  &  &  &  &  & (0.544) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & 0.626 \\
  &  &  &  &  &  &  & (0.528) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.536 & -0.568 & -0.575 & -0.671 & -0.447 & -0.624 & -0.599 \\
  & (0.679) & (0.672) & (0.681) & (0.684) & (0.634) & (0.662) & (0.707) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.001 & 0.116 & 0.142 & 0.115 & 0.184 & 0.049 & 0.148 \\
  & (0.299) & (0.358) & (0.329) & (0.342) & (0.353) & (0.351) & (0.354) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.132 & 0.202 & 0.188 & 0.179 & 0.252 & 0.161 & 0.180 \\
  & (0.236) & (0.210) & (0.228) & (0.211) & (0.203) & (0.202) & (0.220) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & -0.130 & -0.018 & -0.017 & -0.038 & 0.042 & -0.097 & -0.012 \\
  & (0.183) & (0.158) & (0.164) & (0.166) & (0.181) & (0.173) & (0.155) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.488^{**} & 0.383^{*} & 0.386^{*} & 0.386^{*} & 0.324 & 0.461^{*} & 0.383^{*} \\
  & (0.220) & (0.206) & (0.212) & (0.232) & (0.217) & (0.258) & (0.215) \\
  & & & & & & & \\
 ln(Population) & 0.439^{**} & 0.469^{**} & 0.458^{**} & 0.455^{**} & 0.430^{**} & 0.471^{**} & 0.439^{**} \\
  & (0.187) & (0.194) & (0.189) & (0.203) & (0.180) & (0.185) & (0.184) \\
  & & & & & & & \\
 Distance to Scotland & -0.636^{*} & -0.559 & -0.566 & -0.609^{*} & -0.642^{*} & -0.641 & -0.555 \\
  & (0.376) & (0.375) & (0.373) & (0.370) & (0.365) & (0.410) & (0.376) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-86.909} & \multicolumn{1}{c}{-87.601} & \multicolumn{1}{c}{-88.152} & \multicolumn{1}{c}{-86.537} & \multicolumn{1}{c}{-87.012} & \multicolumn{1}{c}{-87.607} & \multicolumn{1}{c}{-87.977} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:40
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Monastic Variables [ownOther_sk]}
  \label{tab:seat_monastic_ownOther_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{7}{c}{\textit{Dependent variable:}} \\
\cline{2-8}
\\[-1.8ex] & \multicolumn{7}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.074 &  &  &  &  &  &  \\
  & (0.090) &  &  &  &  &  &  \\
  & & & & & & & \\
 ln(On-site Land / km²) &  & 0.130^{**} &  &  &  &  &  \\
  &  & (0.054) &  &  &  &  &  \\
  & & & & & & & \\
 ln(Tithe / km²) &  &  & 0.096 &  &  &  &  \\
  &  &  & (0.123) &  &  &  &  \\
  & & & & & & & \\
 ln(Alms / km²) &  &  &  & 0.025 &  &  &  \\
  &  &  &  & (0.064) &  &  &  \\
  & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  & 0.705^{*} &  &  \\
  &  &  &  &  & (0.421) &  &  \\
  & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  & 0.672^{**} &  \\
  &  &  &  &  &  & (0.301) &  \\
  & & & & & & & \\
 Friary Presence &  &  &  &  &  &  & -0.568 \\
  &  &  &  &  &  &  & (0.890) \\
  & & & & & & & \\
 Snubbed Family Proximity (20 km) & 0.085 & 0.068 & 0.084 & 0.067 & 0.051 & 0.006 & 0.082 \\
  & (0.373) & (0.386) & (0.382) & (0.392) & (0.390) & (0.389) & (0.384) \\
  & & & & & & & \\
 Court Officer Proximity (20 km) & 0.719^{***} & 0.746^{***} & 0.724^{***} & 0.742^{***} & 0.730^{***} & 0.693^{***} & 0.745^{***} \\
  & (0.239) & (0.259) & (0.245) & (0.258) & (0.253) & (0.244) & (0.259) \\
  & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.382^{***} & 0.388^{***} & 0.379^{***} & 0.385^{***} & 0.378^{***} & 0.391^{***} & 0.389^{***} \\
  & (0.071) & (0.076) & (0.079) & (0.073) & (0.072) & (0.065) & (0.071) \\
  & & & & & & & \\
 Wet 1535 Weather Shock & 0.113 & 0.120 & 0.128 & 0.131 & 0.127 & 0.005 & 0.134 \\
  & (0.147) & (0.137) & (0.137) & (0.138) & (0.140) & (0.132) & (0.140) \\
  & & & & & & & \\
 Wet 1536 Weather Shock & 0.358^{**} & 0.356^{***} & 0.347^{**} & 0.346^{**} & 0.354^{**} & 0.464^{***} & 0.345^{**} \\
  & (0.141) & (0.138) & (0.138) & (0.140) & (0.142) & (0.123) & (0.141) \\
  & & & & & & & \\
 ln(Population) & 0.029 & 0.027 & 0.032 & 0.032 & 0.037 & 0.031 & 0.046 \\
  & (0.078) & (0.080) & (0.080) & (0.078) & (0.080) & (0.075) & (0.078) \\
  & & & & & & & \\
 Distance to Scotland & -0.857^{***} & -0.856^{***} & -0.855^{***} & -0.850^{***} & -0.833^{***} & -0.935^{***} & -0.856^{***} \\
  & (0.293) & (0.292) & (0.289) & (0.293) & (0.296) & (0.305) & (0.291) \\
  & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-288.447} & \multicolumn{1}{c}{-287.799} & \multicolumn{1}{c}{-288.177} & \multicolumn{1}{c}{-288.588} & \multicolumn{1}{c}{-288.060} & \multicolumn{1}{c}{-285.824} & \multicolumn{1}{c}{-288.406} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{7}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:43
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Progressive Model [ownOther_sk]}
  \label{tab:muster_all_ownOther_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.223 & 0.219 & 0.150 & 0.190 \\
  & (0.167) & (0.149) & (0.134) & (0.141) \\
  & & & & \\
 ln(On-site Land / km²) & -0.152 & -0.485 & -0.532 & -0.550 \\
  & (0.147) & (0.319) & (0.424) & (0.449) \\
  & & & & \\
 Small House Proximity (20km) & -1.022^{***} & -1.096^{***} & -0.568 & -0.417 \\
  & (0.338) & (0.353) & (0.694) & (0.632) \\
  & & & & \\
 Large House Proximity (20km) & -0.279 & -0.338 & 0.127 & 0.298 \\
  & (0.386) & (0.389) & (0.404) & (0.377) \\
  & & & & \\
 ln(Tithe / km²) &  & -0.184^{*} & -0.310^{**} & -0.332^{**} \\
  &  & (0.098) & (0.125) & (0.140) \\
  & & & & \\
 ln(Alms / km²) &  & 0.413^{***} & 0.467^{**} & 0.440^{**} \\
  &  & (0.153) & (0.205) & (0.200) \\
  & & & & \\
 Friary Presence &  & 1.023^{***} & 0.486 & 0.654 \\
  &  & (0.366) & (0.436) & (0.419) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.017 & 0.048 \\
  &  &  & (0.166) & (0.167) \\
  & & & & \\
 ln(Population) &  &  & 0.446^{***} & 0.352^{**} \\
  &  &  & (0.117) & (0.164) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.032 & -0.018 \\
  &  &  & (0.230) & (0.267) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.384^{**} & 0.260 \\
  &  &  & (0.151) & (0.187) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-246.973} & \multicolumn{1}{c}{-239.922} & \multicolumn{1}{c}{-165.636} & \multicolumn{1}{c}{-162.507} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:44
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Progressive Model [ownOther_sk]}
  \label{tab:primary_all_ownOther_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.437^{*} & 0.386 & 0.407 & 0.458 \\
  & (0.227) & (0.252) & (0.358) & (0.362) \\
  & & & & \\
 ln(On-site Land / km²) & -0.309 & -0.655^{**} & -0.899^{***} & -1.135^{***} \\
  & (0.234) & (0.263) & (0.293) & (0.289) \\
  & & & & \\
 Small House Proximity (20km) & -1.326^{***} & -1.386^{***} & -1.114^{*} & -1.152^{**} \\
  & (0.439) & (0.448) & (0.663) & (0.576) \\
  & & & & \\
 Large House Proximity (20km) & -0.513 & -0.596 & 0.108 & 0.118 \\
  & (0.589) & (0.597) & (0.621) & (0.580) \\
  & & & & \\
 ln(Tithe / km²) &  & -0.107 & -0.275 & -0.315 \\
  &  & (0.157) & (0.259) & (0.276) \\
  & & & & \\
 ln(Alms / km²) &  & 0.423^{***} & 0.608^{***} & 0.586^{***} \\
  &  & (0.135) & (0.118) & (0.127) \\
  & & & & \\
 Friary Presence &  & 0.480 & 0.427 & 0.664 \\
  &  & (0.653) & (0.827) & (0.550) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.010 & 0.017 \\
  &  &  & (0.234) & (0.229) \\
  & & & & \\
 ln(Population) &  &  & 0.490^{***} & 0.376^{*} \\
  &  &  & (0.157) & (0.197) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.074 & -0.068 \\
  &  &  & (0.206) & (0.217) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.675^{***} & 0.631^{**} \\
  &  &  & (0.257) & (0.282) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-137.908} & \multicolumn{1}{c}{-134.402} & \multicolumn{1}{c}{-84.712} & \multicolumn{1}{c}{-83.147} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:44
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Progressive Model [ownOther_sk]}
  \label{tab:seat_all_ownOther_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.046 & 0.011 & 0.0002 & -0.030 \\
  & (0.092) & (0.093) & (0.080) & (0.074) \\
  & & & & \\
 ln(On-site Land / km²) & 0.027 & 0.024 & 0.089 & 0.101 \\
  & (0.067) & (0.070) & (0.067) & (0.064) \\
  & & & & \\
 Small House Proximity (20km) & -0.040 & -0.027 & 1.275^{***} & 1.272^{***} \\
  & (0.480) & (0.487) & (0.449) & (0.448) \\
  & & & & \\
 Large House Proximity (20km) & -0.181 & -0.177 & 0.322 & 0.354 \\
  & (0.290) & (0.295) & (0.303) & (0.323) \\
  & & & & \\
 ln(Tithe / km²) &  & 0.096 & 0.095 & 0.089 \\
  &  & (0.112) & (0.138) & (0.136) \\
  & & & & \\
 ln(Alms / km²) &  & -0.007 & -0.038 & -0.074 \\
  &  & (0.066) & (0.074) & (0.075) \\
  & & & & \\
 Friary Presence &  & -0.692 & -0.346 & -0.086 \\
  &  & (0.780) & (0.785) & (0.785) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.089 & 0.074 \\
  &  &  & (0.127) & (0.113) \\
  & & & & \\
 ln(Population) &  &  & 0.112 & 0.041 \\
  &  &  & (0.079) & (0.102) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & 0.026 & 0.008 \\
  &  &  & (0.181) & (0.199) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.715^{***} & 0.689^{***} \\
  &  &  & (0.192) & (0.193) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-433.648} & \multicolumn{1}{c}{-432.755} & \multicolumn{1}{c}{-319.012} & \multicolumn{1}{c}{-311.510} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:45
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model [ownOther_sk]}
  \label{tab:full_monastic_ownOther_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.225 & 0.514 & -0.019 \\
  & (0.142) & (0.375) & (0.076) \\
  & & & \\
 ln(On-site Land / km²) & -0.607 & -1.298^{***} & 0.180^{**} \\
  & (0.467) & (0.311) & (0.086) \\
  & & & \\
 ln(Tithe / km²) & -0.359^{***} & -0.352 & 0.082 \\
  & (0.135) & (0.284) & (0.128) \\
  & & & \\
 ln(Alms / km²) & 0.478^{**} & 0.652^{***} & -0.137 \\
  & (0.204) & (0.121) & (0.108) \\
  & & & \\
 Small House Proximity (20km) & -0.661 & -1.562^{***} & 0.577 \\
  & (0.611) & (0.438) & (0.419) \\
  & & & \\
 Large House Proximity (20km) & 0.543 & 0.522 & 0.645^{**} \\
  & (0.352) & (0.612) & (0.302) \\
  & & & \\
 Friary Presence & 0.552 & 0.512 & -0.668 \\
  & (0.391) & (0.586) & (0.951) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.678 & -0.633 & 0.040 \\
  & (0.474) & (0.607) & (0.404) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.297 & -0.025 & 0.690^{***} \\
  & (0.389) & (0.335) & (0.227) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.232^{*} & 0.304 & 0.395^{***} \\
  & (0.131) & (0.193) & (0.067) \\
  & & & \\
 Wet 1535 Weather Shock & -0.055 & -0.158 & 0.005 \\
  & (0.257) & (0.208) & (0.130) \\
  & & & \\
 Wet 1536 Weather Shock & 0.147 & 0.523^{*} & 0.473^{***} \\
  & (0.189) & (0.280) & (0.120) \\
  & & & \\
 ln(Population) & 0.379^{**} & 0.437^{**} & 0.051 \\
  & (0.156) & (0.186) & (0.071) \\
  & & & \\
 Distance to Scotland & -0.648^{***} & -0.880^{**} & -0.940^{***} \\
  & (0.235) & (0.390) & (0.306) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-157.783} & \multicolumn{1}{c}{-79.540} & \multicolumn{1}{c}{-283.889} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:50
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Monastic Variables [ownOther_arak]}
  \label{tab:muster_monastic_ownOther_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{8}{c}{\textit{Dependent variable:}} \\
\cline{2-9}
\\[-1.8ex] & \multicolumn{8}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)} & \multicolumn{1}{c}{(8)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.246^{*} &  &  &  &  &  &  &  \\
  & (0.149) &  &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(On-site Land / Arable km²) &  & -0.223 &  &  &  &  &  &  \\
  &  & (0.207) &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Tithe / Arable km²) &  &  & -0.131 &  &  &  &  &  \\
  &  &  & (0.145) &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Alms / Arable km²) &  &  &  & 0.224^{**} &  &  &  &  \\
  &  &  &  & (0.110) &  &  &  &  \\
  & & & & & & & & \\
 ln(Net Income / Arable km²) &  &  &  &  & 0.344^{***} &  &  &  \\
  &  &  &  &  & (0.109) &  &  &  \\
  & & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  &  & -0.425 &  &  \\
  &  &  &  &  &  & (0.543) &  &  \\
  & & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  &  & 0.608^{*} &  \\
  &  &  &  &  &  &  & (0.317) &  \\
  & & & & & & & & \\
 Friary Presence &  &  &  &  &  &  &  & 0.643 \\
  &  &  &  &  &  &  &  & (0.429) \\
  & & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.568 & -0.581 & -0.594 & -0.636 & -0.726 & -0.551 & -0.626 & -0.607 \\
  & (0.483) & (0.503) & (0.505) & (0.498) & (0.509) & (0.515) & (0.506) & (0.511) \\
  & & & & & & & & \\
 Court Officer Proximity (20 km) & 0.320 & 0.354 & 0.383 & 0.356 & 0.439 & 0.368 & 0.290 & 0.368 \\
  & (0.403) & (0.438) & (0.429) & (0.438) & (0.486) & (0.444) & (0.420) & (0.441) \\
  & & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.165 & 0.207 & 0.216^{*} & 0.199 & 0.204^{*} & 0.220^{*} & 0.187 & 0.201 \\
  & (0.136) & (0.135) & (0.130) & (0.122) & (0.124) & (0.134) & (0.124) & (0.129) \\
  & & & & & & & & \\
 Wet 1535 Weather Shock & -0.035 & 0.041 & 0.032 & 0.008 & -0.046 & 0.046 & -0.065 & 0.037 \\
  & (0.219) & (0.214) & (0.218) & (0.226) & (0.225) & (0.231) & (0.239) & (0.210) \\
  & & & & & & & & \\
 Wet 1536 Weather Shock & 0.128 & 0.055 & 0.066 & 0.084 & 0.112 & 0.054 & 0.149 & 0.063 \\
  & (0.144) & (0.137) & (0.142) & (0.155) & (0.152) & (0.154) & (0.176) & (0.143) \\
  & & & & & & & & \\
 ln(Population) & 0.368^{**} & 0.397^{**} & 0.392^{**} & 0.376^{**} & 0.376^{**} & 0.377^{**} & 0.396^{**} & 0.368^{**} \\
  & (0.161) & (0.168) & (0.164) & (0.169) & (0.168) & (0.165) & (0.165) & (0.160) \\
  & & & & & & & & \\
 Distance to Scotland & -0.531^{**} & -0.512^{**} & -0.507^{**} & -0.511^{**} & -0.498^{**} & -0.526^{**} & -0.568^{**} & -0.496^{**} \\
  & (0.246) & (0.245) & (0.249) & (0.247) & (0.249) & (0.242) & (0.242) & (0.252) \\
  & & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-164.120} & \multicolumn{1}{c}{-164.558} & \multicolumn{1}{c}{-164.745} & \multicolumn{1}{c}{-163.539} & \multicolumn{1}{c}{-161.461} & \multicolumn{1}{c}{-164.785} & \multicolumn{1}{c}{-164.003} & \multicolumn{1}{c}{-164.686} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{8}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:51
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Monastic Variables [ownOther_arak]}
  \label{tab:primary_monastic_ownOther_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{8}{c}{\textit{Dependent variable:}} \\
\cline{2-9}
\\[-1.8ex] & \multicolumn{8}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)} & \multicolumn{1}{c}{(8)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.503^{*} &  &  &  &  &  &  &  \\
  & (0.296) &  &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(On-site Land / Arable km²) &  & -0.423^{*} &  &  &  &  &  &  \\
  &  & (0.219) &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Tithe / Arable km²) &  &  & 0.013 &  &  &  &  &  \\
  &  &  & (0.215) &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Alms / Arable km²) &  &  &  & 0.302^{***} &  &  &  &  \\
  &  &  &  & (0.109) &  &  &  &  \\
  & & & & & & & & \\
 ln(Net Income / Arable km²) &  &  &  &  & 0.378^{***} &  &  &  \\
  &  &  &  &  & (0.137) &  &  &  \\
  & & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  &  & -1.113^{**} &  &  \\
  &  &  &  &  &  & (0.515) &  &  \\
  & & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  &  & 0.617 &  \\
  &  &  &  &  &  &  & (0.544) &  \\
  & & & & & & & & \\
 Friary Presence &  &  &  &  &  &  &  & 0.626 \\
  &  &  &  &  &  &  &  & (0.528) \\
  & & & & & & & & \\
 Snubbed Family Proximity (20 km) & -0.538 & -0.571 & -0.575 & -0.691 & -0.791 & -0.447 & -0.624 & -0.599 \\
  & (0.648) & (0.674) & (0.682) & (0.678) & (0.661) & (0.634) & (0.662) & (0.707) \\
  & & & & & & & & \\
 Court Officer Proximity (20 km) & 0.006 & 0.115 & 0.137 & 0.125 & 0.237 & 0.184 & 0.049 & 0.148 \\
  & (0.292) & (0.357) & (0.332) & (0.352) & (0.382) & (0.353) & (0.351) & (0.354) \\
  & & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.106 & 0.205 & 0.183 & 0.159 & 0.178 & 0.252 & 0.161 & 0.180 \\
  & (0.237) & (0.210) & (0.230) & (0.219) & (0.210) & (0.203) & (0.202) & (0.220) \\
  & & & & & & & & \\
 Wet 1535 Weather Shock & -0.163 & -0.017 & -0.017 & -0.039 & -0.094 & 0.042 & -0.097 & -0.012 \\
  & (0.182) & (0.158) & (0.164) & (0.168) & (0.176) & (0.181) & (0.173) & (0.155) \\
  & & & & & & & & \\
 Wet 1536 Weather Shock & 0.547^{**} & 0.382^{*} & 0.387^{*} & 0.399^{*} & 0.427^{*} & 0.324 & 0.461^{*} & 0.383^{*} \\
  & (0.224) & (0.206) & (0.209) & (0.228) & (0.233) & (0.217) & (0.258) & (0.215) \\
  & & & & & & & & \\
 ln(Population) & 0.438^{**} & 0.471^{**} & 0.457^{**} & 0.451^{**} & 0.446^{**} & 0.430^{**} & 0.471^{**} & 0.439^{**} \\
  & (0.181) & (0.194) & (0.188) & (0.200) & (0.195) & (0.180) & (0.185) & (0.184) \\
  & & & & & & & & \\
 Distance to Scotland & -0.628^{*} & -0.563 & -0.568 & -0.596 & -0.575 & -0.642^{*} & -0.641 & -0.555 \\
  & (0.378) & (0.376) & (0.374) & (0.371) & (0.375) & (0.365) & (0.410) & (0.376) \\
  & & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-86.469} & \multicolumn{1}{c}{-87.606} & \multicolumn{1}{c}{-88.154} & \multicolumn{1}{c}{-86.419} & \multicolumn{1}{c}{-85.972} & \multicolumn{1}{c}{-87.012} & \multicolumn{1}{c}{-87.607} & \multicolumn{1}{c}{-87.977} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{8}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:52
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Monastic Variables [ownOther_arak]}
  \label{tab:seat_monastic_ownOther_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{8}{c}{\textit{Dependent variable:}} \\
\cline{2-9}
\\[-1.8ex] & \multicolumn{8}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)} & \multicolumn{1}{c}{(5)} & \multicolumn{1}{c}{(6)} & \multicolumn{1}{c}{(7)} & \multicolumn{1}{c}{(8)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.178 &  &  &  &  &  &  &  \\
  & (0.109) &  &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(On-site Land / Arable km²) &  & 0.083 &  &  &  &  &  &  \\
  &  & (0.059) &  &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Tithe / Arable km²) &  &  & 0.103 &  &  &  &  &  \\
  &  &  & (0.110) &  &  &  &  &  \\
  & & & & & & & & \\
 ln(Alms / Arable km²) &  &  &  & -0.001 &  &  &  &  \\
  &  &  &  & (0.071) &  &  &  &  \\
  & & & & & & & & \\
 ln(Net Income / Arable km²) &  &  &  &  & 0.073 &  &  &  \\
  &  &  &  &  & (0.086) &  &  &  \\
  & & & & & & & & \\
 Small House Proximity (20km) &  &  &  &  &  & 0.705^{*} &  &  \\
  &  &  &  &  &  & (0.421) &  &  \\
  & & & & & & & & \\
 Large House Proximity (20km) &  &  &  &  &  &  & 0.672^{**} &  \\
  &  &  &  &  &  &  & (0.301) &  \\
  & & & & & & & & \\
 Friary Presence &  &  &  &  &  &  &  & -0.568 \\
  &  &  &  &  &  &  &  & (0.890) \\
  & & & & & & & & \\
 Snubbed Family Proximity (20 km) & 0.084 & 0.072 & 0.086 & 0.071 & 0.038 & 0.051 & 0.006 & 0.082 \\
  & (0.374) & (0.383) & (0.381) & (0.391) & (0.402) & (0.390) & (0.389) & (0.384) \\
  & & & & & & & & \\
 Court Officer Proximity (20 km) & 0.705^{***} & 0.749^{***} & 0.729^{***} & 0.745^{***} & 0.758^{***} & 0.730^{***} & 0.693^{***} & 0.745^{***} \\
  & (0.241) & (0.261) & (0.249) & (0.259) & (0.270) & (0.253) & (0.244) & (0.259) \\
  & & & & & & & & \\
 ln(Lay Subsidy per Capita) & 0.371^{***} & 0.387^{***} & 0.378^{***} & 0.387^{***} & 0.386^{***} & 0.378^{***} & 0.391^{***} & 0.389^{***} \\
  & (0.067) & (0.074) & (0.078) & (0.072) & (0.072) & (0.072) & (0.065) & (0.071) \\
  & & & & & & & & \\
 Wet 1535 Weather Shock & 0.079 & 0.127 & 0.128 & 0.134 & 0.121 & 0.127 & 0.005 & 0.134 \\
  & (0.146) & (0.138) & (0.136) & (0.139) & (0.137) & (0.140) & (0.132) & (0.140) \\
  & & & & & & & & \\
 Wet 1536 Weather Shock & 0.387^{***} & 0.352^{**} & 0.348^{**} & 0.345^{**} & 0.352^{**} & 0.354^{**} & 0.464^{***} & 0.345^{**} \\
  & (0.143) & (0.139) & (0.138) & (0.140) & (0.139) & (0.142) & (0.123) & (0.141) \\
  & & & & & & & & \\
 ln(Population) & 0.023 & 0.029 & 0.031 & 0.034 & 0.027 & 0.037 & 0.031 & 0.046 \\
  & (0.075) & (0.080) & (0.079) & (0.077) & (0.081) & (0.080) & (0.075) & (0.078) \\
  & & & & & & & & \\
 Distance to Scotland & -0.872^{***} & -0.852^{***} & -0.856^{***} & -0.849^{***} & -0.848^{***} & -0.833^{***} & -0.935^{***} & -0.856^{***} \\
  & (0.294) & (0.292) & (0.289) & (0.293) & (0.292) & (0.296) & (0.305) & (0.291) \\
  & & & & & & & & \\
\hline \\[-1.8ex]
Controls & Y & Y & Y & Y & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-287.553} & \multicolumn{1}{c}{-288.314} & \multicolumn{1}{c}{-288.091} & \multicolumn{1}{c}{-288.622} & \multicolumn{1}{c}{-288.353} & \multicolumn{1}{c}{-288.060} & \multicolumn{1}{c}{-285.824} & \multicolumn{1}{c}{-288.406} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{8}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:55
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster — Progressive Model [ownOther_arak]}
  \label{tab:muster_all_ownOther_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.327^{***} & 0.316^{***} & 0.245^{*} & 0.242^{*} \\
  & (0.114) & (0.081) & (0.126) & (0.128) \\
  & & & & \\
 ln(On-site Land / Arable km²) & -0.113 & -0.653^{***} & -0.708^{**} & -0.729^{**} \\
  & (0.123) & (0.190) & (0.311) & (0.330) \\
  & & & & \\
 Small House Proximity (20km) & -1.009^{***} & -1.159^{***} & -0.646 & -0.521 \\
  & (0.332) & (0.349) & (0.653) & (0.594) \\
  & & & & \\
 Large House Proximity (20km) & -0.305 & -0.431 & 0.031 & 0.211 \\
  & (0.407) & (0.417) & (0.426) & (0.385) \\
  & & & & \\
 ln(Tithe / Arable km²) &  & -0.250^{*} & -0.296^{***} & -0.306^{**} \\
  &  & (0.129) & (0.115) & (0.129) \\
  & & & & \\
 ln(Alms / Arable km²) &  & 0.346^{***} & 0.294^{*} & 0.263 \\
  &  & (0.124) & (0.172) & (0.167) \\
  & & & & \\
 ln(Net Income / Arable km²) &  & 0.394^{***} & 0.495^{***} & 0.491^{***} \\
  &  & (0.101) & (0.109) & (0.104) \\
  & & & & \\
 Friary Presence &  & 0.951^{**} & 0.399 & 0.553 \\
  &  & (0.390) & (0.518) & (0.477) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.035 & 0.058 \\
  &  &  & (0.170) & (0.175) \\
  & & & & \\
 ln(Population) &  &  & 0.443^{***} & 0.365^{**} \\
  &  &  & (0.119) & (0.165) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.140 & -0.118 \\
  &  &  & (0.225) & (0.257) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.410^{***} & 0.308^{*} \\
  &  &  & (0.148) & (0.171) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-245.422} & \multicolumn{1}{c}{-231.796} & \multicolumn{1}{c}{-159.740} & \multicolumn{1}{c}{-157.111} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:56
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary — Progressive Model [ownOther_arak]}
  \label{tab:primary_all_ownOther_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.488^{***} & 0.462^{***} & 0.454 & 0.497 \\
  & (0.119) & (0.114) & (0.297) & (0.305) \\
  & & & & \\
 ln(On-site Land / Arable km²) & -0.292 & -0.800^{***} & -0.971^{***} & -1.190^{***} \\
  & (0.217) & (0.203) & (0.252) & (0.249) \\
  & & & & \\
 Small House Proximity (20km) & -1.256^{***} & -1.387^{***} & -1.143^{*} & -1.277^{**} \\
  & (0.454) & (0.471) & (0.681) & (0.598) \\
  & & & & \\
 Large House Proximity (20km) & -0.504 & -0.663 & 0.020 & -0.014 \\
  & (0.619) & (0.623) & (0.618) & (0.559) \\
  & & & & \\
 ln(Tithe / Arable km²) &  & -0.201 & -0.224 & -0.254 \\
  &  & (0.223) & (0.221) & (0.242) \\
  & & & & \\
 ln(Alms / Arable km²) &  & 0.346^{***} & 0.421^{***} & 0.407^{***} \\
  &  & (0.097) & (0.088) & (0.095) \\
  & & & & \\
 ln(Net Income / Arable km²) &  & 0.349^{***} & 0.448^{***} & 0.464^{***} \\
  &  & (0.119) & (0.139) & (0.120) \\
  & & & & \\
 Friary Presence &  & 0.472 & 0.353 & 0.583 \\
  &  & (0.628) & (0.926) & (0.607) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.051 & 0.045 \\
  &  &  & (0.228) & (0.228) \\
  & & & & \\
 ln(Population) &  &  & 0.477^{***} & 0.376^{*} \\
  &  &  & (0.160) & (0.204) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.190 & -0.172 \\
  &  &  & (0.203) & (0.212) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.708^{***} & 0.703^{**} \\
  &  &  & (0.254) & (0.286) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-136.996} & \multicolumn{1}{c}{-131.105} & \multicolumn{1}{c}{-82.088} & \multicolumn{1}{c}{-80.580} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:56
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats — Progressive Model [ownOther_arak]}
  \label{tab:seat_all_ownOther_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{dep} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.222^{***} & 0.187^{**} & 0.129 & 0.085 \\
  & (0.068) & (0.079) & (0.104) & (0.109) \\
  & & & & \\
 ln(On-site Land / Arable km²) & -0.035 & -0.110 & -0.010 & -0.006 \\
  & (0.069) & (0.098) & (0.081) & (0.076) \\
  & & & & \\
 Small House Proximity (20km) & -0.049 & -0.062 & 1.262^{***} & 1.267^{***} \\
  & (0.504) & (0.502) & (0.439) & (0.440) \\
  & & & & \\
 Large House Proximity (20km) & -0.235 & -0.236 & 0.279 & 0.319 \\
  & (0.300) & (0.305) & (0.295) & (0.310) \\
  & & & & \\
 ln(Tithe / Arable km²) &  & 0.071 & 0.075 & 0.065 \\
  &  & (0.095) & (0.129) & (0.129) \\
  & & & & \\
 ln(Alms / Arable km²) &  & -0.064 & -0.066 & -0.113 \\
  &  & (0.064) & (0.091) & (0.091) \\
  & & & & \\
 ln(Net Income / Arable km²) &  & 0.143^{*} & 0.097 & 0.102 \\
  &  & (0.073) & (0.086) & (0.090) \\
  & & & & \\
 Friary Presence &  & -0.730 & -0.407 & -0.157 \\
  &  & (0.771) & (0.792) & (0.797) \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.079 & 0.068 \\
  &  &  & (0.132) & (0.117) \\
  & & & & \\
 ln(Population) &  &  & 0.101 & 0.038 \\
  &  &  & (0.078) & (0.098) \\
  & & & & \\
 Wet 1535 Weather Shock &  &  & -0.003 & -0.020 \\
  &  &  & (0.182) & (0.201) \\
  & & & & \\
 Wet 1536 Weather Shock &  &  & 0.739^{***} & 0.711^{***} \\
  &  &  & (0.198) & (0.197) \\
  & & & & \\
\hline \\[-1.8ex]
Controls & N & N & N & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,755} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-431.026} & \multicolumn{1}{c}{-429.495} & \multicolumn{1}{c}{-318.175} & \multicolumn{1}{c}{-311.071} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:57
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model [ownOther_arak]}
  \label{tab:full_monastic_ownOther_arak}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.251^{*} & 0.514^{*} & 0.104 \\
  & (0.135) & (0.301) & (0.114) \\
  & & & \\
 ln(On-site Land / Arable km²) & -0.757^{**} & -1.269^{***} & 0.092 \\
  & (0.358) & (0.253) & (0.083) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.331^{***} & -0.283 & 0.065 \\
  & (0.118) & (0.234) & (0.120) \\
  & & & \\
 ln(Alms / Arable km²) & 0.291^{*} & 0.463^{***} & -0.144 \\
  & (0.166) & (0.089) & (0.117) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.483^{***} & 0.439^{***} & 0.044 \\
  & (0.107) & (0.154) & (0.123) \\
  & & & \\
 Small House Proximity (20km) & -0.741 & -1.631^{***} & 0.603 \\
  & (0.564) & (0.420) & (0.410) \\
  & & & \\
 Large House Proximity (20km) & 0.437 & 0.375 & 0.603^{**} \\
  & (0.364) & (0.595) & (0.286) \\
  & & & \\
 Friary Presence & 0.480 & 0.467 & -0.749 \\
  & (0.468) & (0.690) & (0.972) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.872^{*} & -0.873 & 0.045 \\
  & (0.477) & (0.593) & (0.408) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.419 & 0.116 & 0.670^{***} \\
  & (0.445) & (0.327) & (0.240) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.229^{*} & 0.302 & 0.386^{***} \\
  & (0.135) & (0.195) & (0.062) \\
  & & & \\
 Wet 1535 Weather Shock & -0.144 & -0.231 & -0.023 \\
  & (0.251) & (0.202) & (0.134) \\
  & & & \\
 Wet 1536 Weather Shock & 0.204 & 0.604^{**} & 0.489^{***} \\
  & (0.177) & (0.279) & (0.125) \\
  & & & \\
 ln(Population) & 0.387^{**} & 0.431^{**} & 0.049 \\
  & (0.161) & (0.190) & (0.069) \\
  & & & \\
 Distance to Scotland & -0.595^{**} & -0.801^{**} & -0.943^{***} \\
  & (0.236) & (0.401) & (0.307) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-152.648} & \multicolumn{1}{c}{-77.246} & \multicolumn{1}{c}{-283.821} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:09:59
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{DAG Results}
  \label{tab:dag}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster} & \multicolumn{1}{c}{primary} & \multicolumn{1}{c}{seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.263^{*} & 0.433^{**} & 0.102 \\
  & (0.144) & (0.200) & (0.092) \\
  & & & \\
 ln(Population) & 0.503^{***} & 0.574^{***} & 0.204^{**} \\
  & (0.120) & (0.161) & (0.103) \\
  & & & \\
 ln(Lay Subsidy per Capita) & -0.169 & -0.333 & -0.044 \\
  & (0.202) & (0.279) & (0.162) \\
  & & & \\
 Constant & -3.642^{***} & -4.600^{***} & -2.735^{***} \\
  & (0.319) & (0.445) & (0.404) \\
  & & & \\
\hline \\[-1.8ex]
Conley SEs (100 km) & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,558} & \multicolumn{1}{c}{1,558} & \multicolumn{1}{c}{1,558} \\
Log Likelihood & \multicolumn{1}{c}{-210.071} & \multicolumn{1}{c}{-113.712} & \multicolumn{1}{c}{-396.992} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

## VIF Analysis for Multicollinearity Detection

In [3]:
cat("\n========== VIF ANALYSIS ==========\n\n")

vif_table <- function(model, model_name) {
  cat(paste0("Model: ", model_name, "\n"))
  cat("-----------------------------------\n")
  vif_values <- vif(model)
  vif_df <- data.frame(Variable = names(vif_values), VIF = round(vif_values, 3))
  vif_df <- vif_df[order(-vif_df$VIF), ]
  print(vif_df)
  cat("\n")
  return(vif_df)
}

cat("=== FULL MONASTIC MODELS (all 9 specs) ===\n\n")
for (spec_name in names(full_models_by_spec)) {
  mods <- full_models_by_spec[[spec_name]]
  vif_table(mods$muster,  paste("Muster -",  spec_name))
  vif_table(mods$primary, paste("Primary -", spec_name))
  vif_table(mods$seat,    paste("Seats -",   spec_name))
}

cat("\n=== DAG MODELS ===\n\n")
vif_table(dag_muster,  "Muster - DAG Model")
vif_table(dag_primary, "Primary - DAG Model")
vif_table(dag_seat,    "Seats - DAG Model")

cat("\n========== VIF SUMMARY & RECOMMENDATIONS ==========\n")
cat("VIF Interpretation:\n")
cat("  VIF < 5:    Low multicollinearity (generally acceptable)\n")
cat("  VIF 5-10:   Moderate multicollinearity (use with caution)\n")
cat("  VIF > 10:   High multicollinearity (problematic)\n\n")

all_vif_results <- list()
for (spec_name in names(full_models_by_spec)) {
  all_vif_results[[paste0("full_muster_",  spec_name)]] <- vif(full_models_by_spec[[spec_name]]$muster)
  all_vif_results[[paste0("full_primary_", spec_name)]] <- vif(full_models_by_spec[[spec_name]]$primary)
  all_vif_results[[paste0("full_seat_",    spec_name)]] <- vif(full_models_by_spec[[spec_name]]$seat)
}

high_vif <- sapply(all_vif_results, function(x) any(x > 10))
if (any(high_vif)) {
  cat("WARNING: High VIF (>10) detected in:\n")
  for (name in names(high_vif)[high_vif]) {
    high_vars <- names(all_vif_results[[name]][all_vif_results[[name]] > 10])
    cat(paste("  -", name, ":", paste(high_vars, collapse = ", "), "\n"))
  }
} else {
  cat("No high VIF (>10) detected. Multicollinearity appears manageable.\n")
}
cat("\n")

========== VIF ANALYSIS ==========

=== FULL MONASTIC MODELS (all 9 specs) ===

Model: Muster - total_raw
-----------------------------------
             Variable   VIF
wet_1536     wet_1536 2.450
mean_slope mean_slope 2.199
wet_1535     wet_1535 2.067
area             area 1.900
distScot     distScot 1.710
bigHouse     bigHouse 1.688
mg_court     mg_court 1.688
mg_fsnub     mg_fsnub 1.668
uplands       uplands 1.540
llandOwned llandOwned 1.531
lowlands     lowlands 1.426
lLStax_pc   lLStax_pc 1.397
lalmsInTot lalmsInTot 1.384
ltitheOutT ltitheOutT 1.381
lpopC           lpopC 1.336
smHouse       smHouse 1.287
friary         friary 1.091

Model: Primary - total_raw
-----------------------------------
             Variable   VIF
mean_slope mean_slope 2.442
wet_1536     wet_1536 2.356
area             area 1.925
wet_1535     wet_1535 1.907
bigHouse     bigHouse 1.866
mg_court     mg_court 1.790
llandOwned llandOwned 1.789
distScot     distScot 1.732
mg_fsnub     mg_fsnub 1.726
uplands       uplands 1.693
lowlands     lowlands 1.608
lalmsInTot lalmsInTot 1.541
smHouse       smHouse 1.521
lLStax_pc   lLStax_pc 1.453
ltitheOutT ltitheOutT 1.444
lpopC           lpopC 1.368
friary         friary 1.112

Model: Seats - total_raw
-----------------------------------
             Variable   VIF
uplands       uplands 2.447
wet_1536     wet_1536 2.399
lowlands     lowlands 2.353
wet_1535     wet_1535 2.078
mean_slope mean_slope 2.014
distScot     distScot 1.719
area             area 1.655
llandOwned llandOwned 1.623
bigHouse     bigHouse 1.582
mg_court     mg_court 1.581
mg_fsnub     mg_fsnub 1.580
lLStax_pc   lLStax_pc 1.489
ltitheOutT ltitheOutT 1.345
lalmsInTot lalmsInTot 1.327
lpopC           lpopC 1.321
friary         friary 1.070
smHouse       smHouse 1.065

Model: Muster - total_sk
-----------------------------------
             Variable   VIF
wet_1536     wet_1536 2.440
mean_slope mean_slope 2.185
wet_1535     wet_1535 2.042
area             area 1.848
distScot     distScot 1.717
bigHouse     bigHouse 1.690
mg_court     mg_court 1.663
mg_fsnub     mg_fsnub 1.645
llo_sk         llo_sk 1.577
uplands       uplands 1.541
lowlands     lowlands 1.440
lLStax_pc   lLStax_pc 1.397
lpopC           lpopC 1.327
smHouse       smHouse 1.280
lal_sk         lal_sk 1.245
lti_sk         lti_sk 1.228
friary         friary 1.095

Model: Primary - total_sk
-----------------------------------
             Variable   VIF
mean_slope mean_slope 2.397
wet_1536     wet_1536 2.334
llo_sk         llo_sk 1.929
area             area 1.894
bigHouse     bigHouse 1.882
wet_1535     wet_1535 1.874
distScot     distScot 1.739
mg_court     mg_court 1.719
uplands       uplands 1.684
mg_fsnub     mg_fsnub 1.671
lowlands     lowlands 1.635
smHouse       smHouse 1.509
lLStax_pc   lLStax_pc 1.453
lpopC           lpopC 1.367
lal_sk         lal_sk 1.361
lti_sk         lti_sk 1.259
friary         friary 1.114

Model: Seats - total_sk
-----------------------------------
             Variable   VIF
uplands       uplands 2.436
wet_1536     wet_1536 2.391
lowlands     lowlands 2.357
wet_1535     wet_1535 2.018
mean_slope mean_slope 2.015
distScot     distScot 1.716
area             area 1.611
bigHouse     bigHouse 1.590
mg_fsnub     mg_fsnub 1.566
llo_sk         llo_sk 1.546
mg_court     mg_court 1.544
lLStax_pc   lLStax_pc 1.478
lpopC           lpopC 1.294
lti_sk         lti_sk 1.262
lal_sk         lal_sk 1.227
friary         friary 1.070
smHouse       smHouse 1.065

Model: Muster - total_arak
-----------------------------------
             Variable   VIF
wet_1536     wet_1536 2.419
mean_slope mean_slope 2.217
wet_1535     wet_1535 2.048
area             area 1.861
mg_court     mg_court 1.728
mg_fsnub     mg_fsnub 1.718
distScot     distScot 1.716
lal_arak     lal_arak 1.712
lni_arak     lni_arak 1.690
bigHouse     bigHouse 1.651
llo_arak     llo_arak 1.561
uplands       uplands 1.522
lowlands     lowlands 1.451
lLStax_pc   lLStax_pc 1.397
lti_arak     lti_arak 1.337
lpopC           lpopC 1.323
smHouse       smHouse 1.299
friary         friary 1.091

Model: Primary - total_arak
-----------------------------------
             Variable   VIF
mean_slope mean_slope 2.489
wet_1536     wet_1536 2.315
lal_arak     lal_arak 2.171
lni_arak     lni_arak 2.157
area             area 1.930
bigHouse     bigHouse 1.852
wet_1535     wet_1535 1.843
mg_court     mg_court 1.786
llo_arak     llo_arak 1.776
mg_fsnub     mg_fsnub 1.750
distScot     distScot 1.708
uplands       uplands 1.642
lowlands     lowlands 1.626
smHouse       smHouse 1.522
lLStax_pc   lLStax_pc 1.460
lti_arak     lti_arak 1.401
lpopC           lpopC 1.364
friary         friary 1.113

Model: Seats - total_arak
-----------------------------------
             Variable   VIF
uplands       uplands 2.433
wet_1536     wet_1536 2.395
lowlands     lowlands 2.347
wet_1535     wet_1535 2.033
mean_slope mean_slope 2.018
distScot     distScot 1.723
area             area 1.608
bigHouse     bigHouse 1.594
mg_fsnub     mg_fsnub 1.580
mg_court     mg_court 1.551
llo_arak     llo_arak 1.519
lal_arak     lal_arak 1.511
lLStax_pc   lLStax_pc 1.477
lni_arak     lni_arak 1.470
lpopC           lpopC 1.285
lti_arak     lti_arak 1.246
friary         friary 1.081
smHouse       smHouse 1.066

Model: Muster - split_raw
-----------------------------------
             Variable   VIF
wet_1536     wet_1536 2.491
mean_slope mean_slope 2.227
wet_1535     wet_1535 2.119
area             area 1.906
distScot     distScot 1.744
mg_court     mg_court 1.696
mg_fsnub     mg_fsnub 1.683
bigHouse     bigHouse 1.680
uplands       uplands 1.575
lbigLand     lbigLand 1.430
lowlands     lowlands 1.420
lLStax_pc   lLStax_pc 1.418
ltitheOutT ltitheOutT 1.405
lalmsInTot lalmsInTot 1.383
lpopC           lpopC 1.351
smHouse       smHouse 1.309
lsmLand       lsmLand 1.276
friary         friary 1.098

Model: Primary - split_raw
-----------------------------------
             Variable   VIF
mean_slope mean_slope 2.436
wet_1536     wet_1536 2.374
wet_1535     wet_1535 1.918
area             area 1.914
bigHouse     bigHouse 1.868
distScot     distScot 1.802
mg_court     mg_court 1.794
mg_fsnub     mg_fsnub 1.741
uplands       uplands 1.739
lbigLand     lbigLand 1.678
lowlands     lowlands 1.627
lalmsInTot lalmsInTot 1.574
smHouse       smHouse 1.523
lLStax_pc   lLStax_pc 1.501
ltitheOutT ltitheOutT 1.465
lpopC           lpopC 1.391
lsmLand       lsmLand 1.318
friary         friary 1.129

Model: Seats - split_raw
-----------------------------------
             Variable   VIF
uplands       uplands 2.516
wet_1536     wet_1536 2.459
lowlands     lowlands 2.335
wet_1535     wet_1535 2.259
mean_slope mean_slope 2.062
distScot     distScot 1.742
area             area 1.650
mg_fsnub     mg_fsnub 1.606
mg_court     mg_court 1.600
bigHouse     bigHouse 1.599
lbigLand     lbigLand 1.538
lLStax_pc   lLStax_pc 1.511
ltitheOutT ltitheOutT 1.409
lsmLand       lsmLand 1.347
lpopC           lpopC 1.324
lalmsInTot lalmsInTot 1.296
friary         friary 1.078
smHouse       smHouse 1.076

Model: Muster - split_sk
-----------------------------------
             Variable   VIF
wet_1536     wet_1536 2.470
mean_slope mean_slope 2.195
wet_1535     wet_1535 2.084
area             area 1.856
distScot     distScot 1.749
bigHouse     bigHouse 1.691
mg_court     mg_court 1.673
mg_fsnub     mg_fsnub 1.655
uplands       uplands 1.563
lbg_sk         lbg_sk 1.461
lowlands     lowlands 1.438
lLStax_pc   lLStax_pc 1.418
lpopC           lpopC 1.334
smHouse       smHouse 1.290
lti_sk         lti_sk 1.244
lal_sk         lal_sk 1.213
lsm_sk         lsm_sk 1.191
friary         friary 1.111

Model: Primary - split_sk
-----------------------------------
             Variable   VIF
mean_slope mean_slope 2.384
wet_1536     wet_1536 2.298
area             area 1.899
bigHouse     bigHouse 1.887
wet_1535     wet_1535 1.830
distScot     distScot 1.804
lbg_sk         lbg_sk 1.800
uplands       uplands 1.723
mg_court     mg_court 1.721
lowlands     lowlands 1.684
mg_fsnub     mg_fsnub 1.666
lLStax_pc   lLStax_pc 1.519
smHouse       smHouse 1.482
lpopC           lpopC 1.393
lal_sk         lal_sk 1.385
lti_sk         lti_sk 1.281
friary         friary 1.155
lsm_sk         lsm_sk 1.140

Model: Seats - split_sk
-----------------------------------
             Variable   VIF
uplands       uplands 2.471
wet_1536     wet_1536 2.438
lowlands     lowlands 2.353
wet_1535     wet_1535 2.122
mean_slope mean_slope 2.048
distScot     distScot 1.731
area             area 1.615
bigHouse     bigHouse 1.606
mg_fsnub     mg_fsnub 1.588
mg_court     mg_court 1.556
lLStax_pc   lLStax_pc 1.485
lbg_sk         lbg_sk 1.444
lti_sk         lti_sk 1.295
lpopC           lpopC 1.286
lsm_sk         lsm_sk 1.251
lal_sk         lal_sk 1.224
friary         friary 1.092
smHouse       smHouse 1.070

Model: Muster - split_arak
-----------------------------------
             Variable   VIF
wet_1536     wet_1536 2.469
mean_slope mean_slope 2.235
wet_1535     wet_1535 2.086
area             area 1.862
mg_court     mg_court 1.739
distScot     distScot 1.739
lal_arak     lal_arak 1.733
mg_fsnub     mg_fsnub 1.728
lni_arak     lni_arak 1.682
bigHouse     bigHouse 1.651
uplands       uplands 1.548
lowlands     lowlands 1.445
lLStax_pc   lLStax_pc 1.418
lbg_arak     lbg_arak 1.414
lti_arak     lti_arak 1.359
lpopC           lpopC 1.324
smHouse       smHouse 1.314
lsm_arak     lsm_arak 1.183
friary         friary 1.096

Model: Primary - split_arak
-----------------------------------
             Variable   VIF
mean_slope mean_slope 2.422
wet_1536     wet_1536 2.336
lal_arak     lal_arak 2.306
lni_arak     lni_arak 2.195
area             area 1.904
bigHouse     bigHouse 1.878
wet_1535     wet_1535 1.847
mg_court     mg_court 1.791
distScot     distScot 1.772
mg_fsnub     mg_fsnub 1.762
lbg_arak     lbg_arak 1.698
uplands       uplands 1.676
lowlands     lowlands 1.661
lti_arak     lti_arak 1.504
smHouse       smHouse 1.504
lLStax_pc   lLStax_pc 1.504
lpopC           lpopC 1.383
lsm_arak     lsm_arak 1.180
friary         friary 1.146

Model: Seats - split_arak
-----------------------------------
             Variable   VIF
uplands       uplands 2.477
wet_1536     wet_1536 2.435
lowlands     lowlands 2.331
wet_1535     wet_1535 2.127
mean_slope mean_slope 2.058
distScot     distScot 1.745
bigHouse     bigHouse 1.605
area             area 1.598
mg_fsnub     mg_fsnub 1.592
mg_court     mg_court 1.558
lal_arak     lal_arak 1.508
lLStax_pc   lLStax_pc 1.497
lni_arak     lni_arak 1.474
lbg_arak     lbg_arak 1.452
lti_arak     lti_arak 1.276
lpopC           lpopC 1.276
lsm_arak     lsm_arak 1.199
friary         friary 1.094
smHouse       smHouse 1.074

Model: Muster - ownOther_raw
-----------------------------------
             Variable   VIF
wet_1536     wet_1536 2.460
mean_slope mean_slope 2.266
wet_1535     wet_1535 2.005
area             area 1.926
lalmsInTot lalmsInTot 1.913
distScot     distScot 1.766
bigHouse     bigHouse 1.712
mg_court     mg_court 1.653
mg_fsnub     mg_fsnub 1.598
uplands       uplands 1.545
ltitheOutT ltitheOutT 1.530
lowlands     lowlands 1.468
lotherLand lotherLand 1.453
lownLand     lownLand 1.435
lLStax_pc   lLStax_pc 1.406
lpopC           lpopC 1.353
smHouse       smHouse 1.287
friary         friary 1.102

Model: Primary - ownOther_raw
-----------------------------------
             Variable   VIF
mean_slope mean_slope 2.615
wet_1536     wet_1536 2.453
lalmsInTot lalmsInTot 2.254
area             area 2.202
bigHouse     bigHouse 1.948
wet_1535     wet_1535 1.843
distScot     distScot 1.834
ltitheOutT ltitheOutT 1.816
mg_court     mg_court 1.721
uplands       uplands 1.720
lowlands     lowlands 1.684
lotherLand lotherLand 1.678
lownLand     lownLand 1.639
mg_fsnub     mg_fsnub 1.602
smHouse       smHouse 1.552
lLStax_pc   lLStax_pc 1.507
lpopC           lpopC 1.441
friary         friary 1.133

Model: Seats - ownOther_raw
-----------------------------------
             Variable   VIF
uplands       uplands 2.446
wet_1536     wet_1536 2.399
lowlands     lowlands 2.372
wet_1535     wet_1535 2.067
lalmsInTot lalmsInTot 2.041
mean_slope mean_slope 2.013
lownLand     lownLand 1.852
distScot     distScot 1.713
area             area 1.686
mg_fsnub     mg_fsnub 1.589
mg_court     mg_court 1.589
bigHouse     bigHouse 1.578
lotherLand lotherLand 1.572
lLStax_pc   lLStax_pc 1.484
ltitheOutT ltitheOutT 1.357
lpopC           lpopC 1.323
friary         friary 1.067
smHouse       smHouse 1.065

Model: Muster - ownOther_sk
-----------------------------------
             Variable   VIF
wet_1536     wet_1536 2.493
mean_slope mean_slope 2.244
wet_1535     wet_1535 2.047
area             area 1.823
distScot     distScot 1.775
bigHouse     bigHouse 1.721
mg_court     mg_court 1.643
lal_sk         lal_sk 1.606
mg_fsnub     mg_fsnub 1.599
uplands       uplands 1.549
lowlands     lowlands 1.481
loth_sk       loth_sk 1.463
lLStax_pc   lLStax_pc 1.414
lown_sk       lown_sk 1.361
lpopC           lpopC 1.324
lti_sk         lti_sk 1.323
smHouse       smHouse 1.288
friary         friary 1.107

Model: Primary - ownOther_sk
-----------------------------------
             Variable   VIF
mean_slope mean_slope 2.538
wet_1536     wet_1536 2.488
area             area 2.013
bigHouse     bigHouse 1.988
wet_1535     wet_1535 1.924
distScot     distScot 1.866
loth_sk       loth_sk 1.757
uplands       uplands 1.712
mg_court     mg_court 1.704
lowlands     lowlands 1.698
lal_sk         lal_sk 1.619
mg_fsnub     mg_fsnub 1.614
smHouse       smHouse 1.558
lLStax_pc   lLStax_pc 1.525
lti_sk         lti_sk 1.468
lpopC           lpopC 1.410
lown_sk       lown_sk 1.368
friary         friary 1.139

Model: Seats - ownOther_sk
-----------------------------------
             Variable   VIF
uplands       uplands 2.444
wet_1536     wet_1536 2.390
lowlands     lowlands 2.355
mean_slope mean_slope 2.023
wet_1535     wet_1535 2.006
lal_sk         lal_sk 1.835
lown_sk       lown_sk 1.753
distScot     distScot 1.711
area             area 1.628
mg_fsnub     mg_fsnub 1.586
bigHouse     bigHouse 1.577
mg_court     mg_court 1.562
lLStax_pc   lLStax_pc 1.485
loth_sk       loth_sk 1.484
lti_sk         lti_sk 1.282
lpopC           lpopC 1.275
friary         friary 1.067
smHouse       smHouse 1.066

Model: Muster - ownOther_arak
-----------------------------------
             Variable   VIF
wet_1536     wet_1536 2.425
mean_slope mean_slope 2.354
wet_1535     wet_1535 1.997
area             area 1.851
distScot     distScot 1.783
lal_arak     lal_arak 1.731
mg_court     mg_court 1.709
bigHouse     bigHouse 1.700
mg_fsnub     mg_fsnub 1.675
uplands       uplands 1.536
lowlands     lowlands 1.497
lni_arak     lni_arak 1.492
lLStax_pc   lLStax_pc 1.409
loth_arak   loth_arak 1.374
lpopC           lpopC 1.349
smHouse       smHouse 1.312
lti_arak     lti_arak 1.308
lown_arak   lown_arak 1.252
friary         friary 1.100

Model: Primary - ownOther_arak
-----------------------------------
             Variable   VIF
mean_slope mean_slope 2.710
wet_1536     wet_1536 2.422
lal_arak     lal_arak 2.099
area             area 2.067
bigHouse     bigHouse 1.982
distScot     distScot 1.822
wet_1535     wet_1535 1.821
mg_court     mg_court 1.753
lni_arak     lni_arak 1.714
mg_fsnub     mg_fsnub 1.686
lowlands     lowlands 1.686
uplands       uplands 1.672
smHouse       smHouse 1.576
loth_arak   loth_arak 1.543
lLStax_pc   lLStax_pc 1.511
lpopC           lpopC 1.440
lti_arak     lti_arak 1.392
lown_arak   lown_arak 1.343
friary         friary 1.142

Model: Seats - ownOther_arak
-----------------------------------
             Variable   VIF
uplands       uplands 2.445
wet_1536     wet_1536 2.397
lowlands     lowlands 2.350
lown_arak   lown_arak 2.292
wet_1535     wet_1535 2.037
lni_arak     lni_arak 2.035
mean_slope mean_slope 2.014
lal_arak     lal_arak 1.755
distScot     distScot 1.719
area             area 1.620
mg_fsnub     mg_fsnub 1.607
bigHouse     bigHouse 1.586
mg_court     mg_court 1.553
lLStax_pc   lLStax_pc 1.486
loth_arak   loth_arak 1.467
lpopC           lpopC 1.274
lti_arak     lti_arak 1.257
friary         friary 1.081
smHouse       smHouse 1.066

=== DAG MODELS ===

Model: Muster - DAG Model
-----------------------------------
           Variable   VIF
lLStax_pc lLStax_pc 1.049
llo_arak   llo_arak 1.037
lpopC         lpopC 1.024

          Variable  VIF
lLStax_pc lLStax_pc 1.049
llo_arak  llo_arak  1.037
lpopC     lpopC     1.024

Model: Primary - DAG Model
-----------------------------------
           Variable   VIF
lLStax_pc lLStax_pc 1.042
llo_arak   llo_arak 1.029
lpopC         lpopC 1.016

          Variable  VIF
lLStax_pc lLStax_pc 1.042
llo_arak  llo_arak  1.029
lpopC     lpopC     1.016

Model: Seats - DAG Model
-----------------------------------
           Variable   VIF
lLStax_pc lLStax_pc 1.041
llo_arak   llo_arak 1.035
lpopC         lpopC 1.024

          Variable  VIF
lLStax_pc lLStax_pc 1.041
llo_arak  llo_arak  1.035
lpopC     lpopC     1.024

========== VIF SUMMARY & RECOMMENDATIONS ==========

VIF Interpretation:

  VIF < 5:    Low multicollinearity (generally acceptable)

  VIF 5-10:   Moderate multicollinearity (use with caution)

  VIF > 10:   High multicollinearity (problematic)

No high VIF (>10) detected. Multicollinearity appears manageable.

## Section 2: Distance-Weighted Interaction Models (Robustness)

Spatially-weighted monastic variables (raw, per-capita, per-sq-km)

In [4]:
# Standardize distance-weighted variables
dw_vars_all <- c(
  "llo_dw",   "lsl_dw",   "lbl_dw",   "lti_dw",
  "llo_dwpc", "lsl_dwpc", "lbl_dwpc", "lti_dwpc",
  "llo_dwsk", "lsl_dwsk", "lbl_dwsk", "lti_dwsk"
)
for (v in dw_vars_all) {
  pdf[[v]] <- scale(pdf[[v]], center = TRUE, scale = TRUE)[, 1]
}
pdf$Y_COORD <- scale(pdf$Y_COORD, center = TRUE, scale = TRUE)[, 1]

controls_dw <- c(
  "mg_fsnub", "mg_court",
  "lLStax_pc", "wet_1535", "wet_1536", "lpopC",
  "Y_COORD", "uplands", "lowlands", "area", "mean_slope", "distScot"
)
hide_vars_dw <- c("Constant", "Y_COORD", "uplands", "lowlands", "area", "mean_slope")

run_models_dw <- function(monastic_vars, pdf, controls) {
  muster_list  <- list()
  primary_list <- list()
  seat_list    <- list()
  for (var in monastic_vars) {
    f_base <- paste(controls, collapse = " + ")
    muster_list[[var]]  <- glm(paste("muster ~",  var, "+", f_base), data = pdf,
                                family = binomial(link = "logit"))
    primary_list[[var]] <- glm(paste("primary ~", var, "+", f_base), data = pdf,
                                family = binomial(link = "logit"))
    seat_list[[var]]    <- glm(paste("seats ~",   var, "+", f_base), data = pdf,
                                family = "poisson")
  }
  list(muster = muster_list, primary = primary_list, seat = seat_list)
}

# Helper: Conley SEs for a list of GLM models
conley_list_se <- function(model_list, family_lab, cutoff_km = 100) {
  lapply(model_list, function(m) conley_glm_se(m, family_lab, cutoff_km))
}

# --- Set 1: Raw distance-weighted ---
dw_raw <- c("llo_dw", "lsl_dw", "lbl_dw", "lti_dw")
res_raw <- run_models_dw(dw_raw, pdf, controls_dw)

raw_labels <- unlist(pretty_dict[c(dw_raw, "mg_fsnub", "mg_court",
                                   "lLStax_pc", "wet_1535", "wet_1536", "lpopC", "distScot")])

stargazer(res_raw$muster,
  type = "latex", title = "Muster: Raw Distance-Weighted Monastic Variables",
  label = "tab:muster_dw_raw",
  se = conley_list_se(res_raw$muster, "logit"),
  omit = hide_vars_dw, covariate.labels = raw_labels,
  add.lines = list(c("Geographic Controls", "Y", "Y", "Y", "Y"),
                   c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
  align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"), table.placement = "H",
  out = "Output/Tables/muster_dw_raw.tex"
)
stargazer(res_raw$primary,
  type = "latex", title = "Primary: Raw Distance-Weighted Monastic Variables",
  label = "tab:primary_dw_raw",
  se = conley_list_se(res_raw$primary, "logit"),
  omit = hide_vars_dw, covariate.labels = raw_labels,
  add.lines = list(c("Geographic Controls", "Y", "Y", "Y", "Y"),
                   c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
  align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"), table.placement = "H",
  out = "Output/Tables/primary_dw_raw.tex"
)
stargazer(res_raw$seat,
  type = "latex", title = "Seats: Raw Distance-Weighted Monastic Variables",
  label = "tab:seat_dw_raw",
  se = conley_list_se(res_raw$seat, "poisson"),
  omit = hide_vars_dw, covariate.labels = raw_labels,
  add.lines = list(c("Geographic Controls", "Y", "Y", "Y", "Y"),
                   c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
  align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"), table.placement = "H",
  out = "Output/Tables/seat_dw_raw.tex"
)

# --- Set 2: Per capita distance-weighted ---
dw_pc <- c("llo_dwpc", "lsl_dwpc", "lbl_dwpc", "lti_dwpc")
res_pc <- run_models_dw(dw_pc, pdf, controls_dw)

pc_labels <- unlist(pretty_dict[c(dw_pc, "mg_fsnub", "mg_court",
                                  "lLStax_pc", "wet_1535", "wet_1536", "lpopC", "distScot")])

stargazer(res_pc$muster,
  type = "latex", title = "Muster: Per Capita Distance-Weighted Monastic Variables",
  label = "tab:muster_dw_pc",
  se = conley_list_se(res_pc$muster, "logit"),
  omit = hide_vars_dw, covariate.labels = pc_labels,
  add.lines = list(c("Geographic Controls", "Y", "Y", "Y", "Y"),
                   c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
  align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"), table.placement = "H",
  out = "Output/Tables/muster_dw_pc.tex"
)
stargazer(res_pc$primary,
  type = "latex", title = "Primary: Per Capita Distance-Weighted Monastic Variables",
  label = "tab:primary_dw_pc",
  se = conley_list_se(res_pc$primary, "logit"),
  omit = hide_vars_dw, covariate.labels = pc_labels,
  add.lines = list(c("Geographic Controls", "Y", "Y", "Y", "Y"),
                   c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
  align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"), table.placement = "H",
  out = "Output/Tables/primary_dw_pc.tex"
)
stargazer(res_pc$seat,
  type = "latex", title = "Seats: Per Capita Distance-Weighted Monastic Variables",
  label = "tab:seat_dw_pc",
  se = conley_list_se(res_pc$seat, "poisson"),
  omit = hide_vars_dw, covariate.labels = pc_labels,
  add.lines = list(c("Geographic Controls", "Y", "Y", "Y", "Y"),
                   c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
  align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"), table.placement = "H",
  out = "Output/Tables/seat_dw_pc.tex"
)

# --- Set 3: Per sq km distance-weighted ---
dw_sk <- c("llo_dwsk", "lsl_dwsk", "lbl_dwsk", "lti_dwsk")
res_sk <- run_models_dw(dw_sk, pdf, controls_dw)

sk_labels <- unlist(pretty_dict[c(dw_sk, "mg_fsnub", "mg_court",
                                  "lLStax_pc", "wet_1535", "wet_1536", "lpopC", "distScot")])

stargazer(res_sk$muster,
  type = "latex", title = "Muster: Per Sq Km Distance-Weighted Monastic Variables",
  label = "tab:muster_dw_sk",
  se = conley_list_se(res_sk$muster, "logit"),
  omit = hide_vars_dw, covariate.labels = sk_labels,
  add.lines = list(c("Geographic Controls", "Y", "Y", "Y", "Y"),
                   c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
  align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"), table.placement = "H",
  out = "Output/Tables/muster_dw_sk.tex"
)
stargazer(res_sk$primary,
  type = "latex", title = "Primary: Per Sq Km Distance-Weighted Monastic Variables",
  label = "tab:primary_dw_sk",
  se = conley_list_se(res_sk$primary, "logit"),
  omit = hide_vars_dw, covariate.labels = sk_labels,
  add.lines = list(c("Geographic Controls", "Y", "Y", "Y", "Y"),
                   c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
  align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"), table.placement = "H",
  out = "Output/Tables/primary_dw_sk.tex"
)
stargazer(res_sk$seat,
  type = "latex", title = "Seats: Per Sq Km Distance-Weighted Monastic Variables",
  label = "tab:seat_dw_sk",
  se = conley_list_se(res_sk$seat, "poisson"),
  omit = hide_vars_dw, covariate.labels = sk_labels,
  add.lines = list(c("Geographic Controls", "Y", "Y", "Y", "Y"),
                   c("Conley SEs (100 km)", "Y", "Y", "Y", "Y")),
  align = TRUE, column.sep.width = ".5pt", omit.stat = c("aic"), table.placement = "H",
  out = "Output/Tables/seat_dw_sk.tex"
)

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:01
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster: Raw Distance-Weighted Monastic Variables}
  \label{tab:muster_dw_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Distance-Weighted Land Owned) & 0.213^{**} &  &  &  \\
  & (0.083) &  &  &  \\
  & & & & \\
 ln(Distance-Weighted Small House Land) &  & -0.018 &  &  \\
  &  & (0.109) &  &  \\
  & & & & \\
 ln(Distance-Weighted Big House Land) &  &  & 0.208^{**} &  \\
  &  &  & (0.082) &  \\
  & & & & \\
 ln(Distance-Weighted Tithe) &  &  &  & 0.098 \\
  &  &  &  & (0.074) \\
  & & & & \\
 Snubbed Family Proximity (20 km) & -0.577 & -0.436 & -0.583 & -0.469 \\
  & (0.403) & (0.421) & (0.397) & (0.410) \\
  & & & & \\
 Court Officer Proximity (20 km) & 0.121 & 0.133 & 0.123 & 0.136 \\
  & (0.446) & (0.431) & (0.444) & (0.433) \\
  & & & & \\
 ln(Lay Subsidy per Capita) & 0.203 & 0.210^{*} & 0.214 & 0.201 \\
  & (0.132) & (0.128) & (0.132) & (0.129) \\
  & & & & \\
 Wet 1535 Weather Shock & -0.074 & 0.001 & -0.062 & 0.001 \\
  & (0.222) & (0.227) & (0.219) & (0.223) \\
  & & & & \\
 Wet 1536 Weather Shock & 0.133 & 0.117 & 0.124 & 0.119 \\
  & (0.169) & (0.166) & (0.170) & (0.164) \\
  & & & & \\
 ln(Population) & 0.339^{**} & 0.364^{**} & 0.343^{**} & 0.362^{**} \\
  & (0.169) & (0.165) & (0.172) & (0.165) \\
  & & & & \\
 Distance to Scotland & -2.317^{*} & -2.316^{*} & -2.347^{*} & -2.267^{*} \\
  & (1.201) & (1.189) & (1.204) & (1.188) \\
  & & & & \\
\hline \\[-1.8ex]
Geographic Controls & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-161.047} & \multicolumn{1}{c}{-163.490} & \multicolumn{1}{c}{-160.948} & \multicolumn{1}{c}{-163.205} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:02
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary: Raw Distance-Weighted Monastic Variables}
  \label{tab:primary_dw_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Distance-Weighted Land Owned) & 0.227^{***} &  &  &  \\
  & (0.086) &  &  &  \\
  & & & & \\
 ln(Distance-Weighted Small House Land) &  & -0.963^{*} &  &  \\
  &  & (0.533) &  &  \\
  & & & & \\
 ln(Distance-Weighted Big House Land) &  &  & 0.239^{***} &  \\
  &  &  & (0.086) &  \\
  & & & & \\
 ln(Distance-Weighted Tithe) &  &  &  & 0.222^{***} \\
  &  &  &  & (0.084) \\
  & & & & \\
 Snubbed Family Proximity (20 km) & -0.502 & -0.315 & -0.529 & -0.379 \\
  & (0.595) & (0.557) & (0.593) & (0.603) \\
  & & & & \\
 Court Officer Proximity (20 km) & -0.387 & -0.338 & -0.394 & -0.348 \\
  & (0.422) & (0.355) & (0.413) & (0.420) \\
  & & & & \\
 ln(Lay Subsidy per Capita) & 0.202 & 0.268 & 0.220 & 0.169 \\
  & (0.201) & (0.197) & (0.194) & (0.209) \\
  & & & & \\
 Wet 1535 Weather Shock & -0.130 & 0.071 & -0.128 & -0.009 \\
  & (0.160) & (0.179) & (0.157) & (0.163) \\
  & & & & \\
 Wet 1536 Weather Shock & 0.543^{*} & 0.463^{*} & 0.539^{*} & 0.535^{**} \\
  & (0.279) & (0.282) & (0.285) & (0.263) \\
  & & & & \\
 ln(Population) & 0.392^{*} & 0.426^{*} & 0.391^{*} & 0.430^{**} \\
  & (0.206) & (0.219) & (0.211) & (0.190) \\
  & & & & \\
 Distance to Scotland & -4.617^{***} & -4.853^{***} & -4.726^{***} & -4.483^{***} \\
  & (1.745) & (1.715) & (1.762) & (1.675) \\
  & & & & \\
\hline \\[-1.8ex]
Geographic Controls & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-83.507} & \multicolumn{1}{c}{-83.490} & \multicolumn{1}{c}{-83.028} & \multicolumn{1}{c}{-84.324} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:03
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats: Raw Distance-Weighted Monastic Variables}
  \label{tab:seat_dw_raw}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 ln(Distance-Weighted Land Owned) & 0.085^{**} &  &  &  \\
  & (0.038) &  &  &  \\
  & & & & \\
 ln(Distance-Weighted Small House Land) &  & 0.175^{***} &  &  \\
  &  & (0.033) &  &  \\
  & & & & \\
 ln(Distance-Weighted Big House Land) &  &  & 0.050 &  \\
  &  &  & (0.034) &  \\
  & & & & \\
 ln(Distance-Weighted Tithe) &  &  &  & 0.136^{**} \\
  &  &  &  & (0.057) \\
  & & & & \\
 Snubbed Family Proximity (20 km) & 0.304 & 0.380 & 0.329 & 0.324 \\
  & (0.305) & (0.305) & (0.308) & (0.313) \\
  & & & & \\
 Court Officer Proximity (20 km) & 0.201 & 0.208 & 0.201 & 0.213 \\
  & (0.248) & (0.259) & (0.246) & (0.245) \\
  & & & & \\
 ln(Lay Subsidy per Capita) & 0.364^{***} & 0.341^{***} & 0.364^{***} & 0.357^{***} \\
  & (0.060) & (0.064) & (0.059) & (0.064) \\
  & & & & \\
 Wet 1535 Weather Shock & -0.008 & -0.020 & 0.008 & 0.037 \\
  & (0.116) & (0.122) & (0.116) & (0.120) \\
  & & & & \\
 Wet 1536 Weather Shock & 0.510^{***} & 0.517^{***} & 0.505^{***} & 0.499^{***} \\
  & (0.106) & (0.104) & (0.108) & (0.107) \\
  & & & & \\
 ln(Population) & -0.033 & -0.017 & -0.023 & -0.011 \\
  & (0.079) & (0.080) & (0.077) & (0.081) \\
  & & & & \\
 Distance to Scotland & -4.569^{***} & -4.447^{***} & -4.620^{***} & -4.580^{***} \\
  & (1.486) & (1.497) & (1.498) & (1.473) \\
  & & & & \\
\hline \\[-1.8ex]
Geographic Controls & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-276.234} & \multicolumn{1}{c}{-273.735} & \multicolumn{1}{c}{-276.871} & \multicolumn{1}{c}{-275.281} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"glm.fit: fitted probabilities numerically 0 or 1 occurred"

Warning message:
"glm.fit: fitted probabilities numerically 0 or 1 occurred"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:04
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster: Per Capita Distance-Weighted Monastic Variables}
  \label{tab:muster_dw_pc}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 Snubbed Family Proximity (20 km) & 0.515^{*} &  &  &  \\
  & (0.298) &  &  &  \\
  & & & & \\
 Court Officer Proximity (20 km) &  & 0.488^{**} &  &  \\
  &  & (0.221) &  &  \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.414^{*} &  \\
  &  &  & (0.244) &  \\
  & & & & \\
 Wet 1535 Weather Shock &  &  &  & -38.895^{**} \\
  &  &  &  & (19.168) \\
  & & & & \\
 Wet 1536 Weather Shock & -0.904 & -0.979 & -0.902 & -0.514 \\
  & (0.834) & (0.866) & (0.825) & (0.904) \\
  & & & & \\
 ln(Population) & 1.677^{**} & 1.769^{***} & 1.694^{**} & 1.865^{**} \\
  & (0.711) & (0.665) & (0.731) & (0.784) \\
  & & & & \\
 Distance to Scotland & 1.287^{***} & 1.092^{***} & 1.274^{***} & 1.280^{***} \\
  & (0.378) & (0.369) & (0.367) & (0.383) \\
  & & & & \\
 wet\_1535 & -0.939^{*} & -0.753 & -0.851^{*} & -0.664 \\
  & (0.491) & (0.557) & (0.471) & (0.458) \\
  & & & & \\
 wet\_1536 & 0.900^{***} & 0.877^{***} & 0.828^{***} & 0.685^{***} \\
  & (0.288) & (0.298) & (0.265) & (0.188) \\
  & & & & \\
 lpopC & 2.202^{***} & 2.075^{***} & 1.972^{***} & 1.759^{**} \\
  & (0.658) & (0.639) & (0.618) & (0.741) \\
  & & & & \\
 distScot & -1.620 & -0.795 & -1.370 & -0.767 \\
  & (3.626) & (3.052) & (3.614) & (3.608) \\
  & & & & \\
\hline \\[-1.8ex]
Geographic Controls & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{123} & \multicolumn{1}{c}{123} & \multicolumn{1}{c}{123} & \multicolumn{1}{c}{123} \\
Log Likelihood & \multicolumn{1}{c}{-25.902} & \multicolumn{1}{c}{-26.743} & \multicolumn{1}{c}{-26.366} & \multicolumn{1}{c}{-25.170} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:05
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary: Per Capita Distance-Weighted Monastic Variables}
  \label{tab:primary_dw_pc}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 Snubbed Family Proximity (20 km) & 0.598^{**} &  &  &  \\
  & (0.243) &  &  &  \\
  & & & & \\
 Court Officer Proximity (20 km) &  & -2.314 &  &  \\
  &  & (1.956) &  &  \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 0.604^{**} &  \\
  &  &  & (0.247) &  \\
  & & & & \\
 Wet 1535 Weather Shock &  &  &  & -17.683 \\
  &  &  &  & (15.795) \\
  & & & & \\
 Wet 1536 Weather Shock & -1.057 & -0.716 & -1.020 & -0.444 \\
  & (0.992) & (0.985) & (0.966) & (1.165) \\
  & & & & \\
 ln(Population) & 0.991 & 1.213 & 0.988 & 1.004^{*} \\
  & (0.667) & (0.785) & (0.626) & (0.567) \\
  & & & & \\
 Distance to Scotland & 0.093 & 0.718 & 0.154 & 0.151 \\
  & (0.491) & (0.603) & (0.480) & (0.507) \\
  & & & & \\
 wet\_1535 & -0.734^{*} & -0.296 & -0.734^{*} & -0.565 \\
  & (0.423) & (0.565) & (0.423) & (0.383) \\
  & & & & \\
 wet\_1536 & 0.410^{*} & 0.432^{**} & 0.391 & 0.406^{*} \\
  & (0.237) & (0.187) & (0.240) & (0.226) \\
  & & & & \\
 lpopC & 1.653^{***} & 1.379^{***} & 1.632^{***} & 1.455^{***} \\
  & (0.471) & (0.469) & (0.485) & (0.495) \\
  & & & & \\
 distScot & -12.585^{**} & -8.308^{**} & -13.362^{**} & -8.281^{**} \\
  & (5.109) & (3.682) & (5.399) & (3.462) \\
  & & & & \\
\hline \\[-1.8ex]
Geographic Controls & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{123} & \multicolumn{1}{c}{123} & \multicolumn{1}{c}{123} & \multicolumn{1}{c}{123} \\
Log Likelihood & \multicolumn{1}{c}{-18.190} & \multicolumn{1}{c}{-18.557} & \multicolumn{1}{c}{-18.021} & \multicolumn{1}{c}{-18.485} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:06
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats: Per Capita Distance-Weighted Monastic Variables}
  \label{tab:seat_dw_pc}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 Snubbed Family Proximity (20 km) & 0.00002 &  &  &  \\
  & (0.186) &  &  &  \\
  & & & & \\
 Court Officer Proximity (20 km) &  & 0.240 &  &  \\
  &  & (0.162) &  &  \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & -0.174 &  \\
  &  &  & (0.220) &  \\
  & & & & \\
 Wet 1535 Weather Shock &  &  &  & 0.247^{**} \\
  &  &  &  & (0.117) \\
  & & & & \\
 Wet 1536 Weather Shock & 1.584^{***} & 1.608^{***} & 1.654^{***} & 1.511^{**} \\
  & (0.611) & (0.599) & (0.604) & (0.632) \\
  & & & & \\
 ln(Population) & -0.437 & -0.683 & -0.416 & -0.846 \\
  & (0.519) & (0.594) & (0.515) & (0.629) \\
  & & & & \\
 Distance to Scotland & 0.384 & 0.380 & 0.394 & 0.451 \\
  & (0.518) & (0.504) & (0.530) & (0.526) \\
  & & & & \\
 wet\_1535 & -0.152 & -0.197 & -0.130 & -0.154 \\
  & (0.253) & (0.232) & (0.248) & (0.225) \\
  & & & & \\
 wet\_1536 & 0.629^{**} & 0.768^{**} & 0.616^{**} & 0.818^{**} \\
  & (0.273) & (0.310) & (0.245) & (0.331) \\
  & & & & \\
 lpopC & -0.685 & -0.523 & -0.715 & -0.258 \\
  & (1.042) & (1.090) & (1.033) & (1.051) \\
  & & & & \\
 distScot & -9.893^{***} & -9.857^{***} & -10.066^{***} & -9.764^{***} \\
  & (3.453) & (3.135) & (3.574) & (3.020) \\
  & & & & \\
\hline \\[-1.8ex]
Geographic Controls & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{123} & \multicolumn{1}{c}{123} & \multicolumn{1}{c}{123} & \multicolumn{1}{c}{123} \\
Log Likelihood & \multicolumn{1}{c}{-29.713} & \multicolumn{1}{c}{-29.497} & \multicolumn{1}{c}{-29.661} & \multicolumn{1}{c}{-29.161} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"glm.fit: fitted probabilities numerically 0 or 1 occurred"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:07
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Muster: Per Sq Km Distance-Weighted Monastic Variables}
  \label{tab:muster_dw_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{muster \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 Snubbed Family Proximity (20 km) & 2.135 &  &  &  \\
  & (1.807) &  &  &  \\
  & & & & \\
 Court Officer Proximity (20 km) &  & 0.829 &  &  \\
  &  & (0.701) &  &  \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 1.664 &  \\
  &  &  & (1.476) &  \\
  & & & & \\
 Wet 1535 Weather Shock &  &  &  & -0.432 \\
  &  &  &  & (0.266) \\
  & & & & \\
 Wet 1536 Weather Shock & -0.453 & -0.437 & -0.452 & -0.415 \\
  & (0.422) & (0.424) & (0.420) & (0.423) \\
  & & & & \\
 ln(Population) & 0.148 & 0.127 & 0.151 & 0.119 \\
  & (0.444) & (0.431) & (0.448) & (0.436) \\
  & & & & \\
 Distance to Scotland & 0.207 & 0.202 & 0.210 & 0.215^{*} \\
  & (0.127) & (0.126) & (0.128) & (0.130) \\
  & & & & \\
 wet\_1535 & -0.010 & -0.010 & -0.004 & -0.008 \\
  & (0.227) & (0.222) & (0.225) & (0.212) \\
  & & & & \\
 wet\_1536 & 0.116 & 0.122 & 0.115 & 0.124 \\
  & (0.161) & (0.160) & (0.161) & (0.159) \\
  & & & & \\
 lpopC & 0.364^{**} & 0.360^{**} & 0.365^{**} & 0.362^{**} \\
  & (0.168) & (0.167) & (0.170) & (0.170) \\
  & & & & \\
 distScot & -2.321^{*} & -2.305^{*} & -2.321^{*} & -2.344^{*} \\
  & (1.199) & (1.196) & (1.200) & (1.202) \\
  & & & & \\
\hline \\[-1.8ex]
Geographic Controls & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-163.198} & \multicolumn{1}{c}{-163.424} & \multicolumn{1}{c}{-163.262} & \multicolumn{1}{c}{-163.131} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:08
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Primary: Per Sq Km Distance-Weighted Monastic Variables}
  \label{tab:primary_dw_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{primary \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 Snubbed Family Proximity (20 km) & 1.736 &  &  &  \\
  & (2.264) &  &  &  \\
  & & & & \\
 Court Officer Proximity (20 km) &  & -37.233 &  &  \\
  &  & (28.737) &  &  \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & 2.234 &  \\
  &  &  & (1.516) &  \\
  & & & & \\
 Wet 1535 Weather Shock &  &  &  & -0.548 \\
  &  &  &  & (0.447) \\
  & & & & \\
 Wet 1536 Weather Shock & -0.288 & -0.338 & -0.298 & -0.239 \\
  & (0.597) & (0.564) & (0.597) & (0.599) \\
  & & & & \\
 ln(Population) & -0.344 & -0.322 & -0.328 & -0.377 \\
  & (0.428) & (0.378) & (0.432) & (0.432) \\
  & & & & \\
 Distance to Scotland & 0.195 & 0.264 & 0.204 & 0.214 \\
  & (0.200) & (0.200) & (0.196) & (0.208) \\
  & & & & \\
 wet\_1535 & -0.037 & 0.038 & -0.034 & -0.040 \\
  & (0.159) & (0.166) & (0.159) & (0.155) \\
  & & & & \\
 wet\_1536 & 0.532^{**} & 0.506^{*} & 0.530^{**} & 0.536^{**} \\
  & (0.256) & (0.260) & (0.254) & (0.267) \\
  & & & & \\
 lpopC & 0.419^{**} & 0.432^{**} & 0.423^{**} & 0.413^{**} \\
  & (0.204) & (0.213) & (0.206) & (0.206) \\
  & & & & \\
 distScot & -4.486^{***} & -4.655^{***} & -4.488^{***} & -4.571^{***} \\
  & (1.733) & (1.735) & (1.727) & (1.761) \\
  & & & & \\
\hline \\[-1.8ex]
Geographic Controls & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-85.472} & \multicolumn{1}{c}{-84.092} & \multicolumn{1}{c}{-85.300} & \multicolumn{1}{c}{-85.320} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:10
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Seats: Per Sq Km Distance-Weighted Monastic Variables}
  \label{tab:seat_dw_sk}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{4}{c}{\textit{Dependent variable:}} \\
\cline{2-5}
\\[-1.8ex] & \multicolumn{4}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)} & \multicolumn{1}{c}{(4)}\\
\hline \\[-1.8ex]
 Snubbed Family Proximity (20 km) & -0.096 &  &  &  \\
  & (1.131) &  &  &  \\
  & & & & \\
 Court Officer Proximity (20 km) &  & 0.942 &  &  \\
  &  & (0.738) &  &  \\
  & & & & \\
 ln(Lay Subsidy per Capita) &  &  & -1.294 &  \\
  &  &  & (1.117) &  \\
  & & & & \\
 Wet 1535 Weather Shock &  &  &  & -0.029 \\
  &  &  &  & (0.185) \\
  & & & & \\
 Wet 1536 Weather Shock & 0.366 & 0.370 & 0.380 & 0.367 \\
  & (0.294) & (0.299) & (0.294) & (0.303) \\
  & & & & \\
 ln(Population) & 0.200 & 0.194 & 0.187 & 0.197 \\
  & (0.244) & (0.249) & (0.242) & (0.248) \\
  & & & & \\
 Distance to Scotland & 0.362^{***} & 0.357^{***} & 0.363^{***} & 0.363^{***} \\
  & (0.058) & (0.059) & (0.058) & (0.060) \\
  & & & & \\
 wet\_1535 & 0.021 & 0.013 & 0.020 & 0.019 \\
  & (0.119) & (0.120) & (0.117) & (0.122) \\
  & & & & \\
 wet\_1536 & 0.502^{***} & 0.504^{***} & 0.506^{***} & 0.504^{***} \\
  & (0.109) & (0.110) & (0.110) & (0.113) \\
  & & & & \\
 lpopC & -0.011 & -0.015 & -0.010 & -0.011 \\
  & (0.077) & (0.078) & (0.077) & (0.077) \\
  & & & & \\
 distScot & -4.676^{***} & -4.666^{***} & -4.707^{***} & -4.685^{***} \\
  & (1.511) & (1.513) & (1.516) & (1.512) \\
  & & & & \\
\hline \\[-1.8ex]
Geographic Controls & Y & Y & Y & Y \\
Conley SEs (100 km) & Y & Y & Y & Y \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-277.190} & \multicolumn{1}{c}{-276.856} & \multicolumn{1}{c}{-277.034} & \multicolumn{1}{c}{-277.183} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{4}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

## Section 3: Conley (Spatial HAC) Standard Errors — Robustness

Re-estimate the full monastic models (`total` spec) and the joint elite model
using Conley spatial HAC standard errors. Inter-parish distances are computed
on centroids of `northParishFlows.shp` (EPSG:27700, BNG meters; converted to km).
We report SEs at three cutoff distances — **50, 100, 150 km** — using a
Bartlett kernel. The original GLM SEs are reported alongside for comparison.

In [5]:
# Conley (spatial HAC) standard errors via the `conleyreg` package.
# For each of the 9 monastic specs, re-estimate the full joint model using
# Conley SEs at multiple distance cutoffs and write one .tex per spec/cutoff.

pacman::p_load(conleyreg)

# Parish centroids in BNG (EPSG:27700) — conleyreg accepts the sf object directly.
pdf_sf <- pdf  # already an sf object

# Cutoffs in km
conley_cutoffs <- c(50, 100, 150)

# --- Helper: Conley SEs aligned to glm coefficient names -----------------
conley_se <- function(glm_mod, cutoff_km, family_lab) {
  fm <- formula(glm_mod)
  cr <- conleyreg(
    formula     = fm,
    data        = pdf_sf,
    dist_cutoff = cutoff_km,
    model       = family_lab,   # "logit" or "poisson"
    kernel      = "bartlett",
    verbose     = FALSE
  )
  cr_se <- cr[, "Std. Error"]
  out   <- setNames(rep(NA_real_, length(coef(glm_mod))), names(coef(glm_mod)))
  out[names(cr_se)] <- cr_se
  out
}

# --- Helper: write one stargazer table for a (muster, primary, seats) triplet
write_conley_table <- function(mods, cutoff_km, label_suffix, title, out_path,
                               cov_labels) {
  ses <- list(
    conley_se(mods$muster,  cutoff_km, "logit"),
    conley_se(mods$primary, cutoff_km, "logit"),
    conley_se(mods$seat,    cutoff_km, "poisson")
  )
  stargazer(
    mods$muster, mods$primary, mods$seat,
    type             = "latex",
    se               = ses,
    title            = title,
    label            = paste0("tab:conley", label_suffix, "_", cutoff_km, "km"),
    omit             = hide_vars,
    covariate.labels = cov_labels,
    column.labels    = c("Muster", "Primary", "Seats"),
    add.lines        = list(
      c("Conley cutoff (km)", rep(as.character(cutoff_km), 3)),
      c("Kernel",             rep("Bartlett", 3))
    ),
    align            = TRUE,
    column.sep.width = ".5pt",
    omit.stat        = c("aic"),
    table.placement  = "H",
    out              = out_path
  )
}

# --- Loop all 9 monastic specs -------------------------------------------
for (spec_name in names(monastic_specs)) {
  spec      <- monastic_specs[[spec_name]]
  mods      <- full_models_by_spec[[spec_name]]
  mon_vars  <- spec$monastic_vars
  sfx       <- spec$suffix

  cov_order  <- c(mon_vars, "mg_fsnub", "mg_court",
                  "lLStax_pc", "wet_1535", "wet_1536", "lpopC", "distScot")
  cov_labels <- unlist(pretty_dict[cov_order])

  for (k in conley_cutoffs) {
    write_conley_table(
      mods         = mods,
      cutoff_km    = k,
      label_suffix = sfx,
      title        = paste0("Full Monastic Model — Conley SEs (", spec_name, ", ", k, " km)"),
      out_path     = paste0("Output/Tables/conley", sfx, "_", k, "km.tex"),
      cov_labels   = cov_labels
    )
  }
  cat("Wrote Conley tables for spec:", spec_name, "\n")
}

cat("\nAll Conley SE tables written to Output/Tables/conley_*.tex\n")

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:11
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (total_raw, 50 km)}
  \label{tab:conley_total_raw_50km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.200 & 0.455 & 0.159 \\
  & (0.151) & (0.368) & (0.120) \\
  & & & \\
 ln(Tithe) & -0.315^{**} & -0.269 & 0.072 \\
  & (0.144) & (0.233) & (0.104) \\
  & & & \\
 ln(Alms) & 0.260^{***} & 0.331^{***} & -0.027 \\
  & (0.086) & (0.102) & (0.082) \\
  & & & \\
 Small House Proximity (20km) & -0.711 & -1.618^{***} & 0.588 \\
  & (0.682) & (0.601) & (0.586) \\
  & & & \\
 Large House Proximity (20km) & 0.477 & 0.400 & 0.574 \\
  & (0.484) & (0.519) & (0.385) \\
  & & & \\
 Friary Presence & 0.624 & 0.662 & -0.693 \\
  & (0.432) & (0.576) & (1.020) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.666 & -0.600 & 0.079 \\
  & (0.418) & (0.606) & (0.378) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.302 & 0.003 & 0.590^{***} \\
  & (0.364) & (0.441) & (0.207) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.223 & 0.225 & 0.378^{***} \\
  & (0.153) & (0.308) & (0.086) \\
  & & & \\
 Wet 1535 Weather Shock & -0.091 & -0.181 & -0.040 \\
  & (0.264) & (0.292) & (0.190) \\
  & & & \\
 Wet 1536 Weather Shock & 0.166 & 0.507^{*} & 0.496^{***} \\
  & (0.205) & (0.297) & (0.170) \\
  & & & \\
 ln(Population) & 0.344^{**} & 0.370^{**} & 0.040 \\
  & (0.149) & (0.162) & (0.080) \\
  & & & \\
 Distance to Scotland & -0.609^{***} & -0.795^{**} & -0.946^{***} \\
  & (0.228) & (0.343) & (0.233) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 50 & 50 & 50 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.251} & \multicolumn{1}{c}{-82.392} & \multicolumn{1}{c}{-283.716} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:12
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (total_raw, 100 km)}
  \label{tab:conley_total_raw_100km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.200^{*} & 0.455 & 0.159^{*} \\
  & (0.119) & (0.316) & (0.094) \\
  & & & \\
 ln(Tithe) & -0.315^{**} & -0.269 & 0.072 \\
  & (0.127) & (0.235) & (0.113) \\
  & & & \\
 ln(Alms) & 0.260^{***} & 0.331^{***} & -0.027 \\
  & (0.076) & (0.077) & (0.066) \\
  & & & \\
 Small House Proximity (20km) & -0.711 & -1.618^{***} & 0.588 \\
  & (0.607) & (0.436) & (0.428) \\
  & & & \\
 Large House Proximity (20km) & 0.477 & 0.400 & 0.574^{*} \\
  & (0.327) & (0.529) & (0.295) \\
  & & & \\
 Friary Presence & 0.624 & 0.662 & -0.693 \\
  & (0.423) & (0.527) & (0.926) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.666 & -0.600 & 0.079 \\
  & (0.480) & (0.664) & (0.392) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.302 & 0.003 & 0.590^{***} \\
  & (0.404) & (0.357) & (0.201) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.223^{*} & 0.225 & 0.378^{***} \\
  & (0.121) & (0.224) & (0.068) \\
  & & & \\
 Wet 1535 Weather Shock & -0.091 & -0.181 & -0.040 \\
  & (0.255) & (0.205) & (0.133) \\
  & & & \\
 Wet 1536 Weather Shock & 0.166 & 0.507^{*} & 0.496^{***} \\
  & (0.178) & (0.287) & (0.122) \\
  & & & \\
 ln(Population) & 0.344^{**} & 0.370^{**} & 0.040 \\
  & (0.149) & (0.174) & (0.068) \\
  & & & \\
 Distance to Scotland & -0.609^{**} & -0.795^{**} & -0.946^{***} \\
  & (0.245) & (0.404) & (0.307) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 100 & 100 & 100 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.251} & \multicolumn{1}{c}{-82.392} & \multicolumn{1}{c}{-283.716} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:13
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (total_raw, 150 km)}
  \label{tab:conley_total_raw_150km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land Owned + 1) & 0.200^{**} & 0.455^{*} & 0.159^{*} \\
  & (0.080) & (0.236) & (0.082) \\
  & & & \\
 ln(Tithe) & -0.315^{***} & -0.269 & 0.072 \\
  & (0.116) & (0.201) & (0.098) \\
  & & & \\
 ln(Alms) & 0.260^{***} & 0.331^{***} & -0.027 \\
  & (0.059) & (0.067) & (0.056) \\
  & & & \\
 Small House Proximity (20km) & -0.711 & -1.618^{***} & 0.588 \\
  & (0.508) & (0.375) & (0.374) \\
  & & & \\
 Large House Proximity (20km) & 0.477^{*} & 0.400 & 0.574^{*} \\
  & (0.273) & (0.510) & (0.309) \\
  & & & \\
 Friary Presence & 0.624 & 0.662 & -0.693 \\
  & (0.416) & (0.466) & (0.784) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.666 & -0.600 & 0.079 \\
  & (0.467) & (0.637) & (0.368) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.302 & 0.003 & 0.590^{***} \\
  & (0.385) & (0.313) & (0.188) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.223^{**} & 0.225 & 0.378^{***} \\
  & (0.104) & (0.184) & (0.070) \\
  & & & \\
 Wet 1535 Weather Shock & -0.091 & -0.181 & -0.040 \\
  & (0.237) & (0.140) & (0.122) \\
  & & & \\
 Wet 1536 Weather Shock & 0.166 & 0.507^{**} & 0.496^{***} \\
  & (0.148) & (0.247) & (0.120) \\
  & & & \\
 ln(Population) & 0.344^{***} & 0.370^{**} & 0.040 \\
  & (0.131) & (0.150) & (0.057) \\
  & & & \\
 Distance to Scotland & -0.609^{***} & -0.795^{*} & -0.946^{***} \\
  & (0.236) & (0.422) & (0.341) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 150 & 150 & 150 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.251} & \multicolumn{1}{c}{-82.392} & \multicolumn{1}{c}{-283.716} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
Wrote Conley tables for spec: total_raw

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:14
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (total_sk, 50 km)}
  \label{tab:conley_total_sk_50km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.099 & 0.341 & 0.029 \\
  & (0.156) & (0.417) & (0.108) \\
  & & & \\
 ln(Tithe / km²) & -0.300^{**} & -0.254 & 0.076 \\
  & (0.149) & (0.243) & (0.109) \\
  & & & \\
 ln(Alms / km²) & 0.233^{**} & 0.276^{**} & -0.037 \\
  & (0.106) & (0.131) & (0.081) \\
  & & & \\
 Small House Proximity (20km) & -0.653 & -1.531^{**} & 0.592 \\
  & (0.694) & (0.609) & (0.586) \\
  & & & \\
 Large House Proximity (20km) & 0.562 & 0.520 & 0.639 \\
  & (0.488) & (0.542) & (0.389) \\
  & & & \\
 Friary Presence & 0.632 & 0.629 & -0.704 \\
  & (0.431) & (0.635) & (1.054) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.660 & -0.568 & 0.036 \\
  & (0.435) & (0.607) & (0.380) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.326 & 0.063 & 0.656^{***} \\
  & (0.370) & (0.430) & (0.220) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.233 & 0.241 & 0.383^{***} \\
  & (0.152) & (0.296) & (0.086) \\
  & & & \\
 Wet 1535 Weather Shock & -0.057 & -0.113 & 0.00001 \\
  & (0.267) & (0.298) & (0.191) \\
  & & & \\
 Wet 1536 Weather Shock & 0.130 & 0.440 & 0.468^{***} \\
  & (0.209) & (0.297) & (0.170) \\
  & & & \\
 ln(Population) & 0.368^{**} & 0.409^{***} & 0.051 \\
  & (0.149) & (0.158) & (0.080) \\
  & & & \\
 Distance to Scotland & -0.609^{***} & -0.789^{**} & -0.937^{***} \\
  & (0.227) & (0.342) & (0.234) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 50 & 50 & 50 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.857} & \multicolumn{1}{c}{-83.603} & \multicolumn{1}{c}{-284.790} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:15
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (total_sk, 100 km)}
  \label{tab:conley_total_sk_100km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.099 & 0.341 & 0.029 \\
  & (0.126) & (0.365) & (0.078) \\
  & & & \\
 ln(Tithe / km²) & -0.300^{**} & -0.254 & 0.076 \\
  & (0.129) & (0.246) & (0.119) \\
  & & & \\
 ln(Alms / km²) & 0.233^{**} & 0.276^{***} & -0.037 \\
  & (0.105) & (0.107) & (0.069) \\
  & & & \\
 Small House Proximity (20km) & -0.653 & -1.531^{***} & 0.592 \\
  & (0.613) & (0.436) & (0.421) \\
  & & & \\
 Large House Proximity (20km) & 0.562^{*} & 0.520 & 0.639^{**} \\
  & (0.337) & (0.572) & (0.305) \\
  & & & \\
 Friary Presence & 0.632 & 0.629 & -0.704 \\
  & (0.418) & (0.577) & (0.957) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.660 & -0.568 & 0.036 \\
  & (0.505) & (0.646) & (0.395) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.326 & 0.063 & 0.656^{***} \\
  & (0.409) & (0.334) & (0.215) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.233^{*} & 0.241 & 0.383^{***} \\
  & (0.123) & (0.210) & (0.067) \\
  & & & \\
 Wet 1535 Weather Shock & -0.057 & -0.113 & 0.00001 \\
  & (0.254) & (0.205) & (0.130) \\
  & & & \\
 Wet 1536 Weather Shock & 0.130 & 0.440 & 0.468^{***} \\
  & (0.177) & (0.276) & (0.121) \\
  & & & \\
 ln(Population) & 0.368^{**} & 0.409^{**} & 0.051 \\
  & (0.151) & (0.168) & (0.071) \\
  & & & \\
 Distance to Scotland & -0.609^{**} & -0.789^{**} & -0.937^{***} \\
  & (0.243) & (0.396) & (0.307) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 100 & 100 & 100 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.857} & \multicolumn{1}{c}{-83.603} & \multicolumn{1}{c}{-284.790} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:16
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (total_sk, 150 km)}
  \label{tab:conley_total_sk_150km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Total Monastic Land / km²) & 0.099 & 0.341 & 0.029 \\
  & (0.095) & (0.289) & (0.066) \\
  & & & \\
 ln(Tithe / km²) & -0.300^{**} & -0.254 & 0.076 \\
  & (0.121) & (0.209) & (0.105) \\
  & & & \\
 ln(Alms / km²) & 0.233^{***} & 0.276^{***} & -0.037 \\
  & (0.088) & (0.089) & (0.060) \\
  & & & \\
 Small House Proximity (20km) & -0.653 & -1.531^{***} & 0.592 \\
  & (0.511) & (0.379) & (0.366) \\
  & & & \\
 Large House Proximity (20km) & 0.562^{**} & 0.520 & 0.639^{**} \\
  & (0.284) & (0.548) & (0.320) \\
  & & & \\
 Friary Presence & 0.632 & 0.629 & -0.704 \\
  & (0.413) & (0.501) & (0.810) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.660 & -0.568 & 0.036 \\
  & (0.491) & (0.609) & (0.373) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.326 & 0.063 & 0.656^{***} \\
  & (0.390) & (0.295) & (0.199) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.233^{**} & 0.241 & 0.383^{***} \\
  & (0.107) & (0.173) & (0.068) \\
  & & & \\
 Wet 1535 Weather Shock & -0.057 & -0.113 & 0.00001 \\
  & (0.232) & (0.140) & (0.120) \\
  & & & \\
 Wet 1536 Weather Shock & 0.130 & 0.440^{*} & 0.468^{***} \\
  & (0.139) & (0.237) & (0.121) \\
  & & & \\
 ln(Population) & 0.368^{***} & 0.409^{***} & 0.051 \\
  & (0.133) & (0.143) & (0.062) \\
  & & & \\
 Distance to Scotland & -0.609^{***} & -0.789^{*} & -0.937^{***} \\
  & (0.233) & (0.411) & (0.340) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 150 & 150 & 150 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.857} & \multicolumn{1}{c}{-83.603} & \multicolumn{1}{c}{-284.790} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
Wrote Conley tables for spec: total_sk

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:18
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (total_arak, 50 km)}
  \label{tab:conley_total_arak_50km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.139 & 0.376 & 0.115 \\
  & (0.170) & (0.371) & (0.136) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.309^{**} & -0.253 & 0.065 \\
  & (0.144) & (0.230) & (0.104) \\
  & & & \\
 ln(Alms / Arable km²) & 0.094 & 0.164 & -0.116 \\
  & (0.099) & (0.154) & (0.116) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.309^{**} & 0.247 & 0.076 \\
  & (0.121) & (0.221) & (0.127) \\
  & & & \\
 Small House Proximity (20km) & -0.735 & -1.585^{***} & 0.606 \\
  & (0.678) & (0.605) & (0.577) \\
  & & & \\
 Large House Proximity (20km) & 0.478 & 0.428 & 0.602 \\
  & (0.477) & (0.522) & (0.380) \\
  & & & \\
 Friary Presence & 0.586 & 0.575 & -0.781 \\
  & (0.468) & (0.672) & (1.091) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.762^{*} & -0.693 & 0.028 \\
  & (0.433) & (0.600) & (0.376) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.407 & 0.149 & 0.667^{***} \\
  & (0.405) & (0.413) & (0.230) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.235 & 0.221 & 0.383^{***} \\
  & (0.158) & (0.313) & (0.087) \\
  & & & \\
 Wet 1535 Weather Shock & -0.125 & -0.171 & -0.027 \\
  & (0.266) & (0.307) & (0.191) \\
  & & & \\
 Wet 1536 Weather Shock & 0.174 & 0.494^{*} & 0.487^{***} \\
  & (0.200) & (0.297) & (0.170) \\
  & & & \\
 ln(Population) & 0.362^{**} & 0.400^{**} & 0.051 \\
  & (0.150) & (0.155) & (0.080) \\
  & & & \\
 Distance to Scotland & -0.592^{***} & -0.767^{**} & -0.944^{***} \\
  & (0.225) & (0.336) & (0.233) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 50 & 50 & 50 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-158.536} & \multicolumn{1}{c}{-82.585} & \multicolumn{1}{c}{-283.957} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:19
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (total_arak, 100 km)}
  \label{tab:conley_total_arak_100km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.139 & 0.376 & 0.115 \\
  & (0.129) & (0.303) & (0.107) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.309^{***} & -0.253 & 0.065 \\
  & (0.114) & (0.210) & (0.115) \\
  & & & \\
 ln(Alms / Arable km²) & 0.094 & 0.164 & -0.116 \\
  & (0.092) & (0.109) & (0.103) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.309^{***} & 0.247 & 0.076 \\
  & (0.093) & (0.174) & (0.114) \\
  & & & \\
 Small House Proximity (20km) & -0.735 & -1.585^{***} & 0.606 \\
  & (0.581) & (0.423) & (0.410) \\
  & & & \\
 Large House Proximity (20km) & 0.478 & 0.428 & 0.602^{**} \\
  & (0.323) & (0.559) & (0.287) \\
  & & & \\
 Friary Presence & 0.586 & 0.575 & -0.781 \\
  & (0.431) & (0.610) & (0.993) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.762 & -0.693 & 0.028 \\
  & (0.495) & (0.612) & (0.396) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.407 & 0.149 & 0.667^{***} \\
  & (0.460) & (0.342) & (0.238) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.235^{*} & 0.221 & 0.383^{***} \\
  & (0.128) & (0.227) & (0.062) \\
  & & & \\
 Wet 1535 Weather Shock & -0.125 & -0.171 & -0.027 \\
  & (0.246) & (0.207) & (0.133) \\
  & & & \\
 Wet 1536 Weather Shock & 0.174 & 0.494^{*} & 0.487^{***} \\
  & (0.166) & (0.268) & (0.124) \\
  & & & \\
 ln(Population) & 0.362^{**} & 0.400^{**} & 0.051 \\
  & (0.150) & (0.165) & (0.069) \\
  & & & \\
 Distance to Scotland & -0.592^{**} & -0.767^{*} & -0.944^{***} \\
  & (0.243) & (0.395) & (0.308) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 100 & 100 & 100 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-158.536} & \multicolumn{1}{c}{-82.585} & \multicolumn{1}{c}{-283.957} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:20
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (total_arak, 150 km)}
  \label{tab:conley_total_arak_150km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Land Owned / Arable km²) & 0.139 & 0.376 & 0.115 \\
  & (0.101) & (0.229) & (0.092) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.309^{***} & -0.253 & 0.065 \\
  & (0.104) & (0.167) & (0.100) \\
  & & & \\
 ln(Alms / Arable km²) & 0.094 & 0.164^{*} & -0.116 \\
  & (0.082) & (0.098) & (0.084) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.309^{***} & 0.247^{*} & 0.076 \\
  & (0.065) & (0.138) & (0.095) \\
  & & & \\
 Small House Proximity (20km) & -0.735 & -1.585^{***} & 0.606^{*} \\
  & (0.476) & (0.372) & (0.364) \\
  & & & \\
 Large House Proximity (20km) & 0.478^{*} & 0.428 & 0.602^{**} \\
  & (0.268) & (0.542) & (0.302) \\
  & & & \\
 Friary Presence & 0.586 & 0.575 & -0.781 \\
  & (0.412) & (0.516) & (0.816) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.762 & -0.693 & 0.028 \\
  & (0.489) & (0.589) & (0.382) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.407 & 0.149 & 0.667^{***} \\
  & (0.426) & (0.294) & (0.224) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.235^{**} & 0.221 & 0.383^{***} \\
  & (0.111) & (0.189) & (0.064) \\
  & & & \\
 Wet 1535 Weather Shock & -0.125 & -0.171 & -0.027 \\
  & (0.228) & (0.142) & (0.124) \\
  & & & \\
 Wet 1536 Weather Shock & 0.174 & 0.494^{**} & 0.487^{***} \\
  & (0.134) & (0.224) & (0.122) \\
  & & & \\
 ln(Population) & 0.362^{***} & 0.400^{***} & 0.051 \\
  & (0.131) & (0.138) & (0.059) \\
  & & & \\
 Distance to Scotland & -0.592^{**} & -0.767^{*} & -0.944^{***} \\
  & (0.235) & (0.413) & (0.341) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 150 & 150 & 150 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-158.536} & \multicolumn{1}{c}{-82.585} & \multicolumn{1}{c}{-283.957} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
Wrote Conley tables for spec: total_arak

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:21
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (split_raw, 50 km)}
  \label{tab:conley_split_raw_50km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & 0.091 & -0.162 & 0.184^{**} \\
  & (0.160) & (0.198) & (0.072) \\
  & & & \\
 ln(Large House Land + 1) & 0.326^{**} & 0.581^{*} & 0.204^{**} \\
  & (0.143) & (0.333) & (0.103) \\
  & & & \\
 ln(Tithe) & -0.369^{***} & -0.308 & 0.017 \\
  & (0.141) & (0.241) & (0.097) \\
  & & & \\
 ln(Alms) & 0.251^{***} & 0.344^{***} & -0.034 \\
  & (0.087) & (0.102) & (0.076) \\
  & & & \\
 Small House Proximity (20km) & -0.730 & -1.528^{***} & 0.505 \\
  & (0.660) & (0.581) & (0.595) \\
  & & & \\
 Large House Proximity (20km) & 0.401 & 0.360 & 0.539 \\
  & (0.484) & (0.535) & (0.388) \\
  & & & \\
 Friary Presence & 0.548 & 0.657 & -0.739 \\
  & (0.434) & (0.596) & (1.034) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.643 & -0.698 & 0.147 \\
  & (0.414) & (0.620) & (0.370) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.274 & 0.052 & 0.512^{**} \\
  & (0.349) & (0.413) & (0.215) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.225 & 0.265 & 0.371^{***} \\
  & (0.166) & (0.313) & (0.088) \\
  & & & \\
 Wet 1535 Weather Shock & -0.129 & -0.139 & -0.120 \\
  & (0.269) & (0.290) & (0.195) \\
  & & & \\
 Wet 1536 Weather Shock & 0.202 & 0.492 & 0.545^{***} \\
  & (0.206) & (0.302) & (0.174) \\
  & & & \\
 ln(Population) & 0.326^{**} & 0.377^{**} & 0.018 \\
  & (0.142) & (0.165) & (0.079) \\
  & & & \\
 Distance to Scotland & -0.613^{***} & -0.848^{**} & -0.923^{***} \\
  & (0.238) & (0.356) & (0.232) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 50 & 50 & 50 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-159.129} & \multicolumn{1}{c}{-81.406} & \multicolumn{1}{c}{-281.218} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:22
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (split_raw, 100 km)}
  \label{tab:conley_split_raw_100km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & 0.091 & -0.162 & 0.184^{***} \\
  & (0.127) & (0.144) & (0.051) \\
  & & & \\
 ln(Large House Land + 1) & 0.326^{***} & 0.581^{*} & 0.204^{**} \\
  & (0.117) & (0.299) & (0.087) \\
  & & & \\
 ln(Tithe) & -0.369^{***} & -0.308 & 0.017 \\
  & (0.122) & (0.248) & (0.105) \\
  & & & \\
 ln(Alms) & 0.251^{***} & 0.344^{***} & -0.034 \\
  & (0.079) & (0.076) & (0.060) \\
  & & & \\
 Small House Proximity (20km) & -0.730 & -1.528^{***} & 0.505 \\
  & (0.584) & (0.410) & (0.428) \\
  & & & \\
 Large House Proximity (20km) & 0.401 & 0.360 & 0.539^{*} \\
  & (0.321) & (0.540) & (0.293) \\
  & & & \\
 Friary Presence & 0.548 & 0.657 & -0.739 \\
  & (0.422) & (0.538) & (0.930) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.643 & -0.698 & 0.147 \\
  & (0.452) & (0.652) & (0.379) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.274 & 0.052 & 0.512^{**} \\
  & (0.385) & (0.341) & (0.203) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.225^{*} & 0.265 & 0.371^{***} \\
  & (0.134) & (0.222) & (0.074) \\
  & & & \\
 Wet 1535 Weather Shock & -0.129 & -0.139 & -0.120 \\
  & (0.258) & (0.198) & (0.133) \\
  & & & \\
 Wet 1536 Weather Shock & 0.202 & 0.492^{*} & 0.545^{***} \\
  & (0.182) & (0.291) & (0.121) \\
  & & & \\
 ln(Population) & 0.326^{**} & 0.377^{**} & 0.018 \\
  & (0.143) & (0.172) & (0.066) \\
  & & & \\
 Distance to Scotland & -0.613^{**} & -0.848^{**} & -0.923^{***} \\
  & (0.248) & (0.406) & (0.310) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 100 & 100 & 100 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-159.129} & \multicolumn{1}{c}{-81.406} & \multicolumn{1}{c}{-281.218} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:23
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (split_raw, 150 km)}
  \label{tab:conley_split_raw_150km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small House Land + 1) & 0.091 & -0.162 & 0.184^{***} \\
  & (0.101) & (0.118) & (0.048) \\
  & & & \\
 ln(Large House Land + 1) & 0.326^{***} & 0.581^{***} & 0.204^{***} \\
  & (0.074) & (0.225) & (0.075) \\
  & & & \\
 ln(Tithe) & -0.369^{***} & -0.308 & 0.017 \\
  & (0.112) & (0.213) & (0.093) \\
  & & & \\
 ln(Alms) & 0.251^{***} & 0.344^{***} & -0.034 \\
  & (0.063) & (0.065) & (0.050) \\
  & & & \\
 Small House Proximity (20km) & -0.730 & -1.528^{***} & 0.505 \\
  & (0.491) & (0.355) & (0.376) \\
  & & & \\
 Large House Proximity (20km) & 0.401 & 0.360 & 0.539^{*} \\
  & (0.259) & (0.512) & (0.303) \\
  & & & \\
 Friary Presence & 0.548 & 0.657 & -0.739 \\
  & (0.417) & (0.469) & (0.781) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.643 & -0.698 & 0.147 \\
  & (0.437) & (0.615) & (0.355) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.274 & 0.052 & 0.512^{***} \\
  & (0.366) & (0.296) & (0.187) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.225^{**} & 0.265 & 0.371^{***} \\
  & (0.115) & (0.182) & (0.075) \\
  & & & \\
 Wet 1535 Weather Shock & -0.129 & -0.139 & -0.120 \\
  & (0.245) & (0.137) & (0.123) \\
  & & & \\
 Wet 1536 Weather Shock & 0.202 & 0.492^{**} & 0.545^{***} \\
  & (0.154) & (0.246) & (0.118) \\
  & & & \\
 ln(Population) & 0.326^{***} & 0.377^{***} & 0.018 \\
  & (0.126) & (0.145) & (0.053) \\
  & & & \\
 Distance to Scotland & -0.613^{***} & -0.848^{**} & -0.923^{***} \\
  & (0.234) & (0.420) & (0.344) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 150 & 150 & 150 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-159.129} & \multicolumn{1}{c}{-81.406} & \multicolumn{1}{c}{-281.218} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
Wrote Conley tables for spec: split_raw

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:25
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (split_sk, 50 km)}
  \label{tab:conley_split_sk_50km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & 0.010 & -0.574^{*} & 0.152^{*} \\
  & (0.167) & (0.344) & (0.082) \\
  & & & \\
 ln(Large House Land / km²) & 0.233 & 0.459 & 0.095 \\
  & (0.145) & (0.366) & (0.090) \\
  & & & \\
 ln(Tithe / km²) & -0.342^{**} & -0.272 & 0.041 \\
  & (0.144) & (0.256) & (0.105) \\
  & & & \\
 ln(Alms / km²) & 0.223^{**} & 0.289^{*} & -0.067 \\
  & (0.107) & (0.148) & (0.078) \\
  & & & \\
 Small House Proximity (20km) & -0.661 & -1.409^{**} & 0.547 \\
  & (0.673) & (0.577) & (0.592) \\
  & & & \\
 Large House Proximity (20km) & 0.505 & 0.515 & 0.605 \\
  & (0.492) & (0.562) & (0.392) \\
  & & & \\
 Friary Presence & 0.575 & 0.786 & -0.808 \\
  & (0.453) & (0.669) & (1.102) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.662 & -0.733 & 0.089 \\
  & (0.429) & (0.633) & (0.379) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.328 & 0.181 & 0.606^{***} \\
  & (0.364) & (0.421) & (0.224) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.234 & 0.301 & 0.372^{***} \\
  & (0.163) & (0.295) & (0.087) \\
  & & & \\
 Wet 1535 Weather Shock & -0.070 & -0.020 & -0.051 \\
  & (0.271) & (0.304) & (0.196) \\
  & & & \\
 Wet 1536 Weather Shock & 0.144 & 0.398 & 0.493^{***} \\
  & (0.207) & (0.298) & (0.174) \\
  & & & \\
 ln(Population) & 0.361^{**} & 0.432^{***} & 0.044 \\
  & (0.145) & (0.167) & (0.079) \\
  & & & \\
 Distance to Scotland & -0.626^{***} & -0.864^{**} & -0.925^{***} \\
  & (0.232) & (0.346) & (0.234) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 50 & 50 & 50 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.322} & \multicolumn{1}{c}{-81.700} & \multicolumn{1}{c}{-283.517} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:26
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (split_sk, 100 km)}
  \label{tab:conley_split_sk_100km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & 0.010 & -0.574^{**} & 0.152^{***} \\
  & (0.130) & (0.255) & (0.058) \\
  & & & \\
 ln(Large House Land / km²) & 0.233^{*} & 0.459 & 0.095 \\
  & (0.124) & (0.330) & (0.070) \\
  & & & \\
 ln(Tithe / km²) & -0.342^{***} & -0.272 & 0.041 \\
  & (0.125) & (0.270) & (0.115) \\
  & & & \\
 ln(Alms / km²) & 0.223^{**} & 0.289^{**} & -0.067 \\
  & (0.107) & (0.120) & (0.067) \\
  & & & \\
 Small House Proximity (20km) & -0.661 & -1.409^{***} & 0.547 \\
  & (0.584) & (0.392) & (0.421) \\
  & & & \\
 Large House Proximity (20km) & 0.505 & 0.515 & 0.605^{**} \\
  & (0.336) & (0.589) & (0.306) \\
  & & & \\
 Friary Presence & 0.575 & 0.786 & -0.808 \\
  & (0.433) & (0.602) & (0.990) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.662 & -0.733 & 0.089 \\
  & (0.485) & (0.648) & (0.392) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.328 & 0.181 & 0.606^{***} \\
  & (0.403) & (0.356) & (0.215) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.234^{*} & 0.301 & 0.372^{***} \\
  & (0.134) & (0.196) & (0.072) \\
  & & & \\
 Wet 1535 Weather Shock & -0.070 & -0.020 & -0.051 \\
  & (0.255) & (0.204) & (0.132) \\
  & & & \\
 Wet 1536 Weather Shock & 0.144 & 0.398 & 0.493^{***} \\
  & (0.175) & (0.284) & (0.121) \\
  & & & \\
 ln(Population) & 0.361^{**} & 0.432^{**} & 0.044 \\
  & (0.146) & (0.172) & (0.069) \\
  & & & \\
 Distance to Scotland & -0.626^{***} & -0.864^{**} & -0.925^{***} \\
  & (0.242) & (0.391) & (0.310) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 100 & 100 & 100 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.322} & \multicolumn{1}{c}{-81.700} & \multicolumn{1}{c}{-283.517} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:27
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (split_sk, 150 km)}
  \label{tab:conley_split_sk_150km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small House Land / km²) & 0.010 & -0.574^{***} & 0.152^{***} \\
  & (0.110) & (0.201) & (0.050) \\
  & & & \\
 ln(Large House Land / km²) & 0.233^{***} & 0.459^{*} & 0.095 \\
  & (0.088) & (0.261) & (0.060) \\
  & & & \\
 ln(Tithe / km²) & -0.342^{***} & -0.272 & 0.041 \\
  & (0.118) & (0.235) & (0.102) \\
  & & & \\
 ln(Alms / km²) & 0.223^{**} & 0.289^{***} & -0.067 \\
  & (0.090) & (0.093) & (0.057) \\
  & & & \\
 Small House Proximity (20km) & -0.661 & -1.409^{***} & 0.547 \\
  & (0.487) & (0.347) & (0.366) \\
  & & & \\
 Large House Proximity (20km) & 0.505^{*} & 0.515 & 0.605^{*} \\
  & (0.273) & (0.555) & (0.318) \\
  & & & \\
 Friary Presence & 0.575 & 0.786 & -0.808 \\
  & (0.427) & (0.515) & (0.818) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.662 & -0.733 & 0.089 \\
  & (0.470) & (0.603) & (0.370) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.328 & 0.181 & 0.606^{***} \\
  & (0.382) & (0.311) & (0.197) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.234^{**} & 0.301^{*} & 0.372^{***} \\
  & (0.118) & (0.159) & (0.073) \\
  & & & \\
 Wet 1535 Weather Shock & -0.070 & -0.020 & -0.051 \\
  & (0.236) & (0.140) & (0.122) \\
  & & & \\
 Wet 1536 Weather Shock & 0.144 & 0.398 & 0.493^{***} \\
  & (0.139) & (0.245) & (0.119) \\
  & & & \\
 ln(Population) & 0.361^{***} & 0.432^{***} & 0.044 \\
  & (0.129) & (0.146) & (0.059) \\
  & & & \\
 Distance to Scotland & -0.626^{***} & -0.864^{**} & -0.925^{***} \\
  & (0.228) & (0.399) & (0.344) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 150 & 150 & 150 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-160.322} & \multicolumn{1}{c}{-81.700} & \multicolumn{1}{c}{-283.517} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
Wrote Conley tables for spec: split_sk

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:28
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (split_arak, 50 km)}
  \label{tab:conley_split_arak_50km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & 0.028 & -0.393^{*} & 0.124^{*} \\
  & (0.156) & (0.232) & (0.075) \\
  & & & \\
 ln(Large Monastery Land / Arable km²) & 0.274^{*} & 0.509 & 0.195^{*} \\
  & (0.147) & (0.310) & (0.117) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.359^{**} & -0.307 & 0.022 \\
  & (0.141) & (0.235) & (0.098) \\
  & & & \\
 ln(Alms / Arable km²) & 0.098 & 0.187 & -0.119 \\
  & (0.102) & (0.171) & (0.115) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.292^{**} & 0.243 & 0.057 \\
  & (0.122) & (0.212) & (0.129) \\
  & & & \\
 Small House Proximity (20km) & -0.730 & -1.474^{**} & 0.589 \\
  & (0.655) & (0.579) & (0.586) \\
  & & & \\
 Large House Proximity (20km) & 0.417 & 0.366 & 0.565 \\
  & (0.466) & (0.539) & (0.384) \\
  & & & \\
 Friary Presence & 0.537 & 0.627 & -0.862 \\
  & (0.469) & (0.711) & (1.118) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.768^{*} & -0.849 & 0.057 \\
  & (0.421) & (0.614) & (0.372) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.411 & 0.233 & 0.640^{***} \\
  & (0.403) & (0.397) & (0.227) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.230 & 0.264 & 0.375^{***} \\
  & (0.171) & (0.315) & (0.086) \\
  & & & \\
 Wet 1535 Weather Shock & -0.144 & -0.084 & -0.074 \\
  & (0.268) & (0.307) & (0.194) \\
  & & & \\
 Wet 1536 Weather Shock & 0.197 & 0.432 & 0.523^{***} \\
  & (0.199) & (0.302) & (0.174) \\
  & & & \\
 ln(Population) & 0.352^{**} & 0.416^{**} & 0.043 \\
  & (0.145) & (0.162) & (0.080) \\
  & & & \\
 Distance to Scotland & -0.606^{***} & -0.828^{**} & -0.943^{***} \\
  & (0.229) & (0.338) & (0.233) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 50 & 50 & 50 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-157.742} & \multicolumn{1}{c}{-80.952} & \multicolumn{1}{c}{-282.482} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:29
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (split_arak, 100 km)}
  \label{tab:conley_split_arak_100km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & 0.028 & -0.393^{**} & 0.124^{**} \\
  & (0.132) & (0.163) & (0.051) \\
  & & & \\
 ln(Large Monastery Land / Arable km²) & 0.274^{**} & 0.509^{**} & 0.195^{**} \\
  & (0.116) & (0.256) & (0.094) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.359^{***} & -0.307 & 0.022 \\
  & (0.110) & (0.218) & (0.107) \\
  & & & \\
 ln(Alms / Arable km²) & 0.098 & 0.187 & -0.119 \\
  & (0.094) & (0.122) & (0.103) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.292^{***} & 0.243 & 0.057 \\
  & (0.095) & (0.162) & (0.116) \\
  & & & \\
 Small House Proximity (20km) & -0.730 & -1.474^{***} & 0.589 \\
  & (0.544) & (0.373) & (0.412) \\
  & & & \\
 Large House Proximity (20km) & 0.417 & 0.366 & 0.565^{**} \\
  & (0.313) & (0.585) & (0.287) \\
  & & & \\
 Friary Presence & 0.537 & 0.627 & -0.862 \\
  & (0.433) & (0.635) & (1.004) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.768 & -0.849 & 0.057 \\
  & (0.469) & (0.602) & (0.390) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.411 & 0.233 & 0.640^{***} \\
  & (0.457) & (0.353) & (0.232) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.230 & 0.264 & 0.375^{***} \\
  & (0.141) & (0.220) & (0.064) \\
  & & & \\
 Wet 1535 Weather Shock & -0.144 & -0.084 & -0.074 \\
  & (0.245) & (0.204) & (0.134) \\
  & & & \\
 Wet 1536 Weather Shock & 0.197 & 0.432 & 0.523^{***} \\
  & (0.164) & (0.278) & (0.123) \\
  & & & \\
 ln(Population) & 0.352^{**} & 0.416^{**} & 0.043 \\
  & (0.145) & (0.166) & (0.067) \\
  & & & \\
 Distance to Scotland & -0.606^{**} & -0.828^{**} & -0.943^{***} \\
  & (0.240) & (0.387) & (0.308) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 100 & 100 & 100 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-157.742} & \multicolumn{1}{c}{-80.952} & \multicolumn{1}{c}{-282.482} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:31
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (split_arak, 150 km)}
  \label{tab:conley_split_arak_150km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Small Monastery Land / Arable km²) & 0.028 & -0.393^{***} & 0.124^{***} \\
  & (0.117) & (0.133) & (0.044) \\
  & & & \\
 ln(Large Monastery Land / Arable km²) & 0.274^{***} & 0.509^{***} & 0.195^{**} \\
  & (0.082) & (0.194) & (0.084) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.359^{***} & -0.307^{*} & 0.022 \\
  & (0.100) & (0.176) & (0.095) \\
  & & & \\
 ln(Alms / Arable km²) & 0.098 & 0.187^{*} & -0.119 \\
  & (0.085) & (0.108) & (0.083) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.292^{***} & 0.243^{*} & 0.057 \\
  & (0.068) & (0.129) & (0.095) \\
  & & & \\
 Small House Proximity (20km) & -0.730 & -1.474^{***} & 0.589 \\
  & (0.444) & (0.342) & (0.367) \\
  & & & \\
 Large House Proximity (20km) & 0.417^{*} & 0.366 & 0.565^{*} \\
  & (0.253) & (0.559) & (0.299) \\
  & & & \\
 Friary Presence & 0.537 & 0.627 & -0.862 \\
  & (0.417) & (0.525) & (0.818) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.768^{*} & -0.849 & 0.057 \\
  & (0.464) & (0.570) & (0.374) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.411 & 0.233 & 0.640^{***} \\
  & (0.422) & (0.300) & (0.219) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.230^{*} & 0.264 & 0.375^{***} \\
  & (0.124) & (0.180) & (0.066) \\
  & & & \\
 Wet 1535 Weather Shock & -0.144 & -0.084 & -0.074 \\
  & (0.229) & (0.141) & (0.125) \\
  & & & \\
 Wet 1536 Weather Shock & 0.197 & 0.432^{*} & 0.523^{***} \\
  & (0.134) & (0.233) & (0.120) \\
  & & & \\
 ln(Population) & 0.352^{***} & 0.416^{***} & 0.043 \\
  & (0.128) & (0.139) & (0.055) \\
  & & & \\
 Distance to Scotland & -0.606^{***} & -0.828^{**} & -0.943^{***} \\
  & (0.229) & (0.399) & (0.342) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 150 & 150 & 150 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-157.742} & \multicolumn{1}{c}{-80.952} & \multicolumn{1}{c}{-282.482} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
Wrote Conley tables for spec: split_arak

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:32
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (ownOther_raw, 50 km)}
  \label{tab:conley_ownOther_raw_50km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.287^{*} & 0.556 & 0.115 \\
  & (0.159) & (0.374) & (0.118) \\
  & & & \\
 ln(On-site Monastic Land + 1) & -0.544^{*} & -0.849^{***} & 0.077 \\
  & (0.314) & (0.205) & (0.109) \\
  & & & \\
 ln(Tithe) & -0.375^{**} & -0.372 & 0.080 \\
  & (0.148) & (0.286) & (0.111) \\
  & & & \\
 ln(Alms) & 0.488^{***} & 0.655^{***} & -0.058 \\
  & (0.135) & (0.122) & (0.122) \\
  & & & \\
 Small House Proximity (20km) & -0.710 & -1.641^{***} & 0.582 \\
  & (0.682) & (0.619) & (0.588) \\
  & & & \\
 Large House Proximity (20km) & 0.532 & 0.568 & 0.580 \\
  & (0.524) & (0.532) & (0.382) \\
  & & & \\
 Friary Presence & 0.557 & 0.572 & -0.673 \\
  & (0.423) & (0.608) & (1.016) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.700^{*} & -0.705 & 0.074 \\
  & (0.408) & (0.611) & (0.382) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.258 & -0.111 & 0.614^{***} \\
  & (0.357) & (0.466) & (0.208) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.233 & 0.305 & 0.379^{***} \\
  & (0.162) & (0.302) & (0.087) \\
  & & & \\
 Wet 1535 Weather Shock & -0.104 & -0.243 & -0.026 \\
  & (0.255) & (0.280) & (0.190) \\
  & & & \\
 Wet 1536 Weather Shock & 0.193 & 0.612^{**} & 0.488^{***} \\
  & (0.201) & (0.299) & (0.171) \\
  & & & \\
 ln(Population) & 0.366^{**} & 0.421^{**} & 0.037 \\
  & (0.150) & (0.172) & (0.079) \\
  & & & \\
 Distance to Scotland & -0.658^{***} & -0.889^{**} & -0.941^{***} \\
  & (0.226) & (0.347) & (0.233) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 50 & 50 & 50 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-156.818} & \multicolumn{1}{c}{-78.436} & \multicolumn{1}{c}{-283.811} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:33
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (ownOther_raw, 100 km)}
  \label{tab:conley_ownOther_raw_100km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.287^{**} & 0.556^{*} & 0.115 \\
  & (0.123) & (0.326) & (0.096) \\
  & & & \\
 ln(On-site Monastic Land + 1) & -0.544 & -0.849^{***} & 0.077 \\
  & (0.348) & (0.171) & (0.075) \\
  & & & \\
 ln(Tithe) & -0.375^{***} & -0.372 & 0.080 \\
  & (0.145) & (0.314) & (0.121) \\
  & & & \\
 ln(Alms) & 0.488^{***} & 0.655^{***} & -0.058 \\
  & (0.155) & (0.083) & (0.095) \\
  & & & \\
 Small House Proximity (20km) & -0.710 & -1.641^{***} & 0.582 \\
  & (0.617) & (0.466) & (0.427) \\
  & & & \\
 Large House Proximity (20km) & 0.532 & 0.568 & 0.580^{**} \\
  & (0.379) & (0.535) & (0.293) \\
  & & & \\
 Friary Presence & 0.557 & 0.572 & -0.673 \\
  & (0.399) & (0.541) & (0.921) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.700 & -0.705 & 0.074 \\
  & (0.452) & (0.637) & (0.399) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.258 & -0.111 & 0.614^{***} \\
  & (0.386) & (0.376) & (0.209) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.233^{*} & 0.305 & 0.379^{***} \\
  & (0.130) & (0.206) & (0.069) \\
  & & & \\
 Wet 1535 Weather Shock & -0.104 & -0.243 & -0.026 \\
  & (0.252) & (0.201) & (0.133) \\
  & & & \\
 Wet 1536 Weather Shock & 0.193 & 0.612^{**} & 0.488^{***} \\
  & (0.189) & (0.308) & (0.122) \\
  & & & \\
 ln(Population) & 0.366^{**} & 0.421^{**} & 0.037 \\
  & (0.156) & (0.187) & (0.069) \\
  & & & \\
 Distance to Scotland & -0.658^{***} & -0.889^{**} & -0.941^{***} \\
  & (0.232) & (0.405) & (0.308) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 100 & 100 & 100 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-156.818} & \multicolumn{1}{c}{-78.436} & \multicolumn{1}{c}{-283.811} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:34
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (ownOther_raw, 150 km)}
  \label{tab:conley_ownOther_raw_150km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Monastic Land + 1) & 0.287^{***} & 0.556^{**} & 0.115 \\
  & (0.078) & (0.242) & (0.082) \\
  & & & \\
 ln(On-site Monastic Land + 1) & -0.544 & -0.849^{***} & 0.077 \\
  & (0.344) & (0.142) & (0.060) \\
  & & & \\
 ln(Tithe) & -0.375^{***} & -0.372 & 0.080 \\
  & (0.122) & (0.274) & (0.105) \\
  & & & \\
 ln(Alms) & 0.488^{***} & 0.655^{***} & -0.058 \\
  & (0.148) & (0.069) & (0.078) \\
  & & & \\
 Small House Proximity (20km) & -0.710 & -1.641^{***} & 0.582 \\
  & (0.520) & (0.397) & (0.373) \\
  & & & \\
 Large House Proximity (20km) & 0.532 & 0.568 & 0.580^{*} \\
  & (0.336) & (0.517) & (0.307) \\
  & & & \\
 Friary Presence & 0.557 & 0.572 & -0.673 \\
  & (0.389) & (0.460) & (0.785) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.700 & -0.705 & 0.074 \\
  & (0.439) & (0.609) & (0.377) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.258 & -0.111 & 0.614^{***} \\
  & (0.370) & (0.332) & (0.197) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.233^{**} & 0.305^{*} & 0.379^{***} \\
  & (0.118) & (0.177) & (0.071) \\
  & & & \\
 Wet 1535 Weather Shock & -0.104 & -0.243^{*} & -0.026 \\
  & (0.236) & (0.141) & (0.121) \\
  & & & \\
 Wet 1536 Weather Shock & 0.193 & 0.612^{**} & 0.488^{***} \\
  & (0.156) & (0.270) & (0.121) \\
  & & & \\
 ln(Population) & 0.366^{***} & 0.421^{***} & 0.037 \\
  & (0.138) & (0.161) & (0.057) \\
  & & & \\
 Distance to Scotland & -0.658^{***} & -0.889^{**} & -0.941^{***} \\
  & (0.213) & (0.426) & (0.343) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 150 & 150 & 150 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-156.818} & \multicolumn{1}{c}{-78.436} & \multicolumn{1}{c}{-283.811} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
Wrote Conley tables for spec: ownOther_raw

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:35
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (ownOther_sk, 50 km)}
  \label{tab:conley_ownOther_sk_50km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.225 & 0.514 & -0.019 \\
  & (0.171) & (0.424) & (0.102) \\
  & & & \\
 ln(On-site Land / km²) & -0.607 & -1.298^{***} & 0.180^{*} \\
  & (0.411) & (0.389) & (0.106) \\
  & & & \\
 ln(Tithe / km²) & -0.359^{**} & -0.352 & 0.082 \\
  & (0.145) & (0.270) & (0.117) \\
  & & & \\
 ln(Alms / km²) & 0.478^{***} & 0.652^{***} & -0.137 \\
  & (0.169) & (0.136) & (0.123) \\
  & & & \\
 Small House Proximity (20km) & -0.661 & -1.562^{***} & 0.577 \\
  & (0.682) & (0.589) & (0.587) \\
  & & & \\
 Large House Proximity (20km) & 0.543 & 0.522 & 0.645^{*} \\
  & (0.507) & (0.567) & (0.388) \\
  & & & \\
 Friary Presence & 0.552 & 0.512 & -0.668 \\
  & (0.421) & (0.667) & (1.045) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.678 & -0.633 & 0.040 \\
  & (0.422) & (0.600) & (0.386) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.297 & -0.025 & 0.690^{***} \\
  & (0.361) & (0.439) & (0.226) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.232 & 0.304 & 0.395^{***} \\
  & (0.162) & (0.298) & (0.089) \\
  & & & \\
 Wet 1535 Weather Shock & -0.055 & -0.158 & 0.005 \\
  & (0.266) & (0.294) & (0.191) \\
  & & & \\
 Wet 1536 Weather Shock & 0.147 & 0.523^{*} & 0.473^{***} \\
  & (0.209) & (0.296) & (0.172) \\
  & & & \\
 ln(Population) & 0.379^{**} & 0.437^{**} & 0.051 \\
  & (0.152) & (0.173) & (0.079) \\
  & & & \\
 Distance to Scotland & -0.648^{***} & -0.880^{**} & -0.940^{***} \\
  & (0.228) & (0.345) & (0.234) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 50 & 50 & 50 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-157.783} & \multicolumn{1}{c}{-79.540} & \multicolumn{1}{c}{-283.889} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:37
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (ownOther_sk, 100 km)}
  \label{tab:conley_ownOther_sk_100km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.225 & 0.514 & -0.019 \\
  & (0.142) & (0.375) & (0.076) \\
  & & & \\
 ln(On-site Land / km²) & -0.607 & -1.298^{***} & 0.180^{**} \\
  & (0.467) & (0.311) & (0.086) \\
  & & & \\
 ln(Tithe / km²) & -0.359^{***} & -0.352 & 0.082 \\
  & (0.135) & (0.284) & (0.128) \\
  & & & \\
 ln(Alms / km²) & 0.478^{**} & 0.652^{***} & -0.137 \\
  & (0.204) & (0.121) & (0.108) \\
  & & & \\
 Small House Proximity (20km) & -0.661 & -1.562^{***} & 0.577 \\
  & (0.611) & (0.438) & (0.419) \\
  & & & \\
 Large House Proximity (20km) & 0.543 & 0.522 & 0.645^{**} \\
  & (0.352) & (0.612) & (0.302) \\
  & & & \\
 Friary Presence & 0.552 & 0.512 & -0.668 \\
  & (0.391) & (0.586) & (0.951) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.678 & -0.633 & 0.040 \\
  & (0.474) & (0.607) & (0.404) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.297 & -0.025 & 0.690^{***} \\
  & (0.389) & (0.335) & (0.227) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.232^{*} & 0.304 & 0.395^{***} \\
  & (0.131) & (0.193) & (0.067) \\
  & & & \\
 Wet 1535 Weather Shock & -0.055 & -0.158 & 0.005 \\
  & (0.257) & (0.208) & (0.130) \\
  & & & \\
 Wet 1536 Weather Shock & 0.147 & 0.523^{*} & 0.473^{***} \\
  & (0.189) & (0.280) & (0.120) \\
  & & & \\
 ln(Population) & 0.379^{**} & 0.437^{**} & 0.051 \\
  & (0.156) & (0.186) & (0.071) \\
  & & & \\
 Distance to Scotland & -0.648^{***} & -0.880^{**} & -0.940^{***} \\
  & (0.235) & (0.390) & (0.306) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 100 & 100 & 100 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-157.783} & \multicolumn{1}{c}{-79.540} & \multicolumn{1}{c}{-283.889} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:38
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (ownOther_sk, 150 km)}
  \label{tab:conley_ownOther_sk_150km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / km²) & 0.225^{**} & 0.514^{*} & -0.019 \\
  & (0.098) & (0.286) & (0.064) \\
  & & & \\
 ln(On-site Land / km²) & -0.607 & -1.298^{***} & 0.180^{**} \\
  & (0.466) & (0.245) & (0.073) \\
  & & & \\
 ln(Tithe / km²) & -0.359^{***} & -0.352 & 0.082 \\
  & (0.114) & (0.235) & (0.112) \\
  & & & \\
 ln(Alms / km²) & 0.478^{**} & 0.652^{***} & -0.137 \\
  & (0.198) & (0.108) & (0.091) \\
  & & & \\
 Small House Proximity (20km) & -0.661 & -1.562^{***} & 0.577 \\
  & (0.513) & (0.383) & (0.365) \\
  & & & \\
 Large House Proximity (20km) & 0.543^{*} & 0.522 & 0.645^{**} \\
  & (0.295) & (0.591) & (0.317) \\
  & & & \\
 Friary Presence & 0.552 & 0.512 & -0.668 \\
  & (0.381) & (0.480) & (0.810) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.678 & -0.633 & 0.040 \\
  & (0.461) & (0.574) & (0.383) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.297 & -0.025 & 0.690^{***} \\
  & (0.372) & (0.303) & (0.212) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.232^{*} & 0.304^{*} & 0.395^{***} \\
  & (0.119) & (0.167) & (0.068) \\
  & & & \\
 Wet 1535 Weather Shock & -0.055 & -0.158 & 0.005 \\
  & (0.239) & (0.148) & (0.121) \\
  & & & \\
 Wet 1536 Weather Shock & 0.147 & 0.523^{**} & 0.473^{***} \\
  & (0.152) & (0.239) & (0.120) \\
  & & & \\
 ln(Population) & 0.379^{***} & 0.437^{***} & 0.051 \\
  & (0.138) & (0.158) & (0.060) \\
  & & & \\
 Distance to Scotland & -0.648^{***} & -0.880^{**} & -0.940^{***} \\
  & (0.216) & (0.407) & (0.340) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 150 & 150 & 150 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-157.783} & \multicolumn{1}{c}{-79.540} & \multicolumn{1}{c}{-283.889} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
Wrote Conley tables for spec: ownOther_sk

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:39
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (ownOther_arak, 50 km)}
  \label{tab:conley_ownOther_arak_50km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.251 & 0.514 & 0.104 \\
  & (0.176) & (0.355) & (0.136) \\
  & & & \\
 ln(On-site Land / Arable km²) & -0.757^{**} & -1.269^{***} & 0.092 \\
  & (0.316) & (0.316) & (0.116) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.331^{**} & -0.283 & 0.065 \\
  & (0.133) & (0.232) & (0.109) \\
  & & & \\
 ln(Alms / Arable km²) & 0.291^{**} & 0.463^{***} & -0.144 \\
  & (0.146) & (0.138) & (0.140) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.483^{***} & 0.439^{**} & 0.044 \\
  & (0.131) & (0.188) & (0.131) \\
  & & & \\
 Small House Proximity (20km) & -0.741 & -1.631^{***} & 0.603 \\
  & (0.657) & (0.587) & (0.577) \\
  & & & \\
 Large House Proximity (20km) & 0.437 & 0.375 & 0.603 \\
  & (0.524) & (0.542) & (0.381) \\
  & & & \\
 Friary Presence & 0.480 & 0.467 & -0.749 \\
  & (0.510) & (0.777) & (1.076) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.872^{**} & -0.873 & 0.045 \\
  & (0.428) & (0.611) & (0.386) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.419 & 0.116 & 0.670^{***} \\
  & (0.406) & (0.409) & (0.231) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.229 & 0.302 & 0.386^{***} \\
  & (0.162) & (0.291) & (0.089) \\
  & & & \\
 Wet 1535 Weather Shock & -0.144 & -0.231 & -0.023 \\
  & (0.261) & (0.287) & (0.190) \\
  & & & \\
 Wet 1536 Weather Shock & 0.204 & 0.604^{**} & 0.489^{***} \\
  & (0.192) & (0.294) & (0.172) \\
  & & & \\
 ln(Population) & 0.387^{**} & 0.431^{**} & 0.049 \\
  & (0.160) & (0.179) & (0.080) \\
  & & & \\
 Distance to Scotland & -0.595^{***} & -0.801^{**} & -0.943^{***} \\
  & (0.229) & (0.337) & (0.233) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 50 & 50 & 50 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-152.648} & \multicolumn{1}{c}{-77.246} & \multicolumn{1}{c}{-283.821} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:40
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (ownOther_arak, 100 km)}
  \label{tab:conley_ownOther_arak_100km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.251^{*} & 0.514^{*} & 0.104 \\
  & (0.135) & (0.301) & (0.114) \\
  & & & \\
 ln(On-site Land / Arable km²) & -0.757^{**} & -1.269^{***} & 0.092 \\
  & (0.358) & (0.253) & (0.083) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.331^{***} & -0.283 & 0.065 \\
  & (0.118) & (0.234) & (0.120) \\
  & & & \\
 ln(Alms / Arable km²) & 0.291^{*} & 0.463^{***} & -0.144 \\
  & (0.166) & (0.089) & (0.117) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.483^{***} & 0.439^{***} & 0.044 \\
  & (0.107) & (0.154) & (0.123) \\
  & & & \\
 Small House Proximity (20km) & -0.741 & -1.631^{***} & 0.603 \\
  & (0.564) & (0.420) & (0.410) \\
  & & & \\
 Large House Proximity (20km) & 0.437 & 0.375 & 0.603^{**} \\
  & (0.364) & (0.595) & (0.286) \\
  & & & \\
 Friary Presence & 0.480 & 0.467 & -0.749 \\
  & (0.468) & (0.690) & (0.972) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.872^{*} & -0.873 & 0.045 \\
  & (0.477) & (0.593) & (0.408) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.419 & 0.116 & 0.670^{***} \\
  & (0.445) & (0.327) & (0.240) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.229^{*} & 0.302 & 0.386^{***} \\
  & (0.135) & (0.195) & (0.062) \\
  & & & \\
 Wet 1535 Weather Shock & -0.144 & -0.231 & -0.023 \\
  & (0.251) & (0.202) & (0.134) \\
  & & & \\
 Wet 1536 Weather Shock & 0.204 & 0.604^{**} & 0.489^{***} \\
  & (0.177) & (0.279) & (0.125) \\
  & & & \\
 ln(Population) & 0.387^{**} & 0.431^{**} & 0.049 \\
  & (0.161) & (0.190) & (0.069) \\
  & & & \\
 Distance to Scotland & -0.595^{**} & -0.801^{**} & -0.943^{***} \\
  & (0.236) & (0.401) & (0.307) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 100 & 100 & 100 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-152.648} & \multicolumn{1}{c}{-77.246} & \multicolumn{1}{c}{-283.821} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

Warning message:
"st_centroid assumes attributes are constant over geometries"

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: Wed, May 13, 2026 - 14:10:42
% Requires LaTeX packages: dcolumn
\begin{table}[H] \centering
  \caption{Full Monastic Model — Conley SEs (ownOther_arak, 150 km)}
  \label{tab:conley_ownOther_arak_150km}
\begin{tabular}{@{\extracolsep{.5pt}}lD{.}{.}{-3} D{.}{.}{-3} D{.}{.}{-3} }
\\[-1.8ex]\hline
\hline \\[-1.8ex]
 & \multicolumn{3}{c}{\textit{Dependent variable:}} \\
\cline{2-4}
\\[-1.8ex] & \multicolumn{1}{c}{muster \textasciitilde} & \multicolumn{1}{c}{primary \textasciitilde} & \multicolumn{1}{c}{seats \textasciitilde} \\
\\[-1.8ex] & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{logistic}} & \multicolumn{1}{c}{\textit{Poisson}} \\
 & \multicolumn{1}{c}{Muster} & \multicolumn{1}{c}{Primary} & \multicolumn{1}{c}{Seats} \\
\\[-1.8ex] & \multicolumn{1}{c}{(1)} & \multicolumn{1}{c}{(2)} & \multicolumn{1}{c}{(3)}\\
\hline \\[-1.8ex]
 ln(Off-site Land / Arable km²) & 0.251^{***} & 0.514^{**} & 0.104 \\
  & (0.095) & (0.222) & (0.097) \\
  & & & \\
 ln(On-site Land / Arable km²) & -0.757^{**} & -1.269^{***} & 0.092 \\
  & (0.356) & (0.204) & (0.069) \\
  & & & \\
 ln(Tithe / Arable km²) & -0.331^{***} & -0.283 & 0.065 \\
  & (0.100) & (0.193) & (0.105) \\
  & & & \\
 ln(Alms / Arable km²) & 0.291^{*} & 0.463^{***} & -0.144 \\
  & (0.159) & (0.077) & (0.096) \\
  & & & \\
 ln(Net Income / Arable km²) & 0.483^{***} & 0.439^{***} & 0.044 \\
  & (0.067) & (0.118) & (0.102) \\
  & & & \\
 Small House Proximity (20km) & -0.741 & -1.631^{***} & 0.603^{*} \\
  & (0.462) & (0.367) & (0.364) \\
  & & & \\
 Large House Proximity (20km) & 0.437 & 0.375 & 0.603^{**} \\
  & (0.306) & (0.584) & (0.301) \\
  & & & \\
 Friary Presence & 0.480 & 0.467 & -0.749 \\
  & (0.444) & (0.572) & (0.800) \\
  & & & \\
 Snubbed Family Proximity (20 km) & -0.872^{*} & -0.873 & 0.045 \\
  & (0.467) & (0.569) & (0.392) \\
  & & & \\
 Court Officer Proximity (20 km) & 0.419 & 0.116 & 0.670^{***} \\
  & (0.409) & (0.284) & (0.227) \\
  & & & \\
 ln(Lay Subsidy per Capita) & 0.229^{*} & 0.302^{*} & 0.386^{***} \\
  & (0.125) & (0.172) & (0.065) \\
  & & & \\
 Wet 1535 Weather Shock & -0.144 & -0.231 & -0.023 \\
  & (0.239) & (0.143) & (0.124) \\
  & & & \\
 Wet 1536 Weather Shock & 0.204 & 0.604^{***} & 0.489^{***} \\
  & (0.145) & (0.232) & (0.123) \\
  & & & \\
 ln(Population) & 0.387^{***} & 0.431^{***} & 0.049 \\
  & (0.137) & (0.153) & (0.058) \\
  & & & \\
 Distance to Scotland & -0.595^{***} & -0.801^{*} & -0.943^{***} \\
  & (0.218) & (0.420) & (0.342) \\
  & & & \\
\hline \\[-1.8ex]
Conley cutoff (km) & 150 & 150 & 150 \\
Kernel & Bartlett & Bartlett & Bartlett \\
Observations & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} & \multicolumn{1}{c}{1,391} \\
Log Likelihood & \multicolumn{1}{c}{-152.648} & \multicolumn{1}{c}{-77.246} & \multicolumn{1}{c}{-283.821} \\
\hline
\hline \\[-1.8ex]
\textit{Note:}  & \multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\
\end{tabular}
\end{table}
Wrote Conley tables for spec: ownOther_arak

All Conley SE tables written to Output/Tables/conley_*.tex

## Section 4: Moran's I — Spatial Autocorrelation Diagnostics

Tests for residual spatial dependence. Reports Moran's I on:
- raw outcomes (`muster`, `primary`, `seats`),
- Pearson residuals from the full monastic model (`total` spec),
- Pearson residuals from the joint elite model.

Two spatial-weights matrices: row-standardized **queen contiguity** (primary)
and **k-nearest neighbors** with k=8 on parish centroids (robustness).

In [6]:
# Moran's I on raw outcomes and GLM Pearson residuals.
pacman::p_load(spdep, xtable)

# --- Build spatial weights once on the full parish set -------------------
nb_queen <- spdep::poly2nb(pdf, queen = TRUE)
lw_queen <- spdep::nb2listw(nb_queen, style = "W", zero.policy = TRUE)

parish_xy_nb01 <- sf::st_coordinates(sf::st_centroid(sf::st_geometry(pdf)))
nb_knn8  <- spdep::knn2nb(spdep::knearneigh(parish_xy_nb01, k = 8))
lw_knn8  <- spdep::nb2listw(nb_knn8, style = "W")

# --- Helper: Moran's I for a numeric vector aligned to pdf rows ----------
morans_row <- function(label, x, keep_rows, lw, lw_label) {
  if (length(keep_rows) < length(lw$neighbours)) {
    lw_use <- spdep::subset.listw(lw, subset = seq_along(lw$neighbours) %in% keep_rows,
                                  zero.policy = TRUE)
  } else {
    lw_use <- lw
  }
  mt <- spdep::moran.test(x, lw_use, zero.policy = TRUE, na.action = na.omit)
  data.frame(
    Model    = label,
    Weights  = lw_label,
    n        = length(x),
    Morans_I = unname(mt$estimate["Moran I statistic"]),
    Expected = unname(mt$estimate["Expectation"]),
    Variance = unname(mt$estimate["Variance"]),
    z        = unname(mt$statistic),
    p_value  = unname(mt$p.value)
  )
}

# --- Raw outcomes --------------------------------------------------------
raw_inputs <- list(
  muster  = pdf$muster,
  primary = pdf$primary,
  seats   = pdf$seats
)

# --- Residuals: full monastic models (split_arak primary spec) -----------
# Use split_arak as the representative per-arable-km² specification.
mon_mods_ref <- full_models_by_spec[["split_arak"]]

resid_inputs <- list(
  "Monastic — Muster"  = mon_mods_ref$muster,
  "Monastic — Primary" = mon_mods_ref$primary,
  "Monastic — Seats"   = mon_mods_ref$seat
)

# --- Build the table ------------------------------------------------------
rows <- list()
for (lw_lab in c("Queen", "KNN-8")) {
  lw_i <- if (lw_lab == "Queen") lw_queen else lw_knn8

  for (nm in names(raw_inputs)) {
    x    <- raw_inputs[[nm]]
    keep <- which(!is.na(x))
    rows[[length(rows) + 1L]] <- morans_row(
      paste0("Raw — ", nm), x[keep], keep, lw_i, lw_lab
    )
  }
  for (nm in names(resid_inputs)) {
    mod  <- resid_inputs[[nm]]
    used <- as.integer(rownames(model.frame(mod)))
    r    <- residuals(mod, type = "pearson")
    rows[[length(rows) + 1L]] <- morans_row(nm, r, used, lw_i, lw_lab)
  }
}
moran_tab_nb01 <- do.call(rbind, rows)
print(moran_tab_nb01, row.names = FALSE)

# --- Write LaTeX ---------------------------------------------------------
moran_tab_fmt <- moran_tab_nb01
moran_tab_fmt$Morans_I <- sprintf("%.3f", moran_tab_fmt$Morans_I)
moran_tab_fmt$Expected <- sprintf("%.4f", moran_tab_fmt$Expected)
moran_tab_fmt$Variance <- sprintf("%.5f", moran_tab_fmt$Variance)
moran_tab_fmt$z        <- sprintf("%.2f", moran_tab_fmt$z)
moran_tab_fmt$p_value  <- ifelse(moran_tab_fmt$p_value < 1e-4, "<1e-4",
                                 sprintf("%.4f", moran_tab_fmt$p_value))
colnames(moran_tab_fmt) <- c("Model", "Weights", "n", "Moran's I",
                             "E[I]", "Var(I)", "z", "p")

print(
  xtable(moran_tab_fmt,
         caption = "Moran's I — raw outcomes and Pearson residuals (split_arak spec).",
         label   = "tab:moran_nb01",
         align   = c("l", "l", "l", "r", "r", "r", "r", "r", "r")),
  include.rownames  = FALSE,
  caption.placement = "top",
  table.placement   = "H",
  file = "Output/Tables/morans_nb01.tex"
)
cat("Wrote Output/Tables/morans_nb01.tex\n")

Warning message in spdep::poly2nb(pdf, queen = TRUE):
"some observations have no neighbours;
if this seems unexpected, try increasing the snap argument."

Warning message in spdep::poly2nb(pdf, queen = TRUE):
"neighbour object has 5 sub-graphs;
if this sub-graph count seems unexpected, try increasing the snap argument."

Warning message in subset.nb(x = nb, subset = subset):
"subsetting caused increase in subgraph count"

Warning message in subset.nb(x = nb, subset = subset):
"subsetting caused increase in subgraph count"

Warning message in subset.nb(x = nb, subset = subset):
"subsetting caused increase in subgraph count"

              Model Weights    n    Morans_I      Expected     Variance
       Raw — muster   Queen 1755  0.03985870 -0.0005714286 0.0002106817
      Raw — primary   Queen 1755  0.02411574 -0.0005714286 0.0002067796
        Raw — seats   Queen 1755  0.16299498 -0.0005714286 0.0002087765
  Monastic — Muster   Queen 1391  0.01694707 -0.0007215007 0.0002644560
 Monastic — Primary   Queen 1391 -0.01087221 -0.0007215007 0.0002420891
   Monastic — Seats   Queen 1391  0.06011523 -0.0007215007 0.0002714619
       Raw — muster   KNN-8 1755  0.04804414 -0.0005701254 0.0001272905
      Raw — primary   KNN-8 1755  0.04435592 -0.0005701254 0.0001249379
        Raw — seats   KNN-8 1755  0.13811735 -0.0005701254 0.0001261418
  Monastic — Muster   KNN-8 1391  0.02697648 -0.0007215007 0.0001821314
 Monastic — Primary   KNN-8 1391  0.02878659 -0.0007215007 0.0001667232
   Monastic — Seats   KNN-8 1391  0.09371822 -0.0007215007 0.0001869576
         z      p_value
  2.785427 2.672866e-03
  1.716791 4.300869e-02
 11.320178 5.212974e-30
  1.086488 1.386316e-01
 -0.652392 7.429258e-01
  3.692423 1.110637e-04
  4.308894 8.203663e-06
  4.019306 2.918486e-05
 12.348313 2.487174e-35
  2.052370 2.006684e-02
  2.285300 1.114763e-02
  6.906899 2.476809e-12

Wrote Output/Tables/morans_nb01.tex